import type { Section } from '../types';

export const airlineRedemptionSection: Section = {
  id: 'airline-redemption',
  name: 'Airline Redemption Setup',
  description: 'Airline-specific redemption rules and award ticket configuration',
  phase: 'launch',
  visibleIf: {
    questionKey: 'program_industry',
    operator: 'eq',
    value: 'Airlines',
  },
  questions: [
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'do_you_have_a_default_redemption',
      label: 'Do you have a Default Redemption Setup that applies when no specific setup matches a member\'s booking?  (Yes / No)  Note: It is recommended to configure at least one Default setup as a fallback.',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'do_you_have_have_specific_redemption',
      label: 'Do you have have Specific Redemption Setups for particular routes, dates, fare classes, itinerary types etc.?  (Yes / No)  (e.g., JFK–BOS Business at 300,000 points/ miles; Economy at 80,000 points/ miles)',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'for_each_redemption_setup_will_the',
      label: 'For each Redemption Setup, will the Award Price be defined as a fixed points value, or a multiplier? (e.g., Fixed: 300,000 points for JFK-BOS or Multiplier - 1.2x applied on the flight price',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_name',
      label: 'Attribute Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'examples',
      label: 'Examples:',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'origin_airport',
      label: 'Origin Airport',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'flight_date',
      label: 'Flight Date',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'setup_name',
      label: 'Setup Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'examples',
      label: 'Examples:',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'default_flight_redemption_pricing_setup_economy',
      label: 'Default Flight Redemption Pricing Setup: Economy',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'jfk_bos_economy_price',
      label: 'JFK-BOS: Economy Price',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
