import type { Section } from '../types';

export const airportEntitySection: Section = {
  id: 'airport-entity',
  name: 'Airport Entity',
  description: 'Airport entity configuration for airline loyalty programs',
  phase: 'launch',
  visibleIf: {
    questionKey: 'program_industry',
    operator: 'eq',
    value: 'Airlines',
  },
  questions: [
    {
      key: 'standard_3_letter_airport_code_assigned',
      label: 'Standard 3-letter airport code assigned by IATA.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'official_full_name_of_the_airport',
      label: 'Official full name of the airport.',
      inputType: 'text',
      required: true,
      pii: true,
    },
    {
      key: 'country_in_which_the_airport_is',
      label: 'Country in which the airport is located (ISO code).',
      inputType: 'number',
      required: true,
      pii: false,
    },
    {
      key: 'primary_city_served_by_the_airport',
      label: 'Primary city served by the airport.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'business_operational_region_classification_used_by',
      label: 'Business/operational region classification used by the client.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'physical_address_of_the_airport',
      label: 'Physical address of the airport.',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'current_lifecycle_state_of_the_airport',
      label: 'Current lifecycle state of the airport in the system.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'geographical_latitude_of_the_airport',
      label: 'Geographical latitude of the airport.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'geographical_longitude_of_the_airport',
      label: 'Geographical longitude of the airport.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'foreign_key_to_a_country_master',
      label: 'Foreign key to a Country master entity (if used).',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: 'reference_to_a_region_entity',
      label: 'Reference to a Region entity.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'identifier_used_by_external_master_data',
      label: 'Identifier used by external master data system.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'flag_to_mark_priority_strategic_airports',
      label: 'Flag to mark priority/strategic airports.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'free_text_notes_specific_to_this',
      label: 'Free-text notes specific to this tenant.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'user_role_who_created_the_airport',
      label: 'User/role who created the airport record.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'timestamp_of_creation',
      label: 'Timestamp of creation.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'user_role_who_last_modified_the',
      label: 'User/role who last modified the record.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'timestamp_of_last_modification',
      label: 'Timestamp of last modification.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'the_zone_in_which_the_airport',
      label: 'The zone in which the airport operates',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_the_iata_code_for',
      label: 'Please provide the IATA code for each Airport (3-letter airport code, e.g., DEL, LHR, JFK).',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_the_full_official_name',
      label: 'Please provide the full official name of each Airport (e.g., Indira Gandhi International Airport, Heathrow Airport). Enter the name exactly as you want it to appear in the system.YesAll',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'please_provide_your_internal_region_zone',
      label: 'Please provide your internal Region/Zone mapping for each Airport, if you use one (e.g., North India, West Zone). If you do not use internal zones, specify "N/A".',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_any_additional_notes_or',
      label: 'Please provide any additional notes or special handling instructions for specific Airports (e.g., seasonal restrictions, curfews). Use this for exceptions or business rules that are not covered by the standard fields.',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
