import type { Section } from '../types';

export const aisenseSection: Section = {
  id: 'aisense',
  name: 'AiSense',
  description: 'AiSense module configuration for intelligent sensing',
  phase: 'launch',
  visibleIf: {
    questionKey: 'modules_purchased',
    operator: 'contains',
    value: 'AiSense',
  },
  questions: [
    {
      key: 'mandatory',
      label: 'Mandatory',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_apis',
      label: 'Generic Across APIs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_apis',
      label: 'Generic Across APIs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_apis',
      label: 'Generic Across APIs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_apis',
      label: 'Member APIs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_apis',
      label: 'Member APIs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_apis',
      label: 'Member APIs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_apis',
      label: 'Member APIs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'retro_claim',
      label: 'Retro Claim',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'retro_claim',
      label: 'Retro Claim',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'retro_claim',
      label: 'Retro Claim',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'retro_claim',
      label: 'Retro Claim',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'batch_summary',
      label: 'Batch Summary',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'batch_summary',
      label: 'Batch Summary',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'batch_summary',
      label: 'Batch Summary',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'batch_summary',
      label: 'Batch Summary',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'batch_summary',
      label: 'Batch Summary',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'batch_summary',
      label: 'Batch Summary',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'pre_processing_failures',
      label: 'Pre-processing Failures',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'pre_processing_failures',
      label: 'Pre-processing Failures',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'pre_processing_failures',
      label: 'Pre-processing Failures',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'post_processing_failures',
      label: 'Post-processing Failures',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'post_processing_failures',
      label: 'Post-processing Failures',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'post_processing_failures',
      label: 'Post-processing Failures',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_success',
      label: 'Accrual Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'accrual_failure',
      label: 'Accrual Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_success',
      label: 'Redemption Success',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_failure',
      label: 'Redemption Failure',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'generic_across_bits',
      label: 'Generic Across BITs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_enrollment',
      label: 'Member Enrollment',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_enrollment',
      label: 'Member Enrollment',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_enrollment',
      label: 'Member Enrollment',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
