import type { Section } from '../types';

export const batchesSection: Section = {
  id: 'batches',
  name: 'Batches',
  description: 'Batch processing configuration for bulk operations',
  phase: 'design',
  questions: [
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'mention_the_sponsor_under_which_the',
      label: 'Mention the sponsor under which the members will get enrolled.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_name_of_the',
      label: 'What is the name of the batch that will be displayed on the GRAVTY UI for system users?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'please_clarify_whether_the_batch_will',
      label: 'Please clarify whether the batch will be executed on an ad hoc basis or a scheduled basis.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_the_batch_is_scheduled_provide',
      label: 'If the batch is scheduled, provide the timeframe within which the batch should start.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_frequency_at_which_the',
      label: 'Specify the frequency at which the batch should repeat, e.g., Hourly/Daily/Weekly/Monthly/Yearly.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_how_often_the_batch_needs',
      label: 'Specify how often the batch needs to repeat as per the set frequency, e.g., Every two weeks/every three months, etc.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch success notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch failure notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'specify_the_file_format_for_the',
      label: 'Specify the file format for the batch: CSV or JSON.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_delimiter_used_in_the',
      label: 'Specify the delimiter used in the batch input file: Comma, Tilde, Pipe, or Semicolon.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'is_the_first_line_of_the',
      label: 'Is the first line of the input file a Header Row? (Yes/No)',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_date_time_format_used',
      label: 'Specify the Date/Time Format used in the batch input file:  - dd-MM-yyyy - MM-dd-yyyy - yyyy-MM-dd - yyyy-MM-dd HH:mm:ss - yyyy-MM-dd HH:mm:ss.SSS - yyyy-MM-dd HH:mm:ss.SSSZ',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'provide_a_sample_input_file_for',
      label: 'Provide a sample input file for the batch.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'member_update_batch',
      label: 'Member Update Batch',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'mention_the_sponsor_under_which_the',
      label: 'Mention the sponsor under which the members will get updated.',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_name_of_the',
      label: 'What is the name of the batch that will be displayed on the GRAVTY UI for system users?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'please_clarify_whether_the_batch_will',
      label: 'Please clarify whether the batch will be executed on an ad hoc basis or a scheduled basis.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_the_batch_is_scheduled_provide',
      label: 'If the batch is scheduled, provide the timeframe within which the batch should start.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_frequency_at_which_the',
      label: 'Specify the frequency at which the batch should repeat, e.g., Hourly/Daily/Weekly/Monthly/Yearly.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_how_often_the_batch_needs',
      label: 'Specify how often the batch needs to repeat as per the set frequency, e.g., Every two weeks/every three months, etc.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch success notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch failure notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'specify_the_file_format_for_the',
      label: 'Specify the file format for the batch: CSV or JSON.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_delimiter_used_in_the',
      label: 'Specify the delimiter used in the batch input file: Comma, Tilde, Pipe, or Semicolon.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'is_the_first_line_of_the',
      label: 'Is the first line of the input file a Header Row? (Yes/No)',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_date_time_format_used',
      label: 'Specify the Date/Time Format used in the batch input file:  - dd-MM-yyyy - MM-dd-yyyy - yyyy-MM-dd - yyyy-MM-dd HH:mm:ss - yyyy-MM-dd HH:mm:ss.SSS - yyyy-MM-dd HH:mm:ss.SSSZ',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'provide_a_sample_input_file_for',
      label: 'Provide a sample input file for the batch.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'product_batch',
      label: 'Product Batch',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'mention_the_sponsor_under_which_the',
      label: 'Mention the sponsor under which the products will be uploaded.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_name_of_the',
      label: 'What is the name of the batch that will be displayed on the GRAVTY UI for system users?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'will_products_be_uploaded_for_multiple',
      label: 'Will products be uploaded for multiple sponsors? Please note that this option is available only when you select the sponsor as the Host Sponsor.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'please_clarify_whether_the_batch_will',
      label: 'Please clarify whether the batch will be executed on an ad hoc basis or a scheduled basis.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_the_batch_is_scheduled_provide',
      label: 'If the batch is scheduled, provide the timeframe within which the batch should start.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_frequency_at_which_the',
      label: 'Specify the frequency at which the batch should repeat, e.g., Hourly/Daily/Weekly/Monthly/Yearly.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_how_often_the_batch_needs',
      label: 'Specify how often the batch needs to repeat as per the set frequency, e.g., Every two weeks/every three months, etc.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch success notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch failure notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'bits_accrual_batch',
      label: 'BITS (Accrual) Batch',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'mention_the_sponsor_under_which_the',
      label: 'Mention the sponsor under which the BITS will be uploaded.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_name_of_the',
      label: 'What is the name of the batch that will be displayed on the GRAVTY UI for system users?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'will_bits_be_uploaded_for_multiple',
      label: 'Will BITs be uploaded for multiple sponsors? Please note that this option is available only when you select the sponsor as the Host Sponsor.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'please_clarify_whether_the_batch_will',
      label: 'Please clarify whether the batch will be executed on an ad hoc basis or a scheduled basis.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_the_batch_is_scheduled_provide',
      label: 'If the batch is scheduled, provide the timeframe within which the batch should start.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_frequency_at_which_the',
      label: 'Specify the frequency at which the batch should repeat, e.g., Hourly/Daily/Weekly/Monthly/Yearly.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_how_often_the_batch_needs',
      label: 'Specify how often the batch needs to repeat as per the set frequency, e.g., Every two weeks/every three months, etc.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch success notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'specify_the_email_addresses_to_whom',
      label: 'Specify the email addresses to whom batch failure notifications should be sent.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'specify_the_file_format_for_the',
      label: 'Specify the file format for the batch: CSV or JSON or Fixed Length File.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_delimiter_used_in_the',
      label: 'Specify the delimiter used in the batch input file: Comma, Tilde, Pipe, or Semicolon.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'is_the_first_line_of_the',
      label: 'Is the first line of the input file a Header Row? (Yes/No)',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_date_time_format_used',
      label: 'Specify the Date/Time Format used in the batch input file:  - dd-MM-yyyy - MM-dd-yyyy - yyyy-MM-dd - yyyy-MM-dd HH:mm:ss - yyyy-MM-dd HH:mm:ss.SSS - yyyy-MM-dd HH:mm:ss.SSSZ',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'at_which_level_will_the_file',
      label: '"At which level will the file include information: Header Level, Line Level, and Payment Level?"',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'does_the_input_file_include_non',
      label: 'Does the input file include non-member records? If the \'File includes non-member records\' option is checked, the system will save all non-member records in the retro table.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'provide_a_sample_input_file_for',
      label: 'Provide a sample input file for the batch.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'are_there_any_character_length_or',
      label: 'Are there any character length or range value validations required for any attribute?',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
