import type { Section } from '../types';

export const bitDataModelSection: Section = {
  id: 'bit-data-model',
  name: 'BIT Data Model',
  description: 'Transaction (BIT) entity attributes and data model configuration',
  phase: 'design',
  questions: [
    {
      key: 'cancel_bit_id',
      label: 'cancel_bit_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_activity_referred_by_member',
      label: 'h_activity_referred_by_member',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_activity_referred_by_member_id',
      label: 'h_activity_referred_by_member_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_base_accrual',
      label: 'h_base_accrual',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bill_due_date',
      label: 'h_bill_due_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bill_paid_date',
      label: 'h_bill_paid_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_amount',
      label: 'h_bit_amount',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_category',
      label: 'h_bit_category',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_currency',
      label: 'h_bit_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_date',
      label: 'h_bit_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_id',
      label: 'h_bit_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_mode',
      label: 'h_bit_mode',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_received_date',
      label: 'h_bit_received_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_source',
      label: 'h_bit_source',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_source_generated_id',
      label: 'h_bit_source_generated_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_status',
      label: 'h_bit_status',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_type',
      label: 'h_bit_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_booking_agent',
      label: 'h_booking_agent',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel","Hospitality"],
    },
    {
      key: 'h_booking_class',
      label: 'h_booking_class',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_card_type',
      label: 'h_card_type',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Banking","NBFC"],
    },
    {
      key: 'h_checkin_facebook_page',
      label: 'h_checkin_facebook_page',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_comment',
      label: 'h_comment',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_corporate_reference',
      label: 'h_corporate_reference',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_created_by',
      label: 'h_created_by',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_current_family_head',
      label: 'h_current_family_head',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_current_family_head_relationship',
      label: 'h_current_family_head_relationship',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_date_of_booking',
      label: 'h_date_of_booking',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel","Hospitality"],
    },
    {
      key: 'h_deal_code',
      label: 'h_deal_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_destination_airport',
      label: 'h_destination_airport',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_destination_airport_code',
      label: 'h_destination_airport_code',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_destination_area',
      label: 'h_destination_area',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_destination_city',
      label: 'h_destination_city',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_destination_country',
      label: 'h_destination_country',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_destination_region',
      label: 'h_destination_region',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_destination_zone',
      label: 'h_destination_zone',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_discount_code',
      label: 'h_discount_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_end_date',
      label: 'h_end_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_enrollment_user',
      label: 'h_enrollment_user',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_facebook_post',
      label: 'h_facebook_post',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_family_member',
      label: 'h_family_member',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_fare_class',
      label: 'h_fare_class',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_fare_type',
      label: 'h_fare_type',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_first_name',
      label: 'h_first_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_flight_code',
      label: 'h_flight_code',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_flight_date',
      label: 'h_flight_date',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_flight_number',
      label: 'h_flight_number',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_flown_class',
      label: 'h_flown_class',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_iata_code',
      label: 'h_iata_code',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_last_name',
      label: 'h_last_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_location',
      label: 'h_location',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_location_name',
      label: 'h_location_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_loyalty_account',
      label: 'h_loyalty_account',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_member_id',
      label: 'h_member_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_member_login',
      label: 'h_member_login',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_member_name',
      label: 'h_member_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_member_tier_class',
      label: 'h_member_tier_class',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_membership_stage_id',
      label: 'h_membership_stage_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_no_of_nights',
      label: 'h_no_of_nights',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel","Hospitality"],
    },
    {
      key: 'h_number_of_pax',
      label: 'h_number_of_pax',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel","Hospitality"],
    },
    {
      key: 'h_offer_name',
      label: 'h_offer_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_operating_flight_code',
      label: 'h_operating_flight_code',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_operating_flight_number',
      label: 'h_operating_flight_number',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_order_id',
      label: 'h_order_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_origin_airport',
      label: 'h_origin_airport',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_origin_airport_code',
      label: 'h_origin_airport_code',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_origin_area',
      label: 'h_origin_area',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_origin_city',
      label: 'h_origin_city',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_origin_country',
      label: 'h_origin_country',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_origin_region',
      label: 'h_origin_region',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_origin_zone',
      label: 'h_origin_zone',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_original_bit_amount',
      label: 'h_original_bit_amount',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_original_bit_amount_currency',
      label: 'h_original_bit_amount_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_passenger_type',
      label: 'h_passenger_type',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_pay_in_amount',
      label: 'h_pay_in_amount',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_pay_in_amount_currency',
      label: 'h_pay_in_amount_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_pay_in_points',
      label: 'h_pay_in_points',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_pay_in_points_currency',
      label: 'h_pay_in_points_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_paying_member_id',
      label: 'h_paying_member_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_payment_mode',
      label: 'h_payment_mode',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_pnr_number',
      label: 'h_pnr_number',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'h_pos_cashier_id',
      label: 'h_pos_cashier_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_pos_id',
      label: 'h_pos_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_prev_family_head',
      label: 'h_prev_family_head',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_prev_family_head_relationship',
      label: 'h_prev_family_head_relationship',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_privilege',
      label: 'h_privilege',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_privilege_id',
      label: 'h_privilege_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_privileges',
      label: 'h_privileges',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_unique_privileges',
      label: 'h_unique_privileges',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_program_id',
      label: 'h_program_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_rate_type',
      label: 'h_rate_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_reason_code',
      label: 'h_reason_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_referral_member_id',
      label: 'h_referral_member_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_rep_designation',
      label: 'h_rep_designation',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_rep_email',
      label: 'h_rep_email',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_rep_id',
      label: 'h_rep_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_savings',
      label: 'h_savings',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_savings_currency',
      label: 'h_savings_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_source_facebook_page',
      label: 'h_source_facebook_page',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_source_member',
      label: 'h_source_member',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_sponsor_id',
      label: 'h_sponsor_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_sponsor_name',
      label: 'h_sponsor_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_start_date',
      label: 'h_start_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_target_member',
      label: 'h_target_member',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'h_tier_change_reason',
      label: 'h_tier_change_reason',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_amount',
      label: 'l_amount',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_amount_currency',
      label: 'l_amount_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_base_accrual',
      label: 'l_base_accrual',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_bit_type',
      label: 'l_bit_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_cost',
      label: 'l_cost',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_cost_currency',
      label: 'l_cost_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_deal_code',
      label: 'l_deal_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_discount_code',
      label: 'l_discount_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_location',
      label: 'l_location',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_loyalty_account',
      label: 'l_loyalty_account',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_order_id',
      label: 'l_order_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_original_amount',
      label: 'l_original_amount',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_original_amount_currency',
      label: 'l_original_amount_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_privilege',
      label: 'l_privilege',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_privilege_id',
      label: 'l_privilege_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_product_category',
      label: 'l_product_category',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_product_external_id',
      label: 'l_product_external_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_product_id',
      label: 'l_product_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_product_line',
      label: 'l_product_line',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_product_name',
      label: 'l_product_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_quantity',
      label: 'l_quantity',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_rep_email',
      label: 'l_rep_email',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_rep_id',
      label: 'l_rep_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_savings',
      label: 'l_savings',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'l_savings_currency',
      label: 'l_savings_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'offer_id',
      label: 'offer_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'primary_bit_id',
      label: 'primary_bit_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'primary_bit_type',
      label: 'primary_bit_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'primary_member_id',
      label: 'primary_member_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'processing_date',
      label: 'processing_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'transfer_privilege_code',
      label: 'transfer_privilege_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'transferee_member_id',
      label: 'transferee_member_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'verification_code',
      label: 'verification_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'payment_method',
      label: 'payment_method',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'amount',
      label: 'amount',
      inputType: 'grid',
      required: false,
      pii: false,
    },
  ],
};
