import type { Section } from '../types';

export const cobrandedCardsSection: Section = {
  id: 'cobranded-cards',
  name: 'Co-branded Cards',
  description: 'Co-branded credit/debit card program configuration',
  phase: 'launch',
  visibleIf: {
    questionKey: 'has_cobranded_card',
    operator: 'eq',
    value: 'true',
  },
  questions: [
    {
      key: 'the_name_of_the_co_brand',
      label: 'the name of the co-brand program.',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'the_issuing_entity_credit_card_company',
      label: 'the issuing entity/ credit card company name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'the_highlights_and_important_features_of',
      label: 'the highlights and important features of the co-brand program',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'the_co_brand_logo',
      label: 'the co-brand logo',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'active_inactive',
      label: 'Active/Inactive',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'general_questions',
      label: 'General Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_types_of_cards_are_expected',
      label: 'What types of cards are expected to be configured under the portfolio?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'would_you_like_to_structure_multiple',
      label: 'Would you like to structure multiple cards under a single portfolio?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'will_these_cards_have_a_defined',
      label: 'Will these cards have a defined validity period?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'should_the_cards_be_closed_once',
      label: 'Should the cards be closed once their validity expires?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'should_any_privileges_be_issued_immediately',
      label: 'Should any privileges be issued immediately upon card issuance to the member?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_primary_objective_of',
      label: 'What is the primary objective of launching the co-branded card (customer acquisition, retention, revenue, or engagement)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_type_of_partners_are_you',
      label: 'What type of partners are you considering (bank, airline, retail, etc.)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'do_you_already_have_a_banking',
      label: 'Do you already have a banking/financial partner in mind, or would you need support in identifying one?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'which_customer_segments_are_you_aiming',
      label: 'Which customer segments are you aiming to address with this co-branded card?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'should_members_be_able_to_view',
      label: 'Should members be able to view card details, statements, and transaction history in the member facing channels like App or Website?',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
