import type { Section } from '../types';

export const customAttributesSection: Section = {
  id: 'custom-attributes',
  name: 'Custom Attributes',
  description: 'Custom attribute definitions for extending entity data models',
  phase: 'design',
  questions: [
    {
      key: 'attribute_backend_name',
      label: 'Attribute Backend Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'custom_sponsor_attributes',
      label: 'Custom Sponsor Attributes',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_backend_name',
      label: 'Attribute Backend Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'custom_sponsor_location_attributes',
      label: 'Custom Sponsor Location Attributes',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_backend_name',
      label: 'Attribute Backend Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'custom_product_attributes',
      label: 'Custom Product Attributes',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_backend_name',
      label: 'Attribute Backend Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'custom_offer_attributes',
      label: 'Custom Offer Attributes',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_backend_name',
      label: 'Attribute Backend Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'custom_payment_attributes',
      label: 'Custom Payment Attributes',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_backend_name',
      label: 'Attribute Backend Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'custom_bit_attributes',
      label: 'Custom BIT Attributes',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_backend_name',
      label: 'Attribute Backend Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
  ],
};
