import type { Section } from '../types';

export const dataMigrationSection: Section = {
  id: 'data-migration',
  name: 'Data Migration',
  description: 'Data migration strategy, scope, source systems, and migration approach',
  phase: 'discovery',
  questions: [
    {
      key: 'source_systems_what_are_the_source',
      label: 'Source Systems: What are the source systems from which data will be extracted and migrated into GRAVTY®? Will it be one system or multiple systems? If multiple, then please specify the type of data coming from each source system.   E.g., One System from where all the data has to be migrated to GRAVT',
      inputType: 'file',
      required: true,
      pii: false,
      placeholder: 'Snow flake',
    },
    {
      key: 'entities_list_what_are_the_entities',
      label: 'Entities List: What are the entities that need to be migrated into GRAVTY®? 1. Member Profile data 2. Member Cards data  3. Member Transaction data 4. Member Point Balance 5. Member Privileges & Expiry data 6. Retro Transaction data 7. SKU Level data 8. Any other entities ',
      inputType: 'file',
      required: true,
      pii: false,
      placeholder: '- Member Profile Data\n- Member Point Balance\n- SKUs Catalogs\n- Promotions Catalogs\n- Member Transaction Data',
    },
    {
      key: 'entities_count_volume_please_specify_the',
      label: 'Entities Count (Volume): Please specify the counts for all the entities mentioned above in question no. 2.1?  Note: For transactions, please specify the time period. For example, the past 6 months data needs to be migrated to GRAVTY.',
      inputType: 'number',
      required: true,
      pii: false,
      placeholder: 'Member Profile Data - 1M\nMember Point Balance - 300K\nSKUs Catalogs - 100K\nPromotions Catalogs - 5K\nMember Transaction Data - 50M',
    },
    {
      key: 'file_format_can_the_data_be',
      label: 'File Format: Can the data be shared in the below file format?    CSV File Specifications:    a) Separator: |    b) Escape Character: “ (quote)    c) Encoding: UTF-8     d) 1 record per line    e) null representation: abc||def    f) Blank (or empty string representation): abc|"”"”|def      Note: Each',
      inputType: 'file',
      required: true,
      pii: false,
    },
    {
      key: 'migration_strategy_cutover_strategy_what_is',
      label: 'Migration Strategy/Cutover Strategy: What is your preferred data migration strategy? 1. One-Time Full Data Migration:  Full data dump is shared at once during cutover with LJI (or) 2. Base and Incremental Data Migration:  Base Load: The full data dump is shared a few days before going live with LJI ',
      inputType: 'select',
      required: true,
      pii: false,
    },
    {
      key: 'file_part_options_can_you_share',
      label: 'File Part Options: Can you share the data in chunks? For example, if the Member data has 10 million records, can you split them into 10 files and share them with LJI?  Note: Files should be split once they reach the maximum limit of 500,000 records per file.',
      inputType: 'file',
      required: true,
      pii: false,
    },
    {
      key: 'data_sharing_options_would_you_like',
      label: 'Data Sharing Options: Would you like to share the data through your SFTP location, or do you need GRAVTY® S3/SFTP access?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'reconciliation_strategy_how_would_you_like',
      label: 'Reconciliation Strategy: How would you like to do the data reconciliation for migrated data (Reconciliation KPIs)?  E.g.  1. Number of members by Tiers 2. Number of transactions by BIT type or by Quarter',
      inputType: 'number',
      required: true,
      pii: false,
      placeholder: '- No. of members by Tiers\n- Member Points Balance\n- Number of transactions by BIT type or by Quarter',
    },
    {
      key: 'data_quality_is_the_data_of',
      label: 'Data Quality: Is the data of good quality? Are there any known data issues that we should be aware of?  E.g. 1. If the Email ID is unique, do we expect any duplicate data? 2. Do we expect any invalid special character (" , \\n) in the email address?',
      inputType: 'select',
      required: true,
      pii: true,
    },
    {
      key: 'who_will_be_the_business_and',
      label: 'Who will be the Business and IT Point of Contact for Data Migration related queries?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'please_share_sample_data_to_understand',
      label: 'Please share sample data to understand the attributes and their mapping.',
      inputType: 'file',
      required: true,
      pii: false,
    },
  ],
};
