import type { Section } from '../types';

export const distanceTableSection: Section = {
  id: 'distance-table',
  name: 'Distance Table',
  description: 'Route distance table configuration for airline mileage programs',
  phase: 'launch',
  visibleIf: {
    questionKey: 'program_industry',
    operator: 'eq',
    value: 'Airlines',
  },
  questions: [
    {
      key: 'please_provide_the_origin_airport_for',
      label: 'Please provide the Origin Airport for each distance record (e.g., DEL, LHR, JFK).',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Use the same IATA code format that you have defined in your Airport master.',
      industryRelevance: ["Airline"],
    },
    {
      key: 'please_provide_the_destination_airport_for',
      label: 'Please provide the Destination Airport for each distance record (e.g., BOM, CDG, DXB).',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Use the same IATA code format that you have defined in your Airport master.',
      industryRelevance: ["Airline"],
    },
    {
      key: 'please_provide_the_numeric_distance_value',
      label: 'Please provide the numeric distance value for each Origin–Destination pair (e.g., 1130.5).',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Indicate the value as a number as distance between two pairs.',
      industryRelevance: ["Airline"],
    },
    {
      key: 'please_provide_any_additional_attributes_you',
      label: 'Please provide any additional attributes you would like to store with each distance record (e.g., corridor name, region pair, lane ID, tariff band).',
      inputType: 'text',
      required: false,
      pii: true,
      placeholder: 'List each additional field with a sample value so we can add it to the Distance Table configuration.',
      industryRelevance: ["Airline"],
    },
    {
      key: 'are_the_accruals_for_airline_pair',
      label: 'Are the accruals for airline pair based on Base Reward? ',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Indicate the value as a number as Base Reward between two pairs.',
      industryRelevance: ["Airline"],
    },
    {
      key: 'are_the_redemptions_for_airline_pair',
      label: 'Are the redemptions for airline pair based on Base Award? ',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Indicate the value as a number as Base Award between two pairs.',
      industryRelevance: ["Airline"],
    },
  ],
};
