import type { Section } from '../types';

export const dwhSection: Section = {
  id: 'dwh',
  name: 'DWH Integration',
  description: 'Data Warehouse integration and table synchronization configuration',
  phase: 'design',
  questions: [
    {
      key: 'target_systems_what_are_the_dwh',
      label: 'Target Systems: What are the DWH systems to which data will be exported from GRAVTY®?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'entities_list_what_are_the_entities',
      label: 'Entities List: What are the entities that need to be exported from GRAVTY®?  1. Member Profile data  2. Member Transaction data  3. Member Point Balances  4. Member Privileges & Expiry data  5. Program Offers  6. Sponsor Products  7. Any other entities',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'file_format_can_the_dwh_system',
      label: 'File Format: Can the DWH system ingest data if the files are exported from GRAVTY® in the format below?   CSV File Specifications:   a) Separator: |   b) Escape Character: “ (quote)   c) Encoding: UTF-8    d) 1 record per line   e) null representation: abc||def   f) Blank (or empty string representa',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'export_cycle_what_is_the_expected',
      label: 'Export Cycle: What is the expected cycle to export the data from GRAVTY®?   The recommended approach for the export cycle that GRAVTY® supports is as follows:  1. Base Load: Full Data dump on or post-launch  2. Incremental Load: Incremental data files exported Daily',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'delta_logic_how_should_the_incremental',
      label: 'Delta Logic: How should the incremental data be identified? LJI\'s preferred method is to identify new or changed records based on their updated timestamps. GRAVTY® captures each record\'s created_ts (Creation timestamp) & updated_ts (Updated timestamp), and the updated_ts field is used to identify th',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'frequency_would_you_like_the_data',
      label: 'Frequency: Would you like the data from GRAVTY® to be exported Hourly/ Daily/ Weekly/ Monthly?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'data_sharing_options_would_you_like',
      label: 'Data Sharing Options: Would you like the data exported to your SFTP location, (or) do you need GRAVTY® S3/SFTP access?  GRAVTY® supports the following data-sharing options:  1. GRAVTY-owned S3 location  2. Client-owned S3 location  3. SFTP  4. Azure Blob Output location  5. GCP Output location  Note',
      inputType: 'select',
      required: false,
      pii: false,
    },
    {
      key: 'metadata_files_would_you_like_gravty',
      label: 'Metadata Files: Would you like GRAVTY® to include metadata files (e.g., no. of files, no. of records, and file names) along with the data exports?',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'folder_structure_which_folder_structure_would',
      label: 'Folder Structure: Which folder structure would you prefer for organizing and managing the files? Option 1: /<env_name>/<table_name>/ Example:  - /UAT/activities_bit/  - /PROD/activities_bit/  Option 2: /<env_name>/<table_name>/<yyyy>/<mm>/<dd>/<hh>/ Example:  - /UAT/activities_bit/2026/04/01/00/  - ',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'compliance_requirements_are_there_any_regulatory',
      label: 'Compliance Requirements: Are there any regulatory or internal compliance requirements we should be aware of for data export?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'who_will_be_the_business_and',
      label: 'Who will be the Business and IT Point of Contact for Data Export related queries?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member',
      label: 'Member',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offers',
      label: 'Offers',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor',
      label: 'Sponsor',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
