import type { Section } from '../types';

export const locationDetailsSection: Section = {
  id: 'location-details',
  name: 'Sponsor Location Details',
  description: 'Detailed location information template for each sponsor location',
  phase: 'design',
  questions: [
    {
      key: 'sponsor_name',
      label: 'Sponsor Name',
      inputType: 'text',
      required: true,
      pii: true,
      helpText: 'Please provide the name of the Sponsor to which the location belongs.',
    },
    {
      key: 'location_name',
      label: 'Location Name',
      inputType: 'text',
      required: true,
      pii: true,
      helpText: 'The location name attribute can be used to show the location\'s name on member-facing channels such as Mobile, Web, etc.',
    },
    {
      key: 'location_type',
      label: 'Location Type',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'The type of location, whether it is a store, restaurant, etc.',
    },
    {
      key: 'location_code',
      label: 'Location Code',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'Please provide the unique code you wish to use for identifying a location in GRAVTY. This location code is sent as part of the BIT (transaction) to GRAVTY. It\'s important to note that the location code cannot be updated once a location is created.',
    },
    {
      key: 'location_phone_number',
      label: 'Location Phone Number',
      inputType: 'text',
      required: false,
      pii: true,
      helpText: 'The phone number for the location that will be visible to members on member-facing channels, such as the app and website.',
    },
    {
      key: 'sponsor_location_enrollment_form_url',
      label: 'Sponsor Location Enrollment Form URL',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Sponsor-specific location URL used to enroll members into the program. Additionally, it can be utilized to track the number of members getting enrolled through the location.',
    },
    {
      key: 'location_facets',
      label: 'Location Facets',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Location facets can be used for optimizing location search and recommendations.',
    },
    {
      key: 'contact_contact_email',
      label: 'Contact: Contact Email',
      inputType: 'text',
      required: false,
      pii: true,
      helpText: 'Email address of the contact person for location. This person will be registered as a GRAVTY user with the role of Sponsor Location Representative and granted access to this specific location.',
    },
    {
      key: 'contact_contact_name',
      label: 'Contact: Contact Name',
      inputType: 'text',
      required: false,
      pii: true,
      helpText: 'Name of the location\'s contact person. The contact name is mandatory if an email is provided.',
    },
    {
      key: 'contact_contact_number',
      label: 'Contact: Contact Number',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Contact number of the contact person.',
    },
    {
      key: 'location_category',
      label: 'Location Category',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'Indicate whether the location is offline or online. If it is an online location, the domain URL is mandatory; for offline locations, the address is mandatory.',
    },
    {
      key: 'location_address_latitude',
      label: 'Location Address: Latitude',
      inputType: 'number',
      required: true,
      pii: true,
      helpText: 'Latitude of the location. This field is mandatory for offline locations.',
    },
    {
      key: 'location_address_longitude',
      label: 'Location Address: Longitude',
      inputType: 'number',
      required: true,
      pii: true,
      helpText: 'Longitude of the location. This field is mandatory for offline locations.',
    },
    {
      key: 'online_url',
      label: 'Online URL',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'The domain URL of the online location. This field is mandatory for online locations.',
    },
    {
      key: 'destination',
      label: 'Destination',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Refers to the location\'s destination, for example, the name of the shopping mall, hotel, etc.',
    },
    {
      key: 'location_image',
      label: 'Location Image',
      inputType: 'file',
      required: false,
      pii: false,
      helpText: 'Location image of the Sponsor.\n[Files must be 200x200px minimum and not exceed 2MB, accepted formats PNG, JPG, and GIF.].',
    },
    {
      key: 'location_opening_hours_opens_at_hh',
      label: 'Location Opening Hours: Opens at (HH:MM)',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'The operation timings of the location. You can set different open times for different days of the week.',
    },
    {
      key: 'location_opening_hours_closes_at_hh',
      label: 'Location Opening Hours: Closes at (HH:MM)',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'The operation timings of the location. You can set different closing times for different days of the week.',
    },
  ],
};
