import type { Section } from '../types';

export const locationDataModelSection: Section = {
  id: 'location-data-model',
  name: 'Sponsor Location Data Model',
  description: 'Location entity attributes and data model configuration',
  phase: 'design',
  questions: [
    {
      key: 'active',
      label: 'active',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'address',
      label: 'address',
      inputType: 'grid',
      required: false,
      pii: true,
    },
    {
      key: 'contact_name',
      label: 'contact_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'contact_phone',
      label: 'contact_phone',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'country',
      label: 'country',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'destination',
      label: 'destination',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'division',
      label: 'division',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'online_url',
      label: 'online_url',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'contact_email',
      label: 'contact_email',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'latitude',
      label: 'latitude',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'location_category',
      label: 'location_category',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'location_code',
      label: 'location_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'location_name',
      label: 'location_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'location_type',
      label: 'location_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'longitude',
      label: 'longitude',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'phone_number',
      label: 'phone_number',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'pin_code',
      label: 'pin_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor',
      label: 'sponsor',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'acquisition_url',
      label: 'acquisition_url',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'state',
      label: 'state',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'image',
      label: 'image',
      inputType: 'grid',
      required: false,
      pii: false,
    },
  ],
};
