import type { Section } from '../types';

export const loyaltyAccountsSection: Section = {
  id: 'loyalty-accounts',
  name: 'Loyalty Accounts',
  description: 'Loyalty currency accounts, tags, and expiration policies',
  phase: 'discovery',
  questions: [
    {
      key: 'currency_name',
      label: 'Currency Name',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'description',
      label: 'Description',
      inputType: 'textarea',
      required: true,
      pii: false,
    },
    {
      key: 'currency_type_for_rewarding_members_redemption',
      label: 'Currency Type  - For Rewarding Members (Redemption Type) - For Recognizing Members via Tiers, Gamification Badges, etc. (Recognition Type) - Partner Program Currency (e.g. AAdvantageMiles in Hilton Honors Program)',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'currency_logo',
      label: 'Currency Logo',
      inputType: 'file',
      required: true,
      pii: false,
    },
    {
      key: 'internal_cost_for_liability_calculation_applicable',
      label: 'Internal Cost (for Liability Calculation) (Applicable only for Redemption Type loyalty account)',
      inputType: 'currency',
      required: true,
      pii: false,
    },
    {
      key: 'selling_price_base_price_for_selling',
      label: 'Selling Price [Base Price for selling Currency to Partners] (Applicable only for Redemption Type loyalty account)',
      inputType: 'currency',
      required: true,
      pii: false,
    },
    {
      key: 'describe_your_expiration_policy_applicable_only',
      label: 'Describe your Expiration Policy (Applicable only for Redemption Type loyalty account)',
      inputType: 'textarea',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_want_balance_in_this',
      label: 'Do you want balance in this Currency to be visible to Members? (Yes/No)',
      inputType: 'boolean',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_want_to_have_a',
      label: 'Do you want to have a withholding period for the redemption of earned points? (Yes/No)?',
      inputType: 'boolean',
      required: true,
      pii: false,
    },
    {
      key: 'define_the_withholding_period_for_redemption',
      label: 'Define the withholding period for redemption of earned points? (In Number of Days)',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_want_to_micro_track',
      label: 'Do you want to micro-track points earned by members using tags? If yes, please provide details. (Applicable only for Redemption Type loyalty account)',
      inputType: 'textarea',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_want_to_expire_points',
      label: 'Do you want to expire points at a tag level? If yes, please provide details. (Applicable only for Redemption Type loyalty account)',
      inputType: 'textarea',
      required: true,
      pii: false,
    },
  ],
};
