import type { Section } from '../types';

export const marketingConnectSection: Section = {
  id: 'marketing-connect',
  name: 'Marketing Connect',
  description: 'Marketing communication platform integration and triggered events',
  phase: 'discovery',
  questions: [
    {
      key: 'what_channels_would_you_like_to',
      label: 'What channels would you like to use for communication with members? Ex - SMS, Email, Push, Web Push, WhatsApp, etc.,',
      inputType: 'text',
      required: true,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'what_will_be_the_marketing_platforms',
      label: 'What will be the Marketing platforms for each of the channels that will be used to communicate with members? Example:  - Email - Braze - SMS - Twilio',
      inputType: 'select',
      required: true,
      pii: true,
    },
    {
      key: 'do_you_need_data_from_gravty',
      label: 'Do you need data from GRAVTY to be synced to any of your existing marketing communication platforms?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'is_the_capability_to_store_data',
      label: 'Is the capability to store data provided by the marketing tools?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'communication_channel_email_or_sms',
      label: 'Communication Channel - Email or SMS',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'will_the_emails_sms_be_categorized',
      label: 'Will the Emails/SMS be categorized as transactional or promotions, or both?',
      inputType: 'text',
      required: true,
      pii: false,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'what_are_the_scenarios_or_instances',
      label: 'What are the scenarios or instances when Emails/SMS need to be sent to the customer?  For example - After a successful enrollment, when a member earns points, when a member redeems points, or when a member\'s tier is upgraded, etc?',
      inputType: 'text',
      required: true,
      pii: false,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'will_the_email_templates_sms_templates',
      label: 'Will the Email Templates/SMS Templates be stored in GRAVTY or the Marketing Platform?',
      inputType: 'text',
      required: true,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'if_the_marketing_platform_is_responsible',
      label: 'If the Marketing Platform is responsible for storing the templates, could you provide details about the Email/SMS Trigger API for understanding how to send Dynamic Attributes?',
      inputType: 'textarea',
      required: true,
      pii: true,
    },
    {
      key: 'is_there_a_bulk_api_available',
      label: 'Is there a Bulk API available for sending multiple members, such as during the launch of an offer? If so, what is the limit of members that can be sent in a single chunk or packet?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'could_you_provide_information_on_the',
      label: 'Could you provide information on the API Timeout, Concurrency of the API, and the Throttling Limit of the API?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'communication_channel_sync',
      label: 'Communication Channel - Sync',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_are_different_usecases_for_which',
      label: 'What are different usecases for which the data need to be synced? In each use case, what are the Dynamic Attributes that need to be sent?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'what_are_the_scenarios_or_instances',
      label: 'What are the scenarios or instances when the sync need to be sent?  For example - After a successful enrollment, when a member earns points, when a member redeems points, or when a member\'s tier is upgraded, etc?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'what_is_the_webhook_api_url',
      label: 'What is the Webhook API URL?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'what_will_be_the_authorization_type',
      label: 'What will be the Authorization Type? Authorization Type to be used for the API URL. GRAVTY supports Basic and OAuth 2.0 authorizations in Webhook',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'communication_channel_whatsapp',
      label: 'Communication Channel - WhatsApp',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_are_the_scenarios_or_instances',
      label: 'What are the scenarios or instances when communication need to be sent to the customer?  For example - After a successful enrollment, when a member earns points, when a member redeems points, or when a member\'s tier is upgraded, etc?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'what_is_the_api_that_will',
      label: 'What is the API that will be used in this scenario? ',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'is_there_a_bulk_api_available',
      label: 'Is there a Bulk API available for sending communication to multiple members, such as during the launch of an offer? If so, what is the limit of members that can be sent in a single chunk or packet?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'could_you_provide_information_on_the',
      label: 'Could you provide information on the API Timeout, Concurrency of the API, and the Throttling Limit of the API?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'is_there_a_sandbox_or_uat',
      label: 'Is there a sandbox or UAT (User Acceptance Testing) environment provided by the service? If so, could you please share the login details?',
      inputType: 'text',
      required: true,
      pii: false,
    },
  ],
};
