import type { Section } from '../types';

export const memberDataModelSection: Section = {
  id: 'member-data-model',
  name: 'Member Data Model',
  description: 'Member profile attributes and data model configuration',
  phase: 'design',
  questions: [
    {
      key: 'address_line1',
      label: 'address_line1',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'address_line2',
      label: 'address_line2',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'alias',
      label: 'alias',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'annual_income',
      label: 'annual_income',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'apple_uid',
      label: 'apple_uid',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'associate_id',
      label: 'associate_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'behaviour_value',
      label: 'behaviour_value',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'bit_class',
      label: 'bit_class',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'bit_rank',
      label: 'bit_rank',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'bit_score',
      label: 'bit_score',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'bit_value',
      label: 'bit_value',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'companion_designation',
      label: 'companion_designation',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'companion_member',
      label: 'companion_member',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'company',
      label: 'company',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'corporate',
      label: 'corporate',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'country',
      label: 'country',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'date_of_birth',
      label: 'date_of_birth',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'date_of_joining',
      label: 'date_of_joining',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'days_since_bit',
      label: 'days_since_bit',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'email',
      label: 'email',
      inputType: 'grid',
      required: false,
      pii: true,
    },
    {
      key: 'enrolling_location',
      label: 'enrolling_location',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'enrolling_sponsor',
      label: 'enrolling_sponsor',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'enrollment_channel',
      label: 'enrollment_channel',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'enrollment_referrer',
      label: 'enrollment_referrer',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'enrollment_touchpoint',
      label: 'enrollment_touchpoint',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'enrollment_user',
      label: 'enrollment_user',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'ethnicity',
      label: 'ethnicity',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'external_id',
      label: 'external_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'facebook_id',
      label: 'facebook_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'family_designation',
      label: 'family_designation',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'family_head',
      label: 'family_head',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'family_head_points_share',
      label: 'family_head_points_share',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'family_head_relationship',
      label: 'family_head_relationship',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'favorite_categories',
      label: 'favorite_categories',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'favorite_drink',
      label: 'favorite_drink',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'favorite_food',
      label: 'favorite_food',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'favorite_restaurant',
      label: 'favorite_restaurant',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'favorite_sport',
      label: 'favorite_sport',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'fb_friends',
      label: 'fb_friends',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'first_name',
      label: 'first_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'food_preference',
      label: 'food_preference',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'gender',
      label: 'gender',
      inputType: 'grid',
      required: false,
      pii: true,
    },
    {
      key: 'googleplus_id',
      label: 'googleplus_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'highest_education',
      label: 'highest_education',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'hobbies',
      label: 'hobbies',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'influence_value',
      label: 'influence_value',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'institution',
      label: 'institution',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'job_title',
      label: 'job_title',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'last_accrual_date',
      label: 'last_accrual_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'last_activity_date',
      label: 'last_activity_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'last_name',
      label: 'last_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'last_redemption_date',
      label: 'last_redemption_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'latitude',
      label: 'latitude',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'linkedin_id',
      label: 'linkedin_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'longitude',
      label: 'longitude',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'marital_status',
      label: 'marital_status',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'member_id',
      label: 'member_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'member_name',
      label: 'member_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'member_type',
      label: 'member_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'membership_stage',
      label: 'membership_stage',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'membership_tenure',
      label: 'membership_tenure',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'middle_name',
      label: 'middle_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'mobile',
      label: 'mobile',
      inputType: 'grid',
      required: false,
      pii: true,
    },
    {
      key: 'mode_of_communication',
      label: 'mode_of_communication',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'mother_tongue',
      label: 'mother_tongue',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'nationality',
      label: 'nationality',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'number_of_children',
      label: 'number_of_children',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'passport_number',
      label: 'passport_number',
      inputType: 'grid',
      required: false,
      pii: false,
      industryRelevance: ["Airline","Travel"],
    },
    {
      key: 'pinterest_id',
      label: 'pinterest_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'preferred_location',
      label: 'preferred_location',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'primary_member',
      label: 'primary_member',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'program_opt_in',
      label: 'program_opt_in',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'receive_offers',
      label: 'receive_offers',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'region',
      label: 'region',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'relationship_cost',
      label: 'relationship_cost',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'salutation',
      label: 'salutation',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'tier_class',
      label: 'tier_class',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'tier_end_date',
      label: 'tier_end_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'tier_start_date',
      label: 'tier_start_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'transaction_value',
      label: 'transaction_value',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'twitter_id',
      label: 'twitter_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'wedding_anniversary',
      label: 'wedding_anniversary',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'zipcode',
      label: 'zipcode',
      inputType: 'grid',
      required: false,
      pii: false,
    },
  ],
};
