import type { Section } from '../types';

export const memberServicesSection: Section = {
  id: 'member-services',
  name: 'Member Services',
  description: 'Customer service operations and member service configurations',
  phase: 'design',
  questions: [
    {
      key: '16_member_services_points_adjustment',
      label: 'Points Adjustment',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_bit_creation',
      label: 'BIT Creation',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_bit_cancellation',
      label: 'BIT Cancellation',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_profile_update',
      label: 'Profile Update',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_tier_change',
      label: 'Tier Change',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_merge_member',
      label: 'Merge Member',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_membership_stage_change',
      label: 'Membership Stage Change',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_membership_deletion',
      label: 'Membership Deletion',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_membership_cancellation',
      label: 'Membership Cancellation',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_award_redemption',
      label: 'Award Redemption',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_privilege_issuance',
      label: 'Privilege Issuance',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_privilege_extension',
      label: 'Privilege Extension',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_privilege_consumption',
      label: 'Privilege Consumption',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_reinstate_used_privilege',
      label: 'Reinstate Used Privilege',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_privilege_cancellation',
      label: 'Privilege Cancellation',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_privilege_choice_and',
      label: 'Privilege Choice and Swap',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_privilege_transfer',
      label: 'Privilege Transfer',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_points_transfer',
      label: 'Points Transfer',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_offer_acceptance',
      label: 'Offer Acceptance',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_member_services_points_expiry_extension',
      label: 'Points Expiry Extension',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_what',
      label: 'What is the preferred Visible Name for this service?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_1_points_adjustment_service_what',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_what',
      label: 'What are the Permitted Values for "Adjustment Type" (e.g., Reward, Redeem)? ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_which',
      label: 'Which attributes (Adjustment Type, BIT Date, Sponsor ID, Location, Loyalty Account, Reward Tag, Points To Adjust, Reason Code, Linked BIT ID, Comment, Redeem from Pool) should be used? ',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_for',
      label: 'For "Reason Code," do you have a predefined list of reasons for tracking? ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_should',
      label: 'Should the "BIT Date" default to the current system date or allow manual entry? ',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_aside',
      label: 'Aside from "Loyalty Account" and "Points to Transfer," do you need a Comment field?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_are',
      label: 'Are there any Additional Attributes needed on the execution screen (e.g., Reason Code, Reference ID)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_for',
      label: 'For any additional attributes, what are the Permitted Values or Default Values?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_for',
      label: 'For "Reward" adjustments, which specific Loyalty Account should receive the points? ',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_for',
      label: 'For "Redeem" adjustments, which specific Loyalty Account (Wallet) should the points be deducted from? ',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_1_points_adjustment_service_when',
      label: 'When "Redeem from Pool" is selected, which corporate pool/sponsor account should the points be reconciled with? ',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_what',
      label: 'What is the unique Name for this BIT Creation Template?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_2_bit_creation_template_which',
      label: 'Which BIT Type (e.g., Spend, Purchase) should this be associated with?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_what',
      label: 'What is the Description of this template\'s purpose?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_which',
      label: 'Which Header Attributes (Sponsor ID, BIT Date, etc.) are required?',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_which',
      label: 'Which of the header attributes must be mandatory vs. optional?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_does',
      label: 'Does this transaction require Itemized Lines (e.g., SKU, Category)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_what',
      label: 'What specific Line Attributes need to be captured for each item?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_does',
      label: 'Does this transaction require payment level details (e.g., Payment Method, Amount)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_2_bit_creation_template_what',
      label: 'What Payment Attributes (Payment Type, Currency, etc.) are needed?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_what_is',
      label: 'What is the preferred Visible Name for the cancellation service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_3_bit_cancellation_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_which_attributes',
      label: 'Which attributes (Reason Code, Comment, Activity Type, Product External ID, Quantity) should be used?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_for_activity',
      label: 'For Activity Type, what are the permitted values (e.g., Reversal, Partial Refund)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_what_is',
      label: 'What is the default Activity Type when the screen opens?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_for_reason',
      label: 'For Reason Code, what are the specific reasons for cancellation (e.g., Customer Request, Error, Refund)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_does_your',
      label: 'Does your program allow Partial Cancellations (canceling only a portion of the points or items)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_if_partial',
      label: 'If partial cancellation is allowed, should the Quantity attribute be mandatory?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_3_bit_cancellation_are_there',
      label: 'Are there any Additional Attributes (custom fields) needed for audit or reporting during a cancellation?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_4_profile_update_what_is',
      label: 'What is the preferred Visible Name for the profile update service ?',
      inputType: 'file',
      required: false,
      pii: true,
    },
    {
      key: '16_4_profile_update_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_what_is',
      label: 'What is the preferred Visible Name for the tier change service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_5_tier_change_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_which_attributes',
      label: 'Which attributes (Tier Change Reason, BIT Date, Tier Class Code, Tier Code, New Tier End Date, Comment) should be used?',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_what_are',
      label: 'What are the Permitted Reasons for a manual tier change (e.g., Goodwill, Tier Match, Correction)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_which_tier',
      label: 'Which Tier Classes and Tier Codes (levels) should be available for selection in this service?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_should_the',
      label: 'Should the BIT Date default to the current system date?',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_is_a',
      label: 'Is a Comment required for audit purposes when a tier is changed manually?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_when_a',
      label: 'When a tier is changed, should the New Tier End Date be calculated automatically based on program rules or entered manually?',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_5_tier_change_are_there',
      label: 'Are there any Additional Attributes (custom fields) needed to capture more data (e.g., Requestor ID, Ticket Number)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_6_member_merge_what_is',
      label: 'What is the preferred Visible Name for the member merge service',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_6_member_merge_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_6_member_merge_should_the',
      label: 'Should the system Enable Transfer of Vertical Entities (e.g., specific linked assets/data) during Member Merge if vertical entities are present?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_6_member_merge_should_the',
      label: 'Should the Comment field be mandatory to document the reason for the merger?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_7_membership_stage_change_what',
      label: 'What is the preferred Visible Name for this service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_7_membership_stage_change_what',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_7_membership_stage_change_what',
      label: 'What are the Permitted Values for "Membership Stage"? (It can be:  Active, Cancelled, Deleted, Suspended, etc.)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_7_membership_stage_change_aside',
      label: 'Aside from the "Membership Stage," should the Comment field be mandatory for audit purposes?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_7_membership_stage_change_do',
      label: 'Do you need any Additional Attributes captured during this change (e.g., Reason Code, Effective Date, Supporting Ticket ID)?',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_7_membership_stage_change_are',
      label: 'Are there specific Rule Level Blocks (Conditions) that prevent a stage change? (e.g., "Cannot cancel if member has a pending order")',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_8_member_deletion_what_should',
      label: 'What should the Visible Name for the service (e.g., "Membership Deletion" or "Account Closure").',
      inputType: 'number',
      required: false,
      pii: true,
    },
    {
      key: '16_8_member_deletion_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_8_member_deletion_what_are',
      label: 'What are the Permitted Values for "Reason Code"? (It can be: Privacy, Requested by Member, etc.)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_8_member_deletion_aside_from',
      label: 'Aside from the "Reason Code," should the Comment field be mandatory for audit purposes?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_8_member_deletion_are_any',
      label: 'Are any additional attributes required to be captured as part of this change?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_9_membership_cancellation_what_is',
      label: 'What is the preferred Visible Name for the cancellation service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_9_membership_cancellation_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_9_membership_cancellation_what_are',
      label: 'What are the Permitted Values for "Membership Cancellation Reason"? (e.g., Admin Action, Member Request)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_9_membership_cancellation_should_the',
      label: 'Should the Comment field be mandatory to ensure a narrative audit trail for every cancellation?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_9_membership_cancellation_do_you',
      label: 'Do you need any Additional Attributes (custom fields) to be captured (e.g., Request Date, Ticket Reference Number)?',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_10_award_redemption_what_should',
      label: 'What should the Visible Name for the service?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_10_award_redemption_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_10_award_redemption_do_you',
      label: 'Do you need any Additional Attributes (custom fields) to be captured (e.g., Request Date, Ticket Reference Number)?',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_11_privilege_issuance_what_should',
      label: 'What should the Visible Name for the service?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_11_privilege_issuance_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_11_privilege_issuance_what_are',
      label: 'What are the Permitted Values for the "Reason Code"?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_11_privilege_issuance_which_sponsor',
      label: 'Which Sponsor IDs should be permitted for selection?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_11_privilege_issuance_for_privilege',
      label: 'For Privilege Quantity, what are the validation requirements (Mandatory status, Min/Max limits, and Default value)?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_11_privilege_issuance_should_the',
      label: 'Should the Comment field be mandatory to ensure an audit trail for issuance?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_11_privilege_issuance_apart_from',
      label: 'Apart from privilege issuance, are there any other actions triggered by this rule?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_12_privilege_extension_what_should',
      label: 'What should the Visible Name for the service?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_12_privilege_extension_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_12_privilege_extension_which_sponsor',
      label: 'Which Sponsor IDs (Partners/Groups) are permitted to authorize an extension?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_12_privilege_extension_what_are',
      label: 'What are the Permitted Values for the "Privilege Extension Reason"?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_12_privilege_extension_should_the',
      label: 'Should the Comment field be mandatory to ensure a narrative audit trail for the extension?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_12_privilege_extension_specify_any',
      label: 'Specify any Additional Attributes (custom fields) required to be captured for this service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_12_privilege_extension_apart_from',
      label: 'Apart from privilege issuance, are there any other actions triggered by this rule?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_13_privilege_consumption_what_is',
      label: 'What is the preferred Visible Name for this service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_13_privilege_consumption_what_service',
      label: 'What Service Description should be displayed to help the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_13_privilege_consumption_what_are',
      label: 'What are the Permitted Sponsors (Sponsor IDs) allowed to process consumption?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_13_privilege_consumption_input_the',
      label: 'Input the Location where privilege will be consumed?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_13_privilege_consumption_aside_from',
      label: 'Aside from Sponsor and Location, should Comment be mandatory for audit purposes?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_13_privilege_consumption_are_there',
      label: 'Are there Additional Attributes needed (e.g., Receipt Number, Staff ID, Channel)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_14_reinstate_used_privilege_what',
      label: 'What is the preferred Visible Name for this service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_14_reinstate_used_privilege_what',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_14_reinstate_used_privilege_what',
      label: 'What are the Permitted Values for the "Privilege Reinstatement Reason"? (e.g., Member Request, Service Recovery)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_14_reinstate_used_privilege_should',
      label: 'Should the Comment field be mandatory to ensure a narrative audit trail for every reinstatement?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_14_reinstate_used_privilege_do',
      label: 'Do you need any Additional Attributes captured during this process (e.g., Original Transaction ID, Approver ID)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_15_privilege_cancellation_what_is',
      label: 'What is the preferred Visible Name for this service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_15_privilege_cancellation_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_15_privilege_cancellation_what_are',
      label: 'What are the Permitted Values for the "Privilege Cancellation Reason"?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_15_privilege_cancellation_should_the',
      label: 'Should the Comment field be mandatory to ensure a narrative audit trail for every reinstatement?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_15_privilege_cancellation_do_you',
      label: 'Do you need any Additional Attributes captured during this process (e.g., Original Transaction ID, Approver ID)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_16_privilege_choice_and_swap',
      label: 'What is the preferred Visible Name for this service ?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_16_privilege_choice_and_swap',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_17_privilege_transfer_what_is',
      label: 'What is the preferred Visible Name for the privilege transfer service?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_17_privilege_transfer_what_service',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_17_privilege_transfer_what_are',
      label: 'What are the Permitted Values for the "Reason Code"? (e.g., Family Transfer, Gifting, Compensation)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_17_privilege_transfer_should_reason',
      label: 'Should Reason Code and Comment be changed to Mandatory for audit purposes?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_17_privilege_transfer_do_you',
      label: 'Do you need to capture any Additional Attributes (e.g., Relationship to Receiver, Request ID)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_do',
      label: 'Do you want to restrict point transfers based on the member\'s stage?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_which',
      label: 'Which membership stages are eligible to send (Transferor) points?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_which',
      label: 'Which membership stages are eligible to receive (Transferee) points?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_should',
      label: 'Should there be a limit on how many points an individual member can send?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_which',
      label: 'Which Loyalty Account should the transferor limit apply to?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_what',
      label: 'What is the frequency/period for this limit?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_what',
      label: 'What is the Minimum number of points a member can send in a single transaction?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_what',
      label: 'What is the Maximum number of points a member can send within the selected period?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_should',
      label: 'Should there be a limit on how many points an individual member can receive?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_which',
      label: 'Which Loyalty Account should the receiving limit apply to?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_what',
      label: 'What is the frequency/period for the receiving limit?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_what',
      label: 'What is the Minimum number of points a member can receive in a single transaction?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_what',
      label: 'What is the Maximum number of points a member can receive within the selected period?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_aside',
      label: 'Aside from "Loyalty Account" and "Points to Transfer," do you need a Comment field?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_are',
      label: 'Are there any Additional Attributes needed on the execution screen (e.g., Reason Code, Reference ID)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_18_points_transfer_service_for',
      label: 'For any additional attributes, what are the Permitted Values or Default Values?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_19_offer_acceptance_service_what',
      label: 'What is the preferred Visible Name for the offer acceptance service?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_19_offer_acceptance_service_what',
      label: 'What Service Description should be displayed to help operators understand the service?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_19_offer_acceptance_service_what',
      label: 'What are the Permitted Values for the "Reason Code"? (e.g., Customer Requested, Marketing Campaign)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_19_offer_acceptance_service_should',
      label: 'Should the Reason Code be changed from non-mandatory to Mandatory for better tracking?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_19_offer_acceptance_service_should',
      label: 'Should the Comment field be mandatory to ensure an audit trail of why an offer was manually accepted?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_19_offer_acceptance_service_do',
      label: 'Do you need any Additional Attributes captured (e.g., Reference ID, Source of Request, Promo Code)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'What is the preferred Visible Name for the expiry extension service?',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'What Service Description should be displayed to the operator?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'Which Loyalty Accounts (wallets) are eligible for manual expiry extension?',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'Which Permitted Tags (point types) can be extended? (e.g., Bonus, Brand Bonus, Base)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'Expires In: What is the "time-to-live" threshold for eligibility? (e.g., Only points expiring in the next 5 days can be extended)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'Max Extension Limit: What is the maximum duration an operator can extend points by? (e.g., Cannot extend more than 6 months)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'Should Reason Code be changed to Mandatory for audit purposes?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'What are the Permitted Values for the Extension Reason (e.g., Service Recovery, Goodwill)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'Need to Define the New Expiry Date of the Points ',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: '16_20_points_expiry_extension_s',
      label: 'Should the Comment field be mandatory to explain the business case for extension?',
      inputType: 'textarea',
      required: false,
      pii: false,
    },
  ],
};
