import type { Section } from '../types';

export const offersOverviewSection: Section = {
  id: 'offers-overview',
  name: 'Offers Overview',
  description: 'Promotional offers, campaigns, and offer management configuration',
  phase: 'discovery',
  questions: [
    {
      key: 'reward_offers',
      label: 'Reward Offers',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'award_offers',
      label: 'Award Offers',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'deal_offers',
      label: 'Deal Offers',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'privilege_offers',
      label: 'Privilege Offers',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'reward_offer',
      label: 'Reward Offer',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'question',
      label: 'Question',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'the_base_offer_is_applicable_to',
      label: 'The Base offer is applicable to all member transactions in the program and extends to all sponsors unless explicitly excluded within the offer rules. Will there be Base offers in the program? If so, kindly specify the number of Base offers.',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_priority_for_base_offers',
      label: 'Specify the priority for Base offers if multiple such offers exist. If multiple offers are applied to a particular transaction, their application will follow the priority sequence.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'template_to_share_reward_offer_details',
      label: 'Template to share Reward Offer Details',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'reward_offer_setup',
      label: 'Reward Offer Setup',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_details',
      label: 'OFFER DETAILS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_title',
      label: 'Offer Title',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor',
      label: 'Sponsor',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_subtitle',
      label: 'Offer Subtitle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_description',
      label: 'Offer Description',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_visibility',
      label: 'Offer Visibility',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_visibility_toggle',
      label: 'Member Visibility Toggle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'base_offer_toggle_activating_this_toggle',
      label: 'Base Offer Toggle: - Activating this toggle validates the offer for all sponsors in the program. - This toggle is visible only when the sponsor is the Host sponsor.',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'validity_timeframe',
      label: 'Validity Timeframe',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_acceptance',
      label: 'Offer Acceptance',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_execution_schedule',
      label: 'Offer Execution Schedule',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'limit_and_frequency_per_member_per',
      label: 'Limit and Frequency Per member - Per Day - Per Month - Lifetime - Weekly',
      inputType: 'select',
      required: false,
      pii: false,
    },
    {
      key: 'offer_execution_control',
      label: 'OFFER EXECUTION CONTROL',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_external_id',
      label: 'Offer External ID',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'priority',
      label: 'Priority',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'custom_attributes',
      label: 'CUSTOM ATTRIBUTES',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_name',
      label: 'Attribute name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'locations',
      label: 'LOCATIONS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'is_the_offer_applicable_to_all',
      label: 'Is the Offer applicable to all locations?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_not_kindly_specify_whether_eligible',
      label: 'If not, kindly specify whether eligible locations will be selected based on geographical or attribute-based criteria, and provide details regarding the respective criteria.',
      inputType: 'textarea',
      required: false,
      pii: false,
    },
    {
      key: 'member_segment',
      label: 'MEMBER SEGMENT',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'define_the_member_segment_to_which',
      label: 'Define the member segment to which this offer applies.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_rules',
      label: 'OFFER RULES',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_the_reward_offer_rules',
      label: 'Please provide the reward offer rules.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'template_to_share_award_offer_details',
      label: 'Template to share Award Offer Details',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'award_offer_setup',
      label: 'Award Offer Setup',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_details',
      label: 'OFFER DETAILS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_title',
      label: 'Offer Title',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor',
      label: 'Sponsor',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_subtitle',
      label: 'Offer Subtitle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_description',
      label: 'Offer Description',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_visibility',
      label: 'Offer Visibility',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_visibility_toggle',
      label: 'Member Visibility Toggle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'validity_timeframe',
      label: 'Validity Timeframe',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'maximum_usage_and_frequency',
      label: 'Maximum Usage and Frequency',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'details',
      label: 'DETAILS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'associated_product',
      label: 'Associated Product',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'product_cost',
      label: 'Product Cost',
      inputType: 'currency',
      required: false,
      pii: false,
    },
    {
      key: 'award_pricing',
      label: 'Award Pricing',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'conversion_rate',
      label: 'Conversion Rate',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'award_validity',
      label: 'Award Validity',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'limit_and_frequency_per_member_per',
      label: 'Limit and Frequency Per member - Per Day - Per Month - Lifetime - Weekly',
      inputType: 'select',
      required: false,
      pii: false,
    },
    {
      key: 'offer_execution_control',
      label: 'OFFER EXECUTION CONTROL',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_external_id',
      label: 'Offer External ID',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'custom_attributes',
      label: 'CUSTOM ATTRIBUTES',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_name',
      label: 'Attribute name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'locations',
      label: 'LOCATIONS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'is_the_offer_applicable_to_all',
      label: 'Is the Offer applicable to all locations?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_not_kindly_specify_whether_eligible',
      label: 'If not, kindly specify whether eligible locations will be selected based on geographical or attribute-based criteria, and provide details regarding the respective criteria.',
      inputType: 'textarea',
      required: false,
      pii: false,
    },
    {
      key: 'member_segment',
      label: 'MEMBER SEGMENT',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'define_the_member_segment_to_which',
      label: 'Define the member segment to which this offer applies.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_rules',
      label: 'OFFER RULES',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_the_award_offer_rules',
      label: 'Please provide the award offer rules.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'template_to_share_privilege_offer_details',
      label: 'Template to share Privilege Offer Details',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'privilege_offer_setup',
      label: 'Privilege Offer Setup',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_details',
      label: 'Offer Details',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_title',
      label: 'Offer Title',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor',
      label: 'Sponsor',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_subtitle',
      label: 'Offer Subtitle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_description',
      label: 'Offer Description',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_visibility',
      label: 'Offer Visibility',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_visibility_toggle',
      label: 'Member Visibility Toggle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'validity_timeframe',
      label: 'Validity Timeframe',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'details',
      label: 'DETAILS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'associated_product',
      label: 'Associated Product',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'product_cost',
      label: 'Product Cost',
      inputType: 'currency',
      required: false,
      pii: false,
    },
    {
      key: 'privilege_validity',
      label: 'Privilege Validity',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'not_valid_after',
      label: 'Not Valid After',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_execution_control',
      label: 'OFFER EXECUTION CONTROL',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_external_id',
      label: 'Offer External ID',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'custom_attributes',
      label: 'CUSTOM ATTRIBUTES',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_name',
      label: 'Attribute name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'locations',
      label: 'LOCATIONS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'is_the_offer_applicable_to_all',
      label: 'Is the Offer applicable to all locations?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_not_kindly_specify_whether_eligible',
      label: 'If not, kindly specify whether eligible locations will be selected based on geographical or attribute-based criteria, and provide details regarding the respective criteria.',
      inputType: 'textarea',
      required: false,
      pii: false,
    },
    {
      key: 'member_segment',
      label: 'MEMBER SEGMENT',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'define_the_member_segment_to_which',
      label: 'Define the member segment to which this offer applies.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'template_to_share_deal_offer_details',
      label: 'Template to share Deal Offer Details',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'deal_offer_setup',
      label: 'Deal Offer Setup',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_details',
      label: 'Offer Details',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_title',
      label: 'Offer Title',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor',
      label: 'Sponsor',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_subtitle',
      label: 'Offer Subtitle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_description',
      label: 'Offer Description',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_visibility',
      label: 'Offer Visibility',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'member_visibility_toggle',
      label: 'Member Visibility Toggle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'validity_timeframe',
      label: 'Validity Timeframe',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'maximum_usage_and_frequency',
      label: 'Maximum Usage and Frequency',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'details',
      label: 'DETAILS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'deal_code',
      label: 'Deal Code',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'limit_and_frequency_per_member_per',
      label: 'Limit and Frequency Per member - Per Day - Per Month - Lifetime - Weekly',
      inputType: 'select',
      required: false,
      pii: false,
    },
    {
      key: 'offer_execution_control',
      label: 'OFFER EXECUTION CONTROL',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'offer_external_id',
      label: 'Offer External ID',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'custom_attributes',
      label: 'CUSTOM ATTRIBUTES',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_name',
      label: 'Attribute name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'locations',
      label: 'LOCATIONS',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'is_the_offer_applicable_to_all',
      label: 'Is the Offer applicable to all locations?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'if_not_kindly_specify_whether_eligible',
      label: 'If not, kindly specify whether eligible locations will be selected based on geographical or attribute-based criteria, and provide details regarding the respective criteria.',
      inputType: 'textarea',
      required: false,
      pii: false,
    },
    {
      key: 'member_segment',
      label: 'MEMBER SEGMENT',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'define_the_member_segment_to_which',
      label: 'Define the member segment to which this offer applies.',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
