import type { Section } from '../types';

export const offerKpiSection: Section = {
  id: 'offer-kpi',
  name: 'Offer KPI Setup',
  description: 'Key Performance Indicators for measuring offer effectiveness',
  phase: 'design',
  questions: [
    {
      key: 'total_sales_influenced_by_the_offer',
      label: 'Total Sales Influenced by the Offer',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'The total amount of sales that were influenced by the offer.',
    },
    {
      key: 'total_cost_incurred',
      label: 'Total Cost Incurred',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'The total cost of running the offer.',
    },
    {
      key: 'no_of_activations_as_a_percentage',
      label: 'No. of Activations as a Percentage of Targeted Members',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'The number of people who activated the offer as a percentage of the total number of members who were targeted with the offer.',
    },
    {
      key: 'no_of_declines_as_a_percentage',
      label: 'No. of Declines as a Percentage of Target Members',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'The number of people who declined the offer as a percentage of the total number of members who were targeted with the offer.',
    },
    {
      key: 'unique_member_transactions_as_a_percentage',
      label: 'Unique Member Transactions as a Percentage of Targeted Members',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'The number of unique members who made a transaction through the offer as a percentage of the total number of members who were targeted with the offer.',
    },
    {
      key: 'fb_shares_as_a_percentage_of',
      label: 'FB Shares as a Percentage of Target Members',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'FB Shares as a Percentage of Target Members.',
    },
    {
      key: 'no_of_transactions_influenced',
      label: 'No. of Transactions Influenced',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'The total number of transactions that were influenced by the offer.',
    },
    {
      key: 'new_member_acquisitions_as_a_percentage',
      label: 'New Member Acquisitions as a Percentage of Target Members',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'New Member Acquisitions as a Percentage of Target Members.',
    },
    {
      key: 'average_rating_for_the_offer',
      label: 'Average Rating for the Offer',
      inputType: 'boolean',
      required: false,
      pii: false,
      helpText: 'Average Rating for the Offer.',
    },
  ],
};
