import type { Section } from '../types';

export const offerDataModelSection: Section = {
  id: 'offer-data-model',
  name: 'Offer Data Model',
  description: 'Offer entity attributes and data model configuration',
  phase: 'design',
  questions: [
    {
      key: 'allow_sponsorfollowers',
      label: 'allow_sponsorfollowers',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'availed_total',
      label: 'availed_total',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'availed_unique',
      label: 'availed_unique',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'average_rating',
      label: 'average_rating',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'batch_id',
      label: 'batch_id',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'budget',
      label: 'budget',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'count',
      label: 'count',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'deal_code',
      label: 'deal_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'end_date',
      label: 'end_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'fb_share',
      label: 'fb_share',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'interval',
      label: 'interval',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'interval_period',
      label: 'interval_period',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'is_base_offer',
      label: 'is_base_offer',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'is_template_based',
      label: 'is_template_based',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'landing_page_url',
      label: 'landing_page_url',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'launch_date',
      label: 'launch_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'location_category',
      label: 'location_category',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'location_urls',
      label: 'location_urls',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'max_period',
      label: 'max_period',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'max_usage_per_user',
      label: 'max_usage_per_user',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'member_target_json',
      label: 'member_target_json',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'member_target_type',
      label: 'member_target_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'member_target_xml',
      label: 'member_target_xml',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'member_visible',
      label: 'member_visible',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'non_cumulative',
      label: 'non_cumulative',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'non_cumulative_level',
      label: 'non_cumulative_level',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'num_of_clients',
      label: 'num_of_clients',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'offer_acceptance_required',
      label: 'offer_acceptance_required',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'offer_description',
      label: 'offer_description',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'offer_name',
      label: 'offer_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'offer_type',
      label: 'offer_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'price',
      label: 'price',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'priority',
      label: 'priority',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'rating_count',
      label: 'rating_count',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'send_notification',
      label: 'send_notification',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'start_date',
      label: 'start_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'status',
      label: 'status',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'subtitle',
      label: 'subtitle',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'template_name',
      label: 'template_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'template_params',
      label: 'template_params',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'total_count',
      label: 'total_count',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'twitter_share',
      label: 'twitter_share',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'valid_for',
      label: 'valid_for',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'valid_period',
      label: 'valid_period',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'valid_until',
      label: 'valid_until',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'validity',
      label: 'validity',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'version',
      label: 'version',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'featured_rank',
      label: 'featured_rank',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'featured',
      label: 'featured',
      inputType: 'grid',
      required: false,
      pii: false,
    },
  ],
};
