import type { Section } from '../types';

export const policiesSection: Section = {
  id: 'policies',
  name: 'Policy Setup & Currency Conversion',
  description: 'Reward policies, redemption policies, membership policies, and currency conversion rates',
  phase: 'discovery',
  questions: [
    {
      key: 'do_you_expect_to_receive_member',
      label: 'Do you expect to receive member transactions in multiple currencies? (Y/N).',
      inputType: 'boolean',
      required: true,
      pii: false,
    },
    {
      key: 'please_provide_all_the_currencies_that',
      label: 'Please provide all the currencies that will be used in the Program.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_have_a_tool_or',
      label: 'Do you have a tool or system capable of periodically updating currency conversion rates in GRAVTY for each currency against the program home currency? e.g. Program Home Currency is USD and the customer transacts in CAD.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_the_initial_currency_conversion',
      label: 'Please provide the initial currency conversion rates against the program currency. For example, if you have USD (Program Currency) and EUR as currencies, provide the conversion value of EUR against your Program currency USD (e.g., 1 USD = 0.93 Euro).',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'is_there_a_standard_reward_rate',
      label: 'Is there a standard reward rate for each currency, such as earning 5 points for every 1 USD or 6 points for every 1 EURO?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_wish_to_impose_restrictions',
      label: 'Do you wish to impose restrictions on rewards per activity, per day, or per month to prevent potential fraud or excess accrual due to human error? (This is a program-level setting that applies to all members.)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'is_there_a_defined_redemption_rate',
      label: 'Is there a defined redemption rate for each currency? If so, kindly provide the corresponding rates for each currency. The redemption rate refers to the monetary value of each point. e..g 1 Point = 0.1 USD, 1 Point = 8 INR.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_wish_to_impose_restrictions',
      label: 'Do you wish to impose restrictions on redemption per activity, per day, or per month to prevent potential fraud or excess points redemption due to human error? (This is a program-level setting that applies to all members.)',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_want_to_manage_the',
      label: 'Do you want to manage the Membership Lifecycle by assigning specific Membership Stages to the Members?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'custom_membership_stage_name',
      label: 'Custom Membership Stage Name',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'do_you_want_to_restrict_program',
      label: 'Do you want to restrict Program Entitlements based on Program Membership Stage? (Access Rewards, Access Awards, Access Privileges, Access Offers, Access Login)',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'membership_stage',
      label: 'Membership Stage',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'can_a_member_hold_multiple_loyalty',
      label: 'Can a member hold multiple loyalty cards? (Y/N)',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'do_you_allow_transferring_points_if',
      label: 'Do you allow transferring points? If yes, please specify permissible transfers.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'from_member',
      label: 'From Member',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'do_you_allow_transferring_privileges_if',
      label: 'Do you allow transferring Privileges? If yes, please mark permissible transfers.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'from_member',
      label: 'From Member',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'does_your_program_provide_family_memberships',
      label: 'Does your Program provide Family Memberships/Householding? (Yes/No)',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'in_case_of_family_memberships_is',
      label: 'In case of Family Memberships, is there any restriction on the size of the Family?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'contribution_to_family_head_do_the',
      label: 'Contribution to Family Head Do the points earned by family members roll up to the Family Head? If yes:     Is the contribution:       -Policy-driven (fixed percentage defined by program), or       -Member-driven (configurable by individual members)? If policy-driven, please specify the split:       ',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: 'contribution_to_family_pool_do_the',
      label: 'Contribution to Family Pool Do the points earned by family members roll up to the Family Pool? If yes:     Is the contribution:       -Policy-driven (fixed percentage defined by program), or       -Member-driven (configurable by individual members)? If policy-driven, please specify the split:       ',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: 'balance_handling_on_family_formation_when',
      label: 'Balance Handling on Family Formation When a family is created:       -Should the existing balance of the Family Head be transferred to the pool?       -Should the existing balance of members joining the family be transferred to the pool?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'redemption_rules_from_family_pool_are',
      label: 'Redemption Rules from Family Pool Are family members allowed to redeem points from the family pool? If yes: Is redemption:        -Open to all members, or        -Restricted based on role (e.g., head vs member) or relationship level? Can redemption permissions be configured at:        -Member level?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'when_member_exit_from_family_if',
      label: 'When Member Exit from Family If a member leaves the family: What happens to the points they contributed to the pool?        -Remain in pool?        -Returned to member?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'complete_family_dissolution_if_all_members',
      label: 'Complete Family Dissolution If all members leave the family:    What should happen to the remaining pool balance?        -Transferred to Family Head?        -Distributed among members?        -Expired/forfeited?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'linking_unlinking_constraints_is_there_a',
      label: 'Linking & Unlinking Constraints Is there a minimum cooling-off period:        -For a member to unlink from a family?        -For a member to join/link to another family?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'governance_control_optional_are_there_any',
      label: 'Governance & Control (Optional) Are there any additional rules or constraints required for:        -Contribution limits?        -Redemption limits?        -Role-based privileges (e.g., Family Head overrides)?        -Audit / visibility of contributions and redemptions?',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
