import type { Section } from '../types';

export const productDataModelSection: Section = {
  id: 'product-data-model',
  name: 'Product Data Model',
  description: 'Product/SKU entity attributes and data model configuration',
  phase: 'design',
  questions: [
    {
      key: 'sponsor',
      label: 'sponsor',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'description',
      label: 'description',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'category',
      label: 'category',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'award_currency',
      label: 'award_currency',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'award_price',
      label: 'award_price',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'valid_for',
      label: 'valid_for',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'valid_period',
      label: 'valid_period',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'valid_start',
      label: 'valid_start',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'valid_end',
      label: 'valid_end',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'dynamic',
      label: 'dynamic',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'active_start',
      label: 'active_start',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'active_end',
      label: 'active_end',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'as_privilege',
      label: 'as_privilege',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'transfer_on_merge',
      label: 'transfer_on_merge',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'has_external_privilege',
      label: 'has_external_privilege',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'has_external_privilege_codes',
      label: 'has_external_privilege_codes',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'external_privilege_service',
      label: 'external_privilege_service',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'privilege_type',
      label: 'privilege_type',
      inputType: 'grid',
      required: false,
      pii: false,
    },
  ],
};
