import type { Section } from '../types';

export const productDetailsSection: Section = {
  id: 'product-details',
  name: 'Sponsor Reward Products Template',
  description: 'Detailed product/SKU information template for reward catalog',
  phase: 'design',
  questions: [
    {
      key: 'product_name',
      label: 'Product Name',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'The name of the product that will be displayed in GRAVTY and on member-facing portals such as Mobile App, Website, etc.,',
    },
    {
      key: 'product_description',
      label: 'Product Description',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Description of the Product.',
    },
    {
      key: 'product_category',
      label: 'Product Category',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'Please specify the product\'s category, such as Electronics, Apparel, Automotive, etc.',
    },
    {
      key: 'product_line',
      label: 'Product Line',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'Please specify the product\'s line, such as BMW 3 Series, Samsung Galaxy Series, Coca-Cola Beverages, etc.,',
    },
    {
      key: 'product_cost',
      label: 'Product Cost',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: 'The cost of the product incurred by the sponsor in the program currency (USD, EUR, MXN, etc.).',
    },
    {
      key: 'product_validity_start_date',
      label: 'Product Validity: Start Date',
      inputType: 'date',
      required: true,
      pii: false,
      helpText: 'The start date of the Product\'s validity.',
    },
    {
      key: 'product_validity_end_date',
      label: 'Product Validity: End Date',
      inputType: 'date',
      required: false,
      pii: false,
      helpText: 'The End date of the Product\'s validity.',
    },
    {
      key: 'base_reward_in',
      label: 'Base Reward In',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'The "Base Reward In" attribute refers to the specific loyalty account against which the base reward value will be configured.',
    },
    {
      key: 'base_reward',
      label: 'Base Reward',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: 'The "Base Reward" attribute refers to the number of points to be rewarded in the respective loyalty account for the purchase of 1 unit of SKU.',
    },
    {
      key: 'product_external_id',
      label: 'Product External ID',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'The Product External ID is a unique identifier for the product or Stock-keeping unit (SKU) that the source system can pass in the BIT (Transaction) when a member purchases SKU(s).',
    },
    {
      key: 'product_facets',
      label: 'Product Facets',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Product facets can be used for optimizing the Product\'s search and recommendations.',
    },
  ],
};
