import type { Section } from '../types';

export const programSection: Section = {
  id: 'program',
  name: 'Program Details',
  description: 'Core program information including name, currency, and date formats',
  phase: 'discovery',
  questions: [
    {
      key: 'please_provide_the_name_of_your',
      label: 'Please provide the name of your Loyalty Program.',
      inputType: 'text',
      required: true,
      pii: true,
      placeholder: 'Skywards Everyday',
    },
    {
      key: 'please_provide_the_name_of_the',
      label: 'Please provide the name of the company that owns the Program.',
      inputType: 'text',
      required: true,
      pii: true,
      placeholder: 'Emirates',
    },
    {
      key: 'please_specify_the_industry_of_the',
      label: 'Please specify the industry of the Host Program. (For Example: Retail, Airlines, Hospitality, Financial Services, Telco etc.)',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Airlines',
    },
    {
      key: 'please_provide_the_program_launch_date',
      label: 'Please provide the Program Launch Date.',
      inputType: 'date',
      required: true,
      pii: false,
    },
    {
      key: 'what_is_the_programs_home_country',
      label: 'What is the Program\'s Home Country?',
      inputType: 'number',
      required: true,
      pii: false,
      placeholder: 'UAE',
    },
    {
      key: 'what_is_the_preferred_date_format',
      label: 'What is the preferred Date format to be followed for the entire program? 1. DD/MM/YYYY 2. MM/DD/YYYY',
      inputType: 'select',
      required: true,
      pii: false,
      placeholder: 'DD/MM/YYYY',
    },
    {
      key: 'what_will_be_the_programs_home',
      label: 'What will be the Program\'s Home Currency to be used for Financial Reporting ?',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'AED',
    },
    {
      key: 'do_you_reward_the_loyalty_currency',
      label: 'Do you reward the Loyalty Currency in whole numbers or in decimals? If in decimals, please specify the decimal precision you want the system to use for display - Decimal Scale Options: 0, 1, 2, 3, and 4.',
      inputType: 'number',
      required: true,
      pii: false,
    },
    {
      key: 'please_specify_the_decimal_precision_you',
      label: 'Please specify the decimal precision you want to use for calculation. - Decimal Scale Options: 0, 1, 2, 3, and 4.',
      inputType: 'number',
      required: true,
      pii: false,
    },
    {
      key: 'is_this_a_multi_national_program',
      label: 'Is this a Multi-National Program?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'do_you_intend_to_launch_a',
      label: 'Do you intend to launch a separate Program by country/geo, or will it be a single, global Program?',
      inputType: 'number',
      required: true,
      pii: false,
      placeholder: 'Single Program',
    },
    {
      key: 'please_provide_the_languages_you_would',
      label: 'Please provide the languages you would like to configure the Program Data. Multiple languages can be specified (For Example: English, German, and Polish).',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'English',
    },
  ],
};
