import type { Section } from '../types';

export const retroRequestSection: Section = {
  id: 'retro-request',
  name: 'Retro Request Setup',
  description: 'Retroactive points claim configuration for airline programs',
  phase: 'launch',
  visibleIf: {
    questionKey: 'program_industry',
    operator: 'eq',
    value: 'Airlines',
  },
  questions: [
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_name_of_the',
      label: 'What is the name of the Retro Request Category?  (e.g., Flight Retro, Ancillary Retro)',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'what_is_the_bit_type_for',
      label: 'What is the BIT Type for this Retro Request Category?  (Select: Fly / Ancillary / Stay)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'which_sponsor_is_associated_with_this',
      label: 'Which Sponsor is associated with this Retro Request Category?  (e.g., Terminus Airlines / Manderley Hotels)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_a_description_for_this',
      label: 'Please provide a description for this Retro Request Category.  (e.g., \'Retro Requests to capture automated Terminus Airlines Flight Retro\')',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_a_logo_for_this',
      label: 'Please provide a logo for this Retro Request Category.  [File must be 90x90px minimum, not exceed 2 MB. Accepted formats: PNG, JPG, GIF]',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_maximum_number_of',
      label: 'What is the maximum number of days after the activity date by which a member must submit a Retro Request? (e.g., members have up to 90 days from the date of the flight to raise a claim)',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'should_a_bit_transaction_be_automatically',
      label: 'Should a BIT (transaction) be automatically created upon approval of the Retro Request?  (Yes / No)',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'if_answer_of_q1_is_yes',
      label: 'If answer of Q1 is Yes, which accrual offer(s) should be triggered when a Retro Request is approved?  (Provide offer name(s))',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'if_answer_of_q1_is_no',
      label: 'If answer of Q1 is No, which accrual file will include approved retro transactions for accrual? (e.g., Terminus Airlines Accrual Batch)',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'what_is_the_approval_workflow_for',
      label: 'What is the approval workflow for Retro Requests?  (e.g., Manual Review and approval by Customer Service Agents / Processing Retro file from source/partner for automated approval)',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'for_automated_approval_using_file_how',
      label: 'For automated approval using file, how frequently will the Retro file be sent from the source/partner system to GRAVTY? (e.g., daily, weekly)',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'questions',
      label: 'Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'please_provide_the_list_of_portals',
      label: 'Please provide the list of portals / apps through which members/ agents can submit a Retro Request. (e.g., Member Portal, Mobile App, Customer Care Agent Portal)',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'will_retro_requests_be_submitted_from',
      label: 'Will Retro Requests be submitted from any external system (e.g., Airline GDS, Partner system)?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_name',
      label: 'Attribute Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'examples',
      label: 'Examples:',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'h_bit_date',
      label: 'h_bit_date',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'h_pnr_number',
      label: 'h_pnr_number',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'h_origin_airport',
      label: 'h_origin_airport',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'h_destination_airport',
      label: 'h_destination_airport',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'attribute_name',
      label: 'Attribute Name',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'examples',
      label: 'Examples:',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'h_fare_class',
      label: 'h_fare_class',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'h_marketing_carrier',
      label: 'h_marketing_carrier',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
