import type { Section } from '../types';

export const roleMgmtSection: Section = {
  id: 'role-mgmt',
  name: 'Role Management',
  description: 'User roles, permissions, and access control configuration',
  phase: 'design',
  questions: [
    {
      key: 'responsibilities',
      label: 'Responsibilities',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'oversee_overall_program_management_implement_polic',
      label: '- Oversee overall program management. - Implement policies and procedures. - Ensure program goals and objectives are met.',
      inputType: 'select',
      required: false,
      pii: false,
    },
    {
      key: 'analyze_program_data_and_trends_generate',
      label: '- Analyze program data and trends. - Generate reports for performance evaluation. - Provide insights for program improvements.',
      inputType: 'select',
      required: false,
      pii: false,
    },
    {
      key: 'assist_customers_with_inquiries_and_issues',
      label: '- Assist customers with inquiries and issues. - Provide information on products or services. - Ensure a positive customer experience.',
      inputType: 'select',
      required: false,
      pii: false,
    },
    {
      key: 'description',
      label: 'Description',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'select_the_relevant_access_level_program',
      label: 'Select the relevant access level (Program, Sponsor, Sponsor Location) in the case of a custom role. For seeded roles, the access level permission is not updatable.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_configured_offers',
      label: 'Grant permission to view configured offers and offer details such as Offer Name, Offer Description, Validity Timeframe, etc.',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'grant_permission_to_create_and_edit',
      label: 'Grant permission to create and edit offers configured in GRAVTY.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_launch_offers',
      label: 'Grant permission to launch offers.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_update_offer_status',
      label: 'Grant permission to update offer status (Delete, Test, Launched, Update, etc.,)',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_delete_the_offer',
      label: 'Grant permission to delete the offer.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_update_the_offer',
      label: 'Grant permission to update the offer status to "Test" for Offer testing.',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_launch_the_offer',
      label: 'Grant permission to launch the offer.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_update_and_make',
      label: 'Grant permission to update and make changes to the already launched offer.',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_suspend_the_offer',
      label: 'Grant permission to suspend the offer. A suspended offer can be relaunched.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_terminate_the_offer',
      label: 'Grant permission to terminate the offer. A terminated offer cannot be relaunched.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_billing',
      label: 'Grant permission to view the billing details of the sponsor.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_update_the_sponsors',
      label: 'Grant permission to update the sponsor\'s billing details.',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_sponsors',
      label: 'Grant permission to view the sponsor\'s details such as sponsor description, logo, custom attributes, etc.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_update_the_sponsors',
      label: 'Grant permission to update the sponsor\'s details such as sponsor description, logo, custom attributes, etc.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_configurations_such',
      label: 'Grant permission to view configurations such as Policy Setup, Program Details, Data Config, Member Panels, Offer KPI setup, etc., at the program level.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_update_configurations_such',
      label: 'Grant permission to update configurations such as Policy Setup, Program Details, Data Config, Member Panels, Offer KPI setup, etc., at the program level.',
      inputType: 'date',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_bits',
      label: 'Grant permission to view the BITs in the BITs section and under the BITs tab in Member360.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_create_a_bit',
      label: 'Grant permission to create a BIT (transaction, such as earn transaction, points redemption, etc.) for a member using the "Create BIT" option in GRAVTY Member 360.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_out',
      label: 'Grant permission to view the out-of-the-box dashboard.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_g',
      label: 'Grant permission to view the G-Sense dashboard.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_member',
      label: 'Grant permission to view the member list and member details.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_external_privilege',
      label: 'Grant permission to view external privilege IDs',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_edit_member_details',
      label: 'Grant permission to edit member details such as mobile number, date of birth, gender, etc.',
      inputType: 'date',
      required: false,
      pii: true,
    },
    {
      key: 'grant_permission_to_view_the_member',
      label: 'Grant permission to view the member details.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_batches',
      label: 'Grant permission to view the Batches section and the details of processed transactions through Batches for different sponsors.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_set_up_new',
      label: 'Grant permission to set up new batches, edit existing batches, and run a batch by uploading a file.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_download_bits_transaction',
      label: 'Grant permission to Download BITs (Transaction) of a member.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_provide_or_revoke',
      label: 'Grant permission to provide or revoke access for users.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_remove_family_members',
      label: 'Grant permission to remove family members.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_sponsor',
      label: 'Grant permission to view the sponsor and location PINs.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_edit_the_sponsor',
      label: 'Grant permission to edit the sponsor and location PINs.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_rank_offers_that',
      label: 'Grant permission to rank offers that are marked as Featured offers.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_hot_notes',
      label: 'Grant permission to view hot notes added for a member.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_edit_hot_notes',
      label: 'Grant permission to edit hot notes added for a member.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_cobranded_cards',
      label: 'Grant permission to view Cobranded Cards added for a member.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_edit_cobranded_cards',
      label: 'Grant permission to edit Cobranded Cards of a member.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_member_segments',
      label: 'Grant permission to view member segments under segmentation setup. With this permission enabled, users will only be able to view member segments while configuring offers; they will not be able to select a specific segment, and the \'All Members\' segment will be selected by default.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_create_new_member',
      label: 'Grant permission to create new member segments using segmentation setup and while configuring offers.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_download_member_segments',
      label: 'Grant permission to download member segments. As part of the segment download, you will be able to select the member attributes you want to be included in your file, alongside the Member ID.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_various_membership',
      label: 'Grant permission to use various membership services, such as Points Adjustment, Privilege Issuance, etc.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_points',
      label: 'Grant permission to use the Points Adjustment membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_bit',
      label: 'Grant permission to use the BIT Creation membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_bit',
      label: 'Grant permission to use the BIT Cancellation membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_profile',
      label: 'Grant permission to use the Profile Update membership service.',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_tier',
      label: 'Grant permission to use the Tier Change membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_merge',
      label: 'Grant permission to use the Merge Member membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_membership',
      label: 'Grant permission to use the Membership Stage Change membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_membership',
      label: 'Grant permission to use the Membership Deletion membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_membership',
      label: 'Grant permission to use the Membership Cancellation membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_award',
      label: 'Grant permission to use the Award Redemption membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_privilege',
      label: 'Grant permission to use the Privilege Issuance membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_privilege',
      label: 'Grant permission to use the Privilege Extension membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_privilege',
      label: 'Grant permission to use the Privilege Consumption membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_reinstate',
      label: 'Grant permission to use the Reinstate Used Privilege membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_privilege',
      label: 'Grant permission to use the Privilege Cancellation membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_privilege',
      label: 'Grant permission to use the Privilege Choice and Swap membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_privilege',
      label: 'Grant permission to use the Privilege Transfer membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_points',
      label: 'Grant permission to use the Points Transfer membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_offer',
      label: 'Grant permission to use the Offer Acceptance membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_use_the_points',
      label: 'Grant permission to use the Points Expiry Extension membership service.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_verify_the_attributes',
      label: 'Grant permission to verify the attributes',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_rank_the_sponsors',
      label: 'Grant permission to rank the sponsors.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_member',
      label: 'Grant permission to view the member document from Member360.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_edit_and_download',
      label: 'Grant permission to edit and download the member document from Member360.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_access_the_gravty',
      label: 'Grant permission to access the GRAVTY UI.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_trigger_gravty_apis',
      label: 'Grant permission to trigger GRAVTY APIs.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_the_member',
      label: 'Grant permission to view the member Personally Identifiable Information.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_view_retro_request',
      label: 'Grant permission to view Retro Request.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_edit_and_create',
      label: 'Grant permission to edit and create Retro Request.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_approve_and_reject',
      label: 'Grant permission to approve and reject Retro Request.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'this_permission_enforces_pii_masking_and',
      label: 'This permission enforces PII Masking, and the member\'s PII information such as First Name, Last Name, etc., is masked.',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'this_permission_allows_pii_information_unmasking',
      label: 'This permission allows PII Information Unmasking, and the member\'s PII information would be visible after entering the Two Factor Authentication (2FA) code.',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grant_permission_to_configure_the_alerts',
      label: 'Grant permission to configure the alerts for the AiSense.',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
