import type { Section } from '../types';

export const sponsorDataModelSection: Section = {
  id: 'sponsor-data-model',
  name: 'Sponsor Data Model',
  description: 'Sponsor entity attributes and data model configuration',
  phase: 'design',
  questions: [
    {
      key: 'additional_emails',
      label: 'additional_emails',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'address',
      label: 'address',
      inputType: 'grid',
      required: false,
      pii: true,
    },
    {
      key: 'annual_revenue',
      label: 'annual_revenue',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'business_division',
      label: 'business_division',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'business_unit',
      label: 'business_unit',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'phone_number',
      label: 'phone_number',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'contact_person_name',
      label: 'contact_person_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'country',
      label: 'country',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'email',
      label: 'email',
      inputType: 'grid',
      required: false,
      pii: true,
    },
    {
      key: 'email_verified',
      label: 'email_verified',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'employee_count',
      label: 'employee_count',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'end_date',
      label: 'end_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'contact_person_first_name',
      label: 'contact_person_first_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'entity_name',
      label: 'entity_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'header',
      label: 'header',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'industry',
      label: 'industry',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'contact_person_last_name',
      label: 'contact_person_last_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'payment_status',
      label: 'payment_status',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'pin_code',
      label: 'pin_code',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'region',
      label: 'region',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'trade_license_number',
      label: 'trade_license_number',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'specially_abled',
      label: 'specially_abled',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'description',
      label: 'description',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'acquisition_url',
      label: 'acquisition_url',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'short_name',
      label: 'short_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'status',
      label: 'status',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'start_date',
      label: 'start_date',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'contact_person_title',
      label: 'contact_person_title',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'brand_name',
      label: 'brand_name',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'woman_entrepreneur',
      label: 'woman_entrepreneur',
      inputType: 'grid',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor_pin_threshold',
      label: 'sponsor_pin_threshold',
      inputType: 'grid',
      required: false,
      pii: false,
    },
  ],
};
