import type { Section } from '../types';

export const sponsorDetailsSection: Section = {
  id: 'sponsor-details',
  name: 'Sponsor Details Template',
  description: 'Detailed sponsor information template for onboarding each sponsor',
  phase: 'design',
  questions: [
    {
      key: 'sponsor_name',
      label: 'Sponsor Name',
      inputType: 'text',
      required: true,
      pii: true,
      helpText: 'This will be the Sponsor\'s name used to identify the Sponsor in GRAVTY.',
    },
    {
      key: 'visible_name',
      label: 'Visible Name',
      inputType: 'text',
      required: false,
      pii: true,
      helpText: 'The visible name attribute can be used to display the Sponsor\'s brand name on member-facing channels (Mobile, Web, etc.). For example, if you have a Sponsor in multiple countries, in that case, the Sponsor\'s name can be Burger King Poland and Burger King Austria, but the visible name of the Sponsor ',
    },
    {
      key: 'group',
      label: 'Group',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Name of the Holding/Parent Company of the Sponsor.',
    },
    {
      key: 'registered_id',
      label: 'Registered ID',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Sponsor\'s legal ID or identification.',
    },
    {
      key: 'sponsor_enrollment_form_url',
      label: 'Sponsor Enrollment Form URL',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Sponsor specific URL used to enroll members into the program. Additionally, it can be utilized to track the number of members getting enrolled through the Sponsor.',
    },
    {
      key: 'sponsor_short_name',
      label: 'Sponsor Short Name',
      inputType: 'text',
      required: true,
      pii: true,
      helpText: 'Short Name of the Sponsor. The Sponsor\'s short name should be unique (No two sponsors in the tenant can have the same Short name) in the program across all the Sponsors.\n',
    },
    {
      key: 'sponsor_industry',
      label: 'Sponsor Industry',
      inputType: 'text',
      required: true,
      pii: false,
      helpText: 'Industry of the Sponsor.',
    },
    {
      key: 'sponsor_description',
      label: 'Sponsor Description',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Description of the Sponsor.',
    },
    {
      key: 'sponsor_logo',
      label: 'Sponsor Logo',
      inputType: 'file',
      required: true,
      pii: false,
      helpText: 'The Logo of the Sponsor. \n[Files must be 200x200px minimum, and not exceed 2MB, accepted formats PNG, JPG and GIF.]\n',
    },
    {
      key: 'sponsor_banner',
      label: 'Sponsor Banner',
      inputType: 'file',
      required: false,
      pii: false,
      helpText: 'Header/Banner image of the Sponsor.\n[Files must be 200x200px minimum and not exceed 2MB, accepted formats PNG, JPG, and GIF.]\n',
    },
    {
      key: 'sponsor_facets',
      label: 'Sponsor Facets',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Sponsor facets can be used for optimizing the Sponsor\'s search and recommendations.',
    },
    {
      key: 'sponsorship_validity_start_date',
      label: 'Sponsorship Validity: Start Date',
      inputType: 'date',
      required: true,
      pii: false,
      helpText: 'The start date of the Sponsor\'s validity is the date from which BITs (transactions) are sent to GRAVTY by this sponsor. If past-dated BITs (transactions) are sent from a sponsor, the start date should be determined by the oldest past-dated BIT that would be sent to GRAVTY.',
    },
    {
      key: 'sponsorship_validity_end_date',
      label: 'Sponsorship Validity: End Date',
      inputType: 'date',
      required: false,
      pii: false,
      helpText: 'End date of the Sponsor\'s validity.',
    },
    {
      key: 'annual_revenue',
      label: 'Annual Revenue',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: 'Sponsor\'s Annual Revenue',
    },
    {
      key: 'employee_count',
      label: 'Employee Count',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: 'Number of Employees in Sponsor\'s Company/Organization.',
    },
    {
      key: 'contact_person_name',
      label: 'Contact Person: Name',
      inputType: 'text',
      required: false,
      pii: true,
      helpText: 'Name of the primary sponsor representative. This field is Mandatory only when sponsor verification is needed.',
    },
    {
      key: 'contact_person_email',
      label: 'Contact Person: Email',
      inputType: 'text',
      required: false,
      pii: true,
      helpText: 'Email of the primary sponsor representative. This field is Mandatory only when sponsor verification is needed.',
    },
    {
      key: 'contact_person_number',
      label: 'Contact Person: Number',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Phone number of the primary sponsor representative. This field is Mandatory only when sponsor verification is needed.',
    },
    {
      key: 'business_contact_details_business_website',
      label: 'Business Contact Details : Business Website',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Business Website of the Sponsor.',
    },
    {
      key: 'business_contact_details_business_unit',
      label: 'Business Contact Details : Business Unit',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Business Unit of the Sponsor.',
    },
    {
      key: 'business_contact_details_business_division',
      label: 'Business Contact Details : Business Division',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'Business Division of the Sponsor.',
    },
    {
      key: 'business_contact_details_latitude_of_the',
      label: 'Business Contact Details: Latitude of the Business Address',
      inputType: 'number',
      required: true,
      pii: true,
      helpText: 'Latitude of the Sponsor\'s Headquarters Address.',
    },
    {
      key: 'business_contact_details_longitude_of_the',
      label: 'Business Contact Details: Longitude of the Business Address',
      inputType: 'number',
      required: true,
      pii: true,
      helpText: 'Longitude of the Sponsor\'s Headquarters Address.',
    },
    {
      key: 'sponsor_opening_hours_opens_at_hh',
      label: 'Sponsor Opening Hours: Opens at (HH:MM)',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'The operation timings of the sponsor. You can set different open times for different days of the week.',
    },
    {
      key: 'sponsor_opening_hours_closes_at_hh',
      label: 'Sponsor Opening Hours: Closes at (HH:MM)',
      inputType: 'text',
      required: false,
      pii: false,
      helpText: 'The operation timings of the sponsor. You can set different closing times for different days of the week.',
    },
    {
      key: 'base_rate_currency',
      label: 'Base Rate: Currency ',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: '\nThe "Base Rate: Currency" attribute refers to the specific currency against which a base rate is configured.',
    },
    {
      key: 'base_rate_loyalty_account',
      label: 'Base Rate: Loyalty Account ',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: '\nThe "Base Rate: Loyalty Account" attribute refers to the specific loyalty account against which a base rate is configured.',
    },
    {
      key: 'base_rate_value',
      label: 'Base Rate: Value ',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: '\nThe "Base Rate: Value" attribute refers to the number of points to be rewarded in the respective loyalty account on 1 unit of currency spent.',
    },
    {
      key: 'base_rate_validity_start_date',
      label: 'Base Rate Validity: Start Date',
      inputType: 'date',
      required: false,
      pii: false,
      helpText: '"Base Rate Validity: Start Date" refers to the commencement date from which the specified base rate becomes applicable.',
    },
    {
      key: 'base_rate_validity_end_date',
      label: 'Base Rate Validity: End Date',
      inputType: 'date',
      required: false,
      pii: false,
      helpText: '"Base Rate Validity: End Date" refers to the conclusion date, indicating until when the specified base rate remains valid. Once the end date is reached, the base rate will no longer be applicable.',
    },
    {
      key: 'redemption_threshold_loyalty_account',
      label: 'Redemption Threshold: Loyalty Account',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: 'The "Redemption Threshold: Loyalty Account" attribute refers to the specific loyalty account for which the Redemption Threshold is configured.',
    },
    {
      key: 'redemption_threshold_value',
      label: 'Redemption Threshold: Value',
      inputType: 'number',
      required: false,
      pii: false,
      helpText: 'The "Redemption Threshold: Value" attribute refers to the maximum number of points that all members can redeem from the respective loyalty account.',
    },
  ],
};
