import type { Section } from '../types';

export const sponsorMgmtSection: Section = {
  id: 'sponsor-mgmt',
  name: 'Sponsor Management',
  description: 'Participating brands, partners, and sponsor hierarchy configuration',
  phase: 'discovery',
  questions: [
    {
      key: 'what_will_be_the_name_of',
      label: 'What will be the name of the company hosting the Loyalty Program?',
      inputType: 'text',
      required: true,
      pii: true,
      placeholder: 'FAS Rewards LLC',
    },
    {
      key: 'multi_national_loyalty_program_sponsor_management',
      label: 'Multi-National Loyalty Program Sponsor Management Related Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'do_your_participating_brands_partners_operate',
      label: 'Do your Participating Brands/Partners operate across multiple countries?',
      inputType: 'number',
      required: true,
      pii: false,
    },
    {
      key: 'are_the_program_offerings_rewards_redemptions',
      label: 'Are the program offerings (rewards, redemptions, and recognition) common for partners/brands across geographies, or are these unique to each geography? For example, does Elite Plaza UK have different products compared to Elite Plaza US?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Not Applicable',
    },
    {
      key: 'are_the_loyalty_promotions_offers_for',
      label: 'Are the loyalty promotions/offers for a particular partner/brand country-specific or same across countries?',
      inputType: 'number',
      required: false,
      pii: false,
      placeholder: 'Not Applicable',
    },
    {
      key: 'do_you_want_to_restrict_the',
      label: 'Do you want to restrict the visibility of the program data (member engagement, promotions, and transactions) by geo for your participating brands/partners? For example, should the user of Elite Plaza UK not be able to view the program data for Elite Plaza US?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Not Applicable',
      industryRelevance: ["Ecosystem"],
    },
    {
      key: 'sponsor_modelling_related_questions',
      label: 'Sponsor Modelling Related Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'do_you_have_any_group_brands',
      label: 'Do you have any Group Brands participating in your Loyalty Program?',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Yes',
    },
    {
      key: 'do_you_have_any_third_party',
      label: 'Do you have any Third-party Companies participating in your Loyalty Program?',
      inputType: 'text',
      required: true,
      pii: false,
      industryRelevance: ["Ecosystem"],
    },
    {
      key: 'do_you_have_shopping_malls_participating',
      label: 'Do you have Shopping Malls participating in the Loyalty Program? If yes, do other participating brands have locations that exist in the participating malls? For example, Elite Plaza (Retail), Fashion Show Mall, and Great Mall participate in your loyalty program. Elite Plaza has two locations - one i',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Yes',
      industryRelevance: ["Real Estate (Malls)"],
    },
    {
      key: 'at_what_level_do_you_intend',
      label: 'At what level do you intend to analyse Program Data? 1.  Brand (Partner) Level globally 2. Brand (Partner) Level by Geo 3. Brand (Partner) Location Level',
      inputType: 'select',
      required: true,
      pii: false,
      placeholder: 'Partner Level and Partner Location Level',
    },
    {
      key: 'please_provide_your_organizational_hierarchy_invol',
      label: 'Please provide your organizational hierarchy involving the participating brands. [For better understanding, refer here]',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor_reward_rate',
      label: 'Sponsor Reward Rate',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'does_the_sponsor_accrual_earn_rate',
      label: 'Does the Sponsor Accrual (Earn) Rate vary per Currency?',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'does_the_sponsor_accrual_earn_rate',
      label: 'Does the Sponsor Accrual (Earn) Rate vary per Sponsor?',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Yes',
    },
    {
      key: 'please_provide_the_sponsor_details_using',
      label: 'Please provide the Sponsor details using the sponsor details template.',
      inputType: 'text',
      required: true,
      pii: false,
    },
    {
      key: 'will_each_brand_partner_have_access',
      label: 'Will each Brand/Partner have access to GRAVTY®? (Yes/No). If Yes, please provide details of the Sponsor (Partner) level users of the program.',
      inputType: 'boolean',
      required: false,
      pii: false,
      industryRelevance: ["Ecosystem"],
    },
    {
      key: 'please_provide_the_sponsor_locations_details',
      label: 'Please provide the Sponsor Locations details using the sponsor location management template.',
      inputType: 'text',
      required: true,
      pii: false,
    },
  ],
};
