import type { Section } from '../types';

export const subscriptionSection: Section = {
  id: 'subscription',
  name: 'Subscription Module',
  description: 'Paid membership and subscription tier configuration',
  phase: 'launch',
  visibleIf: {
    questionKey: 'has_paid_membership',
    operator: 'eq',
    value: 'true',
  },
  questions: [
    {
      key: 'general_questions',
      label: 'General Questions',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'subscription_package',
      label: 'Subscription Package',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'description',
      label: 'Description',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'upgrade_type',
      label: 'Upgrade Type',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'joining_fees_currency',
      label: 'Joining Fees (Currency) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'joining_fees_points',
      label: 'Joining Fees (Points) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grace_period_payments',
      label: 'Grace Period (Payments) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'grace_period_renewals',
      label: 'Grace Period (Renewals) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'subscription_package_image',
      label: 'Subscription Package Image',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'does_your_paid_program_have_multiple',
      label: 'Does your paid program have multiple plans in the package?',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'subscription_plan',
      label: 'Subscription Plan ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'plan_description',
      label: 'Plan Description',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'expires_in',
      label: 'Expires In ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'expires_on',
      label: 'Expires On ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'plan_image',
      label: 'Plan Image',
      inputType: 'file',
      required: false,
      pii: false,
    },
    {
      key: 'billing_cycle',
      label: 'Billing Cycle ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'activation_fees_currency',
      label: 'Activation Fees (Currency) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'renewal_fees_currency',
      label: 'Renewal Fees (Currency) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'activation_fees_points',
      label: 'Activation Fees (Points) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'renewal_fees_points',
      label: 'Renewal Fees (Points) ',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'are_there_any_addons_that_can',
      label: 'Are there any addons that can be purchased in this plan',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'sponsor',
      label: 'Sponsor',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'privilege',
      label: 'Privilege',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'usage_policy',
      label: 'Usage Policy',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'quantity',
      label: 'Quantity',
      inputType: 'number',
      required: false,
      pii: false,
    },
    {
      key: 'billing_cycle',
      label: 'Billing Cycle',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'add_on_price_currency',
      label: 'Add on Price (Currency)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'add_on_price_points',
      label: 'Add on Price (Points)',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'associated_privileges',
      label: 'Associated Privileges',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
