import type { Section } from '../types';

export const tierMgmtSection: Section = {
  id: 'tier-mgmt',
  name: 'Tier Management',
  description: 'Tier structure, qualification criteria, upgrade/downgrade policies, and tier entitlements',
  phase: 'discovery',
  visibleIf: {
    questionKey: 'program_has_tiers',
    operator: 'eq',
    value: 'true',
  },
  questions: [
    {
      key: 'tier_class_tiers_setup',
      label: 'Tier Class & Tiers Setup',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'does_your_program_have_a_tier',
      label: 'Does your Program have a Tier structure? If Yes, kindly provide Tier related details.',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: 'Yes and Starbucks Rewards program has 3 Tiers.',
    },
    {
      key: 'please_share_the_logo_associated_with',
      label: 'Please share the logo associated with the Tier Class.',
      inputType: 'file',
      required: true,
      pii: false,
    },
    {
      key: 'what_are_the_names_of_the',
      label: 'What are the names of the Tiers within the Tier Class? For example, Welcome Tier, Green Tier, Gold Tier, Silver Tier, etc.',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Tiers:\n1. Welcome Tier\n2. Green Tier\n3. Gold Tier',
    },
    {
      key: 'do_you_have_a_predetermined_order',
      label: 'Do you have a predetermined order or ranking for the Tiers within the Tier Class? By default, GRAVTY assigns ranks in the sequence of addition. Would you like to customize these ranks?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'The Welcome Tier is the lowest, and the Gold Tier is the highest.',
    },
    {
      key: 'do_you_want_the_tier_class',
      label: 'Do you want the Tier Class information and underlying Tiers to be visible to members? (Yes/No)  - If yes, would you prefer all Tiers under a Class to be member-visible by default (or)  - Do you prefer individual tier visibility control?',
      inputType: 'boolean',
      required: false,
      pii: false,
      placeholder: 'All Tiers to be member visible.',
    },
    {
      key: 'please_indicate_the_tier_type_earned',
      label: 'Please indicate the Tier type (Earned, Paid, or Complimentary).  [Select at least one; you can choose multiple options.]',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Welcome Tier - Complementary\nGreen Tier - Earned\nGold Tier - Paid',
    },
    {
      key: 'if_paid_type_is_selected_could',
      label: 'If Paid Type is selected, could you define the fee for purchasing the Tier in Program Currency? Would you like to enable "Allow Payment with Points"? If yes, please define the fee in terms of redemption currency.',
      inputType: 'currency',
      required: false,
      pii: false,
      placeholder: 'Gold Membership Fee: $500. Purchasing the paid tier using points is prohibited.',
    },
    {
      key: 'what_should_be_the_attain_threshold',
      label: 'What should be the Attain Threshold and Retain Threshold for Earned Tiers?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Welcome Level members have the option to upgrade to the Green tier by spending $100 before the Tier End date.',
    },
    {
      key: 'should_any_tiers_in_the_tier',
      label: 'Should any Tiers in the Tier Class have lifetime recognition, meaning members attain and retain the tier for a lifetime? (Yes/No)  If yes, please provide an example or specific details for better understanding.',
      inputType: 'boolean',
      required: false,
      pii: false,
    },
    {
      key: 'tier_model_which_of_the_below',
      label: 'Tier Model: Which of the below-mentioned models would you prefer to reassess the members\' Tiers: 1. Fixed Period Model (i.e., reassess a member\'s tier status at set intervals, such as annually or semi-annually). 2. Anniversary Model (i.e., reassess a member\'s tier status based on the anniversary of ',
      inputType: 'date',
      required: false,
      pii: false,
      placeholder: '12 Months (Anniversary)',
    },
    {
      key: 'at_what_frequency_should_members_be',
      label: 'At what frequency should members be given the chance to qualify for a higher Tier?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Anytime based on spend',
    },
    {
      key: 'tier_validity_what_is_the_duration',
      label: 'Tier Validity: What is the duration for the validity of a tier before it undergoes reassessment?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: '12 Months (Anniversary)',
    },
    {
      key: 'qualification_period_define_the_qualification_peri',
      label: 'Qualification Period: Define the Qualification Period, establishing the timeframe for assessing member tier upgrades and retention.',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Starts on the Anniversary Date + 1 year.',
    },
    {
      key: 'how_would_you_like_to_manage',
      label: 'How would you like to manage Tier Upgrades? Examples: - Attain Green Tier by spending >= $1000 annually and Gold Tier by spending >= $5000 annually. - Achieve Green Tier with >= 10 transactions and Gold Tier with >= 25 transactions in a year. - The Welcome Tier is complimentary, while the Green Tier',
      inputType: 'select',
      required: false,
      pii: false,
      placeholder: 'Welcome - $0\nGreen - $100\nGold - $500',
    },
    {
      key: 'how_would_you_like_to_manage',
      label: 'How would you like to manage Tier Downgrades/Renewals? (Provide criteria, e.g., Downgrade if spend < x in the past year, Renew if spend is between x and y)',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: '0 - $100 -> Welcome Tier\n$100 - $300 -> Green Tier\n$300+ -> Gold Tier',
    },
    {
      key: 'tier_entitlements',
      label: 'Tier Entitlements',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'specify_the_entitlements_or_benefits_you',
      label: 'Specify the entitlements or benefits you intend to grant members based on their tier.',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Green Tier\n1. Free Birthday drink (Tall size handcrafted beverage)\n2. Free Size Upgrade on handcrafted beverage\n\nGold Tier\n1. Free Birthday drink (Tall size handcrafted beverage)\n2. Free Size Upgrade ',
    },
    {
      key: 'specify_how_many_times_the_member',
      label: 'Specify how many times the member can use each entitlement.',
      inputType: 'number',
      required: false,
      pii: false,
      placeholder: 'Once',
    },
    {
      key: 'how_long_is_each_entitlement_valid',
      label: 'How long is each entitlement valid for?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Same as the Tier Validity',
    },
    {
      key: 'what_occurs_to_these_entitlements_in',
      label: 'What occurs to these entitlements in the event of a Tier Upgrade or Tier Expiry?',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Upon Tier Upgrade or Tier Expiry, existing entitlements will be revoked, and new entitlements corresponding to the new Tier will be issued.',
    },
  ],
};
