import type { Section } from '../types';

export const userMgmtSection: Section = {
  id: 'user-mgmt',
  name: 'User Management',
  description: 'System user accounts and user detail configuration',
  phase: 'design',
  questions: [
    {
      key: 'password_policy',
      label: 'Password Policy',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'password_expiry_policy_specify_the_password',
      label: 'Password Expiry Policy: Specify the password expiration period for GRAVTY users (this doesn\'t apply to loyalty program members). The default setting for this value is 90 days and it should be within the range of 7 to 90 days.',
      inputType: 'text',
      required: true,
      pii: false,
      placeholder: '90 days',
    },
    {
      key: 'password_reuse_policy_specify_the_number',
      label: 'Password Reuse Policy: Specify the number of previous passwords that cannot be reused. The default setting for this value is 4, and it should be within the range of 4 to 10.',
      inputType: 'number',
      required: true,
      pii: false,
    },
    {
      key: 'single_sign_on',
      label: 'Single Sign-On',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'would_you_like_to_authorize_login',
      label: 'Would you like to authorize login through Single Sign-On (SSO)? GRAVTY supports SSO Integration with various Identity Providers (IdPs).',
      inputType: 'text',
      required: false,
      pii: false,
      placeholder: 'Yes',
    },
    {
      key: 'idp_details_required_to_enable_sso',
      label: 'IdP Details required to enable SSO Login',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'entityid',
      label: 'EntityId',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'x509certificate',
      label: 'x509certificate',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'single_sign_on_service_redirection_url',
      label: 'Single Sign-On service redirection URL',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'service_name_optional_this_name_will',
      label: 'Service Name (Optional: This name will be displayed on the UI as "LOGIN WITH <service_name>") - Example: ADFS, OKTA, Auth0, Pingf',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'please_provide_the_email_addresses_roles',
      label: 'Please provide the email addresses, roles, and any other relevant details for the users who will be using GRAVTY.',
      inputType: 'text',
      required: false,
      pii: true,
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'first_name_of_the_user',
      label: 'First name of the user.',
      inputType: 'text',
      required: false,
      pii: true,
    },
    {
      key: 'robin',
      label: 'Robin',
      inputType: 'text',
      required: false,
      pii: false,
    },
    {
      key: 'shaun',
      label: 'Shaun',
      inputType: 'text',
      required: false,
      pii: false,
    },
  ],
};
