import type { Section } from '../types';

export const verticalEntitiesSection: Section = {
  id: 'vertical-entities',
  name: 'Vertical Entities',
  description: 'Industry-specific vertical entity configuration for hospitality',
  phase: 'launch',
  visibleIf: {
    questionKey: 'program_industry',
    operator: 'eq',
    value: 'Hospitality',
  },
  questions: [
    {
      key: 'how_important_is_it_for_you',
      label: 'How important is it for you to have a system that can store and evaluate membership related details like membership ID, membership name, sponsor associated to the membership, etc. efficiently?',
      inputType: 'text',
      required: false,
      pii: true,
      industryRelevance: ["Hospitality"],
    },
    {
      key: 'how_would_you_envision_using_the',
      label: 'How would you envision using the data stored for member details and FFP members to enhance your business operations?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Hospitality"],
    },
    {
      key: 'are_there_any_additional_attributes_or',
      label: 'Are there any additional attributes or customizations needed while storing the Membership Plan and Member Cards?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Hospitality"],
    },
    {
      key: 'are_the_membership_details_stored_to',
      label: 'Are the membership details stored to trigger welcome email to members?',
      inputType: 'text',
      required: false,
      pii: true,
      industryRelevance: ["Hospitality"],
      validation: {"pattern":"^[^@]+@[^@]+\\.[^@]+$","patternMessage":"Enter a valid email address"},
    },
    {
      key: 'is_there_a_need_to_manage',
      label: 'Is there a need to manage card details that are used for printing physical cards?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Hospitality"],
    },
    {
      key: 'are_member_food_preferences_recorded',
      label: 'Are member food preferences recorded? ',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Hospitality"],
    },
    {
      key: 'can_you_share_insights_into_how',
      label: 'Can you share insights into how you currently handle member data and bookings in the process?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Hospitality"],
    },
    {
      key: 'should_the_details_be_deleted_or',
      label: 'Should the details be deleted or updated frequently? If yes, what is the frequency with which it is updated?',
      inputType: 'date',
      required: false,
      pii: false,
      industryRelevance: ["Hospitality"],
    },
    {
      key: 'do_you_have_any_co_brand',
      label: 'Do you have any co-brand cards in the program specific to members?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Airlines"],
    },
    {
      key: 'if_yes_then_what_are_the',
      label: 'If yes, then what are the attributes that are stored under every co-brand card?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Airlines"],
    },
    {
      key: 'is_it_necessary_to_store_specific',
      label: 'Is it necessary to store specific details regarding member consent?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Airlines"],
    },
    {
      key: 'are_physical_or_virtual_card_details',
      label: 'Are physical or virtual card details stored for each member in the system?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Retail"],
    },
    {
      key: 'is_there_any_limit_to_holding',
      label: 'Is there any limit to holding one type of card for each member?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Retail"],
    },
    {
      key: 'are_there_any_voucher_codes_specific',
      label: 'Are there any voucher codes specific to members that must be stored? ',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Retail"],
    },
    {
      key: 'should_the_details_be_deleted_frequently',
      label: 'Should the details be deleted frequently? If yes, what is the frequency of deletion?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Retail"],
    },
    {
      key: 'are_the_specifics_of_member_level',
      label: 'Are the specifics of member-level website abandoned journeys stored within the system?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Ecosystem"],
    },
    {
      key: 'are_there_any_events_and_bookings',
      label: 'Are there any events and bookings made by members stored to track any member-specific information within the system?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Ecosystem"],
    },
    {
      key: 'should_the_vehicle_details_of_member',
      label: 'Should the vehicle details of member be recorded to provide VIP privileges like special parking, permanent slots, etc.?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Ecosystem"],
    },
    {
      key: 'is_there_any_requirement_to_store',
      label: 'Is there any requirement to store voucher codes that are assigned to every member and track the usage?',
      inputType: 'text',
      required: false,
      pii: false,
      industryRelevance: ["Ecosystem"],
    },
    {
      key: 'are_details_of_external_accounts_with',
      label: 'Are details of external accounts with different partners held by members stored? ',
      inputType: 'number',
      required: false,
      pii: false,
      industryRelevance: ["Ecosystem"],
    },
  ],
};
