import type { DataModelAttribute } from '../types';

export const bitAttributes: DataModelAttribute[] = [
  {
    businessName: 'Cancel BIT ID',
    attributeName: 'cancel_bit_id',
    description: 'Refers to the ID of BIT which is to be cancelled',
    sampleValue: 'WRUIT3435K',
    dataType: 'TEXT',
  },
  {
    businessName: 'Activity Referred by Member',
    attributeName: 'h_activity_referred_by_member',
    description: 'Name of the Member who referred this activity to another member.',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Activity Referred by MemberID',
    attributeName: 'h_activity_referred_by_member_id',
    description: 'Member ID of the Member who referred this activity to another member.',
    sampleValue: 'FEEUI3455',
    dataType: 'TEXT',
  },
  {
    businessName: 'Base Accrual',
    attributeName: 'h_base_accrual',
    description: 'Points accrued for this BIT based on the offer setup',
    sampleValue: '324',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Bill Due Date',
    attributeName: 'h_bill_due_date',
    description: 'Refers to the Bill due date',
    sampleValue: '44079',
    dataType: 'DATE',
  },
  {
    businessName: 'Bill Paid Date',
    attributeName: 'h_bill_paid_date',
    description: 'Refers to the Bill paid date',
    sampleValue: '44081',
    dataType: 'DATE',
  },
  {
    businessName: 'BIT Amount',
    attributeName: 'h_bit_amount',
    description: 'Refers to total invoice amount paid by member at POS/Payment Gateway, excluding tax for retail customers',
    sampleValue: '200',
    dataType: 'NUMBER',
  },
  {
    businessName: 'BIT Category',
    attributeName: 'h_bit_category',
    description: 'Determines the transaction category, which determines the type of offer applied on the transaction',
    sampleValue: 'ACCRUAL, REDEMPTION',
    dataType: 'LOV',
    lovType: 'BIT_CATEGORY',
  },
  {
    businessName: 'BIT Currency',
    attributeName: 'h_bit_currency',
    description: 'Currency in which is the transaction has been done',
    sampleValue: 'AED,USD',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'BIT Date',
    attributeName: 'h_bit_date',
    description: 'Timestamp when the transaction occurred',
    sampleValue: '2019-09-17T11:59:59+05:30',
    dataType: 'DATETIME',
  },
  {
    businessName: 'BIT ID',
    attributeName: 'h_bit_id',
    description: 'Unique transaction ID to track an activity',
    sampleValue: 'GTYHSDN12344',
    dataType: 'TEXT',
  },
  {
    businessName: 'BIT Mode',
    attributeName: 'h_bit_mode',
    description: 'Used for tracking retros and different types of manual adjustment',
    sampleValue: 'Retro',
    dataType: 'LOOKUP',
    lookupType: 'BIT_MODE',
  },
  {
    businessName: 'BIT Received Date',
    attributeName: 'h_bit_received_date',
    description: 'Timestamp of the BIT when it was received',
    sampleValue: '2019-09-17T11:59:59+05:30',
    dataType: 'DATETIME',
  },
  {
    businessName: 'BIT Source',
    attributeName: 'h_bit_source',
    description: 'Refers to the source of the transaction which is sent to GRAVTY as a part of the transaction, source integration system should use its own h_bit_source.',
    sampleValue: 'PMS, Mobile App, POS',
    dataType: 'LOOKUP',
    lookupType: 'BIT_SOURCE',
  },
  {
    businessName: 'BIT Source Generated ID',
    attributeName: 'h_bit_source_generated_id',
    description: 'ID generated at the Source for this BIT',
    sampleValue: '435656',
    dataType: 'TEXT',
  },
  {
    businessName: 'BIT Status',
    attributeName: 'h_bit_status',
    description: 'This reflects the status of the transaction as to whether it was successful or if there was some error that was encountered during transaction processing',
    sampleValue: 'Success, Failure',
    dataType: 'TEXT',
  },
  {
    businessName: 'BIT Type',
    attributeName: 'h_bit_type',
    description: 'Refers to the type of BIT/activity ',
    sampleValue: 'STAY, ENROL, Membership change',
    dataType: 'LOOKUP',
    lookupType: 'BIT_TYPE',
  },
  {
    businessName: 'Booking Agent',
    attributeName: 'h_booking_agent',
    description: 'Booking Agent who helped the member avail the BIT/activity',
    sampleValue: 'Agent',
    dataType: 'TEXT',
  },
  {
    businessName: 'Booking Class',
    attributeName: 'h_booking_class',
    description: 'Refers to the booking class incase for Airline Industry',
    sampleValue: 'Business Class',
    dataType: 'LOOKUP',
    lookupType: 'BOOKING_CLASS',
  },
  {
    businessName: 'Card Type',
    attributeName: 'h_card_type',
    description: 'Type of the Card used to pay for the transaction',
    sampleValue: 'Amex',
    dataType: 'LOOKUP',
    lookupType: 'CARD_TYPE',
  },
  {
    businessName: 'Checkin Facebook Page',
    attributeName: 'h_checkin_facebook_page',
    description: 'Facebook Page Id on which member has tagged check-In status, usually comes in check-in BIT',
    sampleValue: 'https://facebook.com/jumeirah',
    dataType: 'LOV',
    lovType: 'FACEBOOK_PAGE_LIST',
  },
  {
    businessName: 'Comment',
    attributeName: 'h_comment',
    description: 'Refers to the comment made by the CC Agent/Support person at the transaction gateway',
    sampleValue: 'Comments',
    dataType: 'TEXT',
  },
  {
    businessName: 'Corporate Reference',
    attributeName: 'h_corporate_reference',
    description: 'Member Id of the Corporate which has been modelled as a member with member type as Company.',
    sampleValue: 'IKIJ1234567',
    dataType: 'TEXT',
  },
  {
    businessName: 'Created By',
    attributeName: 'h_created_by',
    description: 'User who created the BIT. E.g., POS operator, CS Agent.',
    sampleValue: 'David',
    dataType: 'TEXT',
  },
  {
    businessName: 'Current Family Head',
    attributeName: 'h_current_family_head',
    description: 'Refers to the current Family Head',
    sampleValue: 'David',
    dataType: 'TEXT',
  },
  {
    businessName: 'Current Family Head Relationship',
    attributeName: 'h_current_family_head_relationship',
    description: 'Refers to the Member\'s Relationship with the Family Head',
    sampleValue: 'Brother',
    dataType: 'TEXT',
  },
  {
    businessName: 'Date of Booking',
    attributeName: 'h_date_of_booking',
    description: 'Date of booking of the Transaction',
    sampleValue: '43864',
    dataType: 'DATE',
  },
  {
    businessName: 'Deal Code',
    attributeName: 'h_deal_code',
    description: 'Deal code used in the transaction, which is configured in GRAVTY\'s products',
    sampleValue: 'DEAL45',
    dataType: 'TEXT',
  },
  {
    businessName: 'Destination Airport',
    attributeName: 'h_destination_airport',
    description: 'Name of the Airport to which the flight is destined',
    sampleValue: 'Dubai International Airport',
    dataType: 'LOV',
    lovType: 'AIRPORT_LIST',
  },
  {
    businessName: 'Destination Airport Code',
    attributeName: 'h_destination_airport_code',
    description: 'Code of the Airport to which the flight is destined',
    sampleValue: 'DXB',
    dataType: 'LOV',
    lovType: 'AIRPORT_CODE_LIST',
  },
  {
    businessName: 'Destination Area',
    attributeName: 'h_destination_area',
    description: 'Area of the Airport to which the flight is destined',
    sampleValue: 'Dubai',
    dataType: 'LOV',
    lovType: 'AREA_LIST',
  },
  {
    businessName: 'Destination City',
    attributeName: 'h_destination_city',
    description: 'Name of the Airport to which the flight is destined',
    sampleValue: 'Dubai',
    dataType: 'LOV',
    lovType: 'CITY_LIST',
  },
  {
    businessName: 'Destination Country',
    attributeName: 'h_destination_country',
    description: 'Country of the Airport to which the flight is destined',
    sampleValue: 'UAE',
    dataType: 'LOV',
    lovType: 'COUNTRY_LIST',
  },
  {
    businessName: 'Destination State',
    attributeName: 'h_destination_region',
    description: 'State/Region of the Airport to which the flight is destined',
    sampleValue: 'Dubai',
    dataType: 'LOV',
    lovType: 'REGION_LIST',
  },
  {
    businessName: 'Destination Zone',
    attributeName: 'h_destination_zone',
    description: 'Refers to the Airport zone at destination Airport',
    sampleValue: 'Zone1',
    dataType: 'LOOKUP',
    lookupType: 'AIRPORT_ZONE',
  },
  {
    businessName: 'Discount Code',
    attributeName: 'h_discount_code',
    description: 'Discount code used for the BIT/activity, which comes in transaction from external system',
    sampleValue: 'JM432',
    dataType: 'TEXT',
  },
  {
    businessName: 'End Date',
    attributeName: 'h_end_date',
    description: 'Any kind of end date can be passed into this attribute and offer logic rules can be written on this',
    sampleValue: '43895',
    dataType: 'DATE',
  },
  {
    businessName: 'Enrollment User',
    attributeName: 'h_enrollment_user',
    description: 'Refers to POS/PMS user who has enrolled the member',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Facebook Post',
    attributeName: 'h_facebook_post',
    description: 'Post uploaded by the member on Facebook, in which sponsor is tagged',
    sampleValue: '"Hello, Your service was great"',
    dataType: 'LOV',
    lovType: 'FACEBOOK_POST_LIST',
  },
  {
    businessName: 'Family Member',
    attributeName: 'h_family_member',
    description: 'Refers to the family member',
    sampleValue: 'Wick',
    dataType: 'TEXT',
  },
  {
    businessName: 'Fare Class',
    attributeName: 'h_fare_class',
    description: 'Fare Class for the bookings in this BIT',
    sampleValue: 'Economy',
    dataType: 'LOOKUP',
    lookupType: 'FARE_CLASS',
  },
  {
    businessName: 'Fare Type',
    attributeName: 'h_fare_type',
    description: 'Fare Type for the bookings in this BIT',
    sampleValue: 'Base Fare',
    dataType: 'LOOKUP',
    lookupType: 'FARE_TYPE',
  },
  {
    businessName: 'First Name',
    attributeName: 'h_first_name',
    description: 'First Name of the member who initialized this BIT',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Flight Code',
    attributeName: 'h_flight_code',
    description: 'Refers to the flight code',
    sampleValue: 'AY446',
    dataType: 'LOOKUP',
    lookupType: 'FLIGHT_CODE',
  },
  {
    businessName: 'Flight Date',
    attributeName: 'h_flight_date',
    description: 'The Date and time of the flight',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Flight Number',
    attributeName: 'h_flight_number',
    description: 'Refers to the Flight number',
    sampleValue: 'DBY454',
    dataType: 'LOOKUP',
    lookupType: 'FLIGHT_NUMBER',
  },
  {
    businessName: 'Flown Class',
    attributeName: 'h_flown_class',
    description: 'Class in which the Member flew',
    sampleValue: 'Economy',
    dataType: 'LOOKUP',
    lookupType: 'FLOWN_CLASS',
  },
  {
    businessName: 'IATA Code',
    attributeName: 'h_iata_code',
    description: 'IATA code of the Airport involved for this BIT',
    sampleValue: 'DXB',
    dataType: 'TEXT',
  },
  {
    businessName: 'Last Name',
    attributeName: 'h_last_name',
    description: 'Last Name of the member who initialized this BIT',
    sampleValue: 'wick',
    dataType: 'TEXT',
  },
  {
    businessName: 'Location',
    attributeName: 'h_location',
    description: 'Sponsor Location at which the BIT is created',
    sampleValue: 'Spa',
    dataType: 'LOV',
    lovType: 'SPONSOR_LOCATION_LIST',
  },
  {
    businessName: 'Location Name',
    attributeName: 'h_location_name',
    description: 'Sponsor Location name at which the BIT is created',
    sampleValue: 'Private Dining',
    dataType: 'LOV',
    lovType: 'SPONSOR_LOCATION_LIST',
  },
  {
    businessName: 'Loyalty Account',
    attributeName: 'h_loyalty_account',
    description: 'Refers to the loyalty account on which member can be rewarded or member can redeem.',
    sampleValue: 'Points',
    dataType: 'LOV',
    lovType: 'LOYALTY_ACCOUNT_LIST',
  },
  {
    businessName: 'Member ID',
    attributeName: 'h_member_id',
    description: 'Membership ID, unique for each Member.',
    sampleValue: '345456',
    dataType: 'TEXT',
  },
  {
    businessName: 'Member Login',
    attributeName: 'h_member_login',
    description: 'This attribute represent the login attributes such as email and mobile number through which the member gets logged in and performed the transaction.\nAny BIT created in GRAVTY should have one of the two, \'h_member_Id\' or \'h_member_login\'',
    sampleValue: 'Mobile Number, Facebook/Apple ID',
    dataType: 'TEXT',
  },
  {
    businessName: 'Member Name',
    attributeName: 'h_member_name',
    description: 'Name of the Member',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'New Member Tier',
    attributeName: 'h_member_tier_class',
    description: 'Refers to the New Tier Class in which GRAVTY/integrated system user wants the member to be in',
    sampleValue: 'Gold',
    dataType: 'LOOKUP',
    lookupType: 'TIER_CLASS',
  },
  {
    businessName: 'Membership Stage ID',
    attributeName: 'h_membership_stage_id',
    description: 'Refers to the new membership stage Id which the user wants the member to be in',
    sampleValue: '2',
    dataType: 'LOV',
    lovType: 'MEMBERSHIP_STAGE_LIST',
  },
  {
    businessName: 'Number of Nights',
    attributeName: 'h_no_of_nights',
    description: 'Used to track number of nights member stayed at sponsor\'s hotel',
    sampleValue: '5',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Number of Pax',
    attributeName: 'h_number_of_pax',
    description: 'Number of people/passengers the booking was carried out for using this BIT',
    sampleValue: '290',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Offer Name',
    attributeName: 'h_offer_name',
    description: 'Used for Award offers for redemption, this comes from the source',
    sampleValue: 'Complimentary Room Upgrade',
    dataType: 'LOV',
    lovType: 'OFFER_LIST',
  },
  {
    businessName: 'Operating Flight Code',
    attributeName: 'h_operating_flight_code',
    description: 'Operating Carrier\'s Flight Code',
    sampleValue: 'BA2490',
    dataType: 'LOOKUP',
    lookupType: 'FLIGHT_CODE',
  },
  {
    businessName: 'Operating Flight Number',
    attributeName: 'h_operating_flight_number',
    description: 'Operating Carrier\'s Flight Number',
    sampleValue: '2490',
    dataType: 'LOOKUP',
    lookupType: 'FLIGHT_NUMBER',
  },
  {
    businessName: 'Order ID',
    attributeName: 'h_order_id',
    description: 'Refers to the Order ID',
    sampleValue: '3330',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Origin Airport',
    attributeName: 'h_origin_airport',
    description: 'Name of the Airport from which the flight originated',
    sampleValue: 'Rajiv Gandhi International Airport',
    dataType: 'LOV',
    lovType: 'AIRPORT_LIST',
  },
  {
    businessName: 'Origin Airport Code',
    attributeName: 'h_origin_airport_code',
    description: 'Code of the Airport from which the flight originated',
    sampleValue: 'HYD',
    dataType: 'LOV',
    lovType: 'AIRPORT_CODE_LIST',
  },
  {
    businessName: 'OriginArea',
    attributeName: 'h_origin_area',
    description: 'Area of the Airport to which the flight originated',
    sampleValue: 'Shamshabad',
    dataType: 'LOV',
    lovType: 'AREA_LIST',
  },
  {
    businessName: 'Origin City',
    attributeName: 'h_origin_city',
    description: 'Name of the Airport from which the flight originated',
    sampleValue: 'Hyderabad',
    dataType: 'LOV',
    lovType: 'CITY_LIST',
  },
  {
    businessName: 'Origin Country',
    attributeName: 'h_origin_country',
    description: 'Refers to the Origin Airport Country',
    sampleValue: 'INDIA',
    dataType: 'LOV',
    lovType: 'COUNTRY_LIST',
  },
  {
    businessName: 'Origin State',
    attributeName: 'h_origin_region',
    description: 'Refers to the Origin Airport region',
    sampleValue: 'Shamshabad',
    dataType: 'LOV',
    lovType: 'REGION_LIST',
  },
  {
    businessName: 'Origin Zone',
    attributeName: 'h_origin_zone',
    description: 'Refers to the Origin Airport Zone',
    sampleValue: 'Zone1',
    dataType: 'LOOKUP',
    lookupType: 'AIRPORT_ZONE',
  },
  {
    businessName: 'Original BIT Amount',
    attributeName: 'h_original_bit_amount',
    description: 'Total invoice amount including tax',
    sampleValue: '5600',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Original BIT Amount Currency',
    attributeName: 'h_original_bit_amount_currency',
    description: 'Currency in which the original amount has been billed',
    sampleValue: 'AED',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Passenger Type',
    attributeName: 'h_passenger_type',
    description: 'Refers to the Type of passenger',
    sampleValue: 'Adult/Child',
    dataType: 'LOOKUP',
    lookupType: 'PASSENGER_TYPE',
  },
  {
    businessName: 'Pay In Amount',
    attributeName: 'h_pay_in_amount',
    description: 'Amount equivalent of points would be deducted from the member\'s account',
    sampleValue: '309',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Pay In Amount Currency',
    attributeName: 'h_pay_in_amount_currency',
    description: 'Currency of the amount mentioned in \'h_pay_in_amount\'',
    sampleValue: 'AED',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Pay in Points',
    attributeName: 'h_pay_in_points',
    description: 'Refers to the number of points to be deducted from the member\'s loyalty account when doing redemption transaction',
    sampleValue: '401',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Pay in Points Currency',
    attributeName: 'h_pay_in_points_currency',
    description: 'Refers to the account currency for h_pay_in_points with which the member wants to pay',
    sampleValue: 'AED, USD',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Paying Member ID',
    attributeName: 'h_paying_member_id',
    description: 'ID of the Member who paid for this BIT. Travel Agent, Executive Assistants, Parents paying for child, etc.',
    sampleValue: 'MEMBER345',
    dataType: 'TEXT',
  },
  {
    businessName: 'Payment Mode',
    attributeName: 'h_payment_mode',
    description: 'Medium through which the payment is done for the transaction',
    sampleValue: 'Online',
    dataType: 'LOOKUP',
    lookupType: 'PAYMENT_MODE',
  },
  {
    businessName: 'PNR Number',
    attributeName: 'h_pnr_number',
    description: 'PNR Number of the Flight',
    sampleValue: '56241',
    dataType: 'TEXT',
  },
  {
    businessName: 'POS CashierID',
    attributeName: 'h_pos_cashier_id',
    description: 'POS(Point of Sale) Cashier\'s ID',
    sampleValue: '345',
    dataType: 'TEXT',
  },
  {
    businessName: 'POS ID',
    attributeName: 'h_pos_id',
    description: 'Refers to the POS(Point of Sales) ID',
    sampleValue: 'POS123',
    dataType: 'TEXT',
  },
  {
    businessName: 'Previous Family Head',
    attributeName: 'h_prev_family_head',
    description: 'Refers to the previous family head',
    sampleValue: 'David',
    dataType: 'TEXT',
  },
  {
    businessName: 'Previous Family Head Relationship',
    attributeName: 'h_prev_family_head_relationship',
    description: 'Refers to the previous family head relation',
    sampleValue: 'father',
    dataType: 'TEXT',
  },
  {
    businessName: 'Privilege',
    attributeName: 'h_privilege',
    description: 'List of names of all the privileges assigned to member',
    sampleValue: 'Complimentary Room Upgrade',
    dataType: 'LOV',
    lovType: 'PRIVILEGE_LIST_NAME',
  },
  {
    businessName: 'Privilege ID',
    attributeName: 'h_privilege_id',
    description: 'List of IDs of privileges assigned to the member',
    sampleValue: 'HEYR232',
    dataType: 'LOV',
    lovType: 'PRIVILEGE_LIST',
  },
  {
    businessName: 'privileges',
    attributeName: 'h_privileges',
    description: 'List of privileges to be availed in the availment BIT',
    sampleValue: 'HEYR232, 78EHRJF',
    dataType: 'TEXT',
  },
  {
    businessName: 'Unique Privileges',
    attributeName: 'h_unique_privileges',
    description: 'Unique privilege Id assigned to the member',
    sampleValue: '7JEUER',
    dataType: '',
  },
  {
    businessName: 'Program ID',
    attributeName: 'h_program_id',
    description: 'Program ID, unique for each program created(tenant Id)',
    sampleValue: '4',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Rate Type',
    attributeName: 'h_rate_type',
    description: 'Refers to the type of rates defined for the BIT',
    sampleValue: 'Corporate/Regular',
    dataType: 'LOOKUP',
    lookupType: 'RATE_TYPE',
  },
  {
    businessName: 'Reason Code',
    attributeName: 'h_reason_code',
    description: 'Reason for creating a BIT',
    sampleValue: 'Member Insisted',
    dataType: 'LOOKUP',
    lookupType: 'REASON_CODE',
  },
  {
    businessName: 'Referral Member ID',
    attributeName: 'h_referral_member_id',
    description: 'Member ID of the referrer at Header level',
    sampleValue: '2730847903',
    dataType: 'TEXT',
  },
  {
    businessName: 'Rep Designation',
    attributeName: 'h_rep_designation',
    description: 'User\'s designation, the user who is creating the BIT',
    sampleValue: 'Service Executive, Mall Manager, Store Manager',
    dataType: 'TEXT',
  },
  {
    businessName: 'Representative Email',
    attributeName: 'h_rep_email',
    description: 'User\'s email Id, the user who is creating the BIT',
    sampleValue: 'rep@gmail.com',
    dataType: 'LOV',
    lovType: 'USER_LIST_EMAIL',
  },
  {
    businessName: 'Representative ID',
    attributeName: 'h_rep_id',
    description: 'User\'s GRAVTY username, the user who is creating the BIT',
    sampleValue: 'EMP435',
    dataType: 'LOV',
    lovType: 'USER_LIST',
  },
  {
    businessName: 'Savings',
    attributeName: 'h_savings',
    description: 'Amount saved in the BIT',
    sampleValue: '789',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Savings Currency',
    attributeName: 'h_savings_currency',
    description: 'Currency in which the amount was saved when transacting for this BIT',
    sampleValue: 'AED/BHD',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Source Facebook Page',
    attributeName: 'h_source_facebook_page',
    description: 'Facebook Page from which this social action is initiated',
    sampleValue: 'https://facebook.com/john',
    dataType: 'LOV',
    lovType: 'FACEBOOK_PAGE_LIST',
  },
  {
    businessName: 'Source_Member ID',
    attributeName: 'h_source_member',
    description: 'Incase of Member merge. BIT, this refers to the merged member',
    sampleValue: '3242356',
    dataType: 'TEXT',
  },
  {
    businessName: 'Sponsor ID',
    attributeName: 'h_sponsor_id',
    description: 'Sponsor for which the BIT is created',
    sampleValue: '32',
    dataType: 'LOV',
    lovType: 'SPONSOR_LIST',
  },
  {
    businessName: 'Sponsor Name',
    attributeName: 'h_sponsor_name',
    description: 'Name of the Sponsor for which BIT is created',
    sampleValue: 'Burj Al Arab',
    dataType: 'LOV',
    lovType: 'SPONSOR_LIST',
  },
  {
    businessName: 'Start Date',
    attributeName: 'h_start_date',
    description: 'Represents any kind of start date which is sent by source',
    sampleValue: '44077',
    dataType: 'DATE',
  },
  {
    businessName: 'Target_Member ID',
    attributeName: 'h_target_member',
    description: 'During Merging of the Members, this is the surviving Member ID',
    sampleValue: '7812723312(Member Id)',
    dataType: 'TEXT',
  },
  {
    businessName: 'TIER Change Reason',
    attributeName: 'h_tier_change_reason',
    description: 'Reason for tier change',
    sampleValue: 'Manual change',
    dataType: 'LOOKUP',
    lookupType: 'TIER_CHANGE_REASON',
  },
  {
    businessName: 'Amount',
    attributeName: 'l_amount',
    description: 'Amount of the line item',
    sampleValue: '435',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Amount Currency',
    attributeName: 'l_amount_currency',
    description: 'Currency of line amount',
    sampleValue: 'AED',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Base Accrual',
    attributeName: 'l_base_accrual',
    description: 'Base Points accrued by the Member in the line-level transaction based on the offer setup',
    sampleValue: '420',
    dataType: 'NUMBER',
  },
  {
    businessName: 'BIT Type',
    attributeName: 'l_bit_type',
    description: 'Type of BIT/activity tracked at line-level',
    sampleValue: 'Service',
    dataType: 'LOOKUP',
    lookupType: 'BIT_TYPE',
  },
  {
    businessName: 'Cost',
    attributeName: 'l_cost',
    description: 'Cost of the product/service purchased, tracked at line-level',
    sampleValue: '300',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Cost Currency',
    attributeName: 'l_cost_currency',
    description: 'Currency of the Cost of the product/Service',
    sampleValue: 'AED',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Deal Code',
    attributeName: 'l_deal_code',
    description: 'Deal Code used in the line level transaction, this code is defined in GRAVTY\'s offers',
    sampleValue: 'AMAZON10',
    dataType: 'TEXT',
  },
  {
    businessName: 'Discount Code',
    attributeName: 'l_discount_code',
    description: 'Discount Code used in the transaction at line level, this value comes in transaction and defined in external system',
    sampleValue: 'CODE40',
    dataType: 'TEXT',
  },
  {
    businessName: 'Location',
    attributeName: 'l_location',
    description: 'Sponsor Location at which the Line item was purchased',
    sampleValue: 'Burj Al Arab',
    dataType: 'LOV',
    lovType: 'SPONSOR_LOCATION_LIST',
  },
  {
    businessName: 'Loyalty Account',
    attributeName: 'l_loyalty_account',
    description: 'The account in which the accrual is transacted. This is applicable when a value in sent in l_base_accrual',
    sampleValue: '7394857F',
    dataType: 'LOV',
    lovType: 'LOYALTY_ACCOUNT_LIST',
  },
  {
    businessName: 'Order ID',
    attributeName: 'l_order_id',
    description: 'ID of the Order of this line in this Transaction',
    sampleValue: '7834',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Original Amount',
    attributeName: 'l_original_amount',
    description: 'Original Amount of this line that includes bank component, discount, paid in points, etc',
    sampleValue: '456',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Original Amount Currency',
    attributeName: 'l_original_amount_currency',
    description: 'Currency of the Original Amount',
    sampleValue: 'AED',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Privilege',
    attributeName: 'l_privilege',
    description: 'List of name of all the privileges that the member availed from the line',
    sampleValue: 'Complimentary Room Upgrade',
    dataType: 'LOV',
    lovType: 'PRIVILEGE_LIST_NAME',
  },
  {
    businessName: 'Privilege ID',
    attributeName: 'l_privilege_id',
    description: 'List of IDs of all the privileges that the member availed from the line',
    sampleValue: 'JKF12F',
    dataType: 'LOV',
    lovType: 'PRIVILEGE_LIST',
  },
  {
    businessName: 'Product Category',
    attributeName: 'l_product_category',
    description: 'Category of the product used in the line',
    sampleValue: 'Booking',
    dataType: 'LOOKUP',
    lookupType: 'PRODUCT_CATEGORY',
  },
  {
    businessName: 'Product ExternalID',
    attributeName: 'l_product_external_id',
    description: 'External ID of the product used in the line',
    sampleValue: '783',
    dataType: 'LOV',
    lovType: 'SPONSOR_PRODUCT_EXTERNAL_LIST',
  },
  {
    businessName: 'Product ID',
    attributeName: 'l_product_id',
    description: 'ID of the product used in this line',
    sampleValue: '567',
    dataType: 'LOV',
    lovType: 'SPONSOR_PRODUCT_LIST',
  },
  {
    businessName: 'Product Line',
    attributeName: 'l_product_line',
    description: 'Product Line used in the line-level transaction corresponding to l_product_id',
    sampleValue: 'Food',
    dataType: 'LOOKUP',
    lookupType: 'PRODUCT_LINE',
  },
  {
    businessName: 'Product Name',
    attributeName: 'l_product_name',
    description: 'Name of the product used in the line-level transaction corresponding to l_product_id',
    sampleValue: 'Ice Cream',
    dataType: 'TEXT',
  },
  {
    businessName: 'Quantity',
    attributeName: 'l_quantity',
    description: 'Quantity of the line item',
    sampleValue: '7',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Representative Email',
    attributeName: 'l_rep_email',
    description: 'Refers to the Representative\'s email ID',
    sampleValue: 'john345@gmail.com',
    dataType: 'LOV',
    lovType: 'USER_LIST_EMAIL',
  },
  {
    businessName: 'Representative ID',
    attributeName: 'l_rep_id',
    description: 'ID of the Representative',
    sampleValue: 'John',
    dataType: 'LOV',
    lovType: 'USER_LIST',
  },
  {
    businessName: 'Savings',
    attributeName: 'l_savings',
    description: 'Refers to the amount saved in a line-level transaction',
    sampleValue: '45',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Savings Currency',
    attributeName: 'l_savings_currency',
    description: 'Refers to the currency of the amount saved in a line-level transaction',
    sampleValue: 'AED/BHD',
    dataType: 'LOOKUP',
    lookupType: 'CURRENCY',
  },
  {
    businessName: 'Offer ID',
    attributeName: 'offer_id',
    description: 'Determines the offer which the users wants to run for a particular transaction',
    sampleValue: '47583',
    dataType: 'LOV',
    lovType: 'OFFER_LIST',
  },
  {
    businessName: 'Primary BIT ID',
    attributeName: 'primary_bit_id',
    description: 'BIT Id of the original BIT which generated this BIT, this is applicable for THIRD_PARTY_REWARD type BITs.(THIRD_PARTY_REWARD is rewarding the entity which is not involved in the transaction)',
    sampleValue: 'TXN234',
    dataType: 'TEXT',
  },
  {
    businessName: 'Primary BIT Type',
    attributeName: 'primary_bit_type',
    description: 'BIT type of the original BIT which generated this BIT, this is applicable for THIRD_PARTY_REWARD type BITs.(THIRD_PARTY_REWARD is rewarding the entity which is not involved in the transaction)',
    sampleValue: 'Dining/Enroll/Spend',
    dataType: 'LOOKUP',
    lookupType: 'BIT_TYPE',
  },
  {
    businessName: 'Primary Member ID',
    attributeName: 'primary_member_id',
    description: 'Member Id of the original BIT which generated the BIT, applicable for THIRD_PARTY_REWARD type BITs.(THIRD_PARTY_REWARD is rewarding the entity which is not involved in the transaction)',
    sampleValue: '2637434',
    dataType: 'TEXT',
  },
  {
    businessName: 'BITProcessed Date',
    attributeName: 'processing_date',
    description: 'Refers to the datetime at which the BIT is processed in GRAVTY',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Transfer Privilege Code',
    attributeName: 'transfer_privilege_code',
    description: 'Privilege code of a privilege which a member wishes to transfer to some other member',
    sampleValue: 'JMOUT45',
    dataType: 'TEXT',
  },
  {
    businessName: 'Transferee Member ID',
    attributeName: 'transferee_member_id',
    description: 'Member Id of member to whom member wishes to transfer their points to',
    sampleValue: '2342348577',
    dataType: 'TEXT',
  },
  {
    businessName: 'Verification Code',
    attributeName: 'verification_code',
    description: 'Verification code, if required, for a particular transaction',
    sampleValue: '234879',
    dataType: 'TEXT',
  },
  {
    businessName: 'Payment Method',
    attributeName: 'payment_method',
    description: 'Determines the payment method for a transaction',
    sampleValue: 'Payment via CASH, DEBIT, CREDIT',
    dataType: 'LOOKUP',
    lookupType: 'PAYMENT_MODE',
  },
  {
    businessName: 'Amount',
    attributeName: 'amount',
    description: 'Refers to payment amount done via payment method like, cash, credit, debit, e.t.c',
    sampleValue: '3400',
    dataType: 'NUMBER',
  },
];
