import type { DataModelAttribute } from '../types';

export const locationAttributes: DataModelAttribute[] = [
  {
    businessName: 'Active',
    attributeName: 'active',
    description: 'Describes Sponsor Location\'s status, only active locations transactions would be valid',
    sampleValue: 'True/False',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'Address',
    attributeName: 'address',
    description: 'Refers to Sponsor Location\'s address',
    sampleValue: 'Burj Al Arab',
    dataType: 'TEXT',
  },
  {
    businessName: 'Area',
    attributeName: 'area',
    description: 'Refers to Sponsor Location\'s area',
    sampleValue: '27th floor,Burj Al Arab Jumeirah',
    dataType: 'LOV',
    lovType: 'AREA_LIST',
  },
  {
    businessName: 'City',
    attributeName: 'city',
    description: 'Refers to Sponsor Location\'s city',
    sampleValue: 'Jumeirah St',
    dataType: 'LOV',
    lovType: 'CITY_LIST',
  },
  {
    businessName: 'Contact',
    attributeName: 'contact_name',
    description: 'Refers to the name of Location\'s Contact person, who would be created as Sponsor location representative user in GRAVTY',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Contact Number',
    attributeName: 'contact_phone',
    description: 'Refers to Sponsor Location representative\'s contact number',
    sampleValue: '1234567890',
    dataType: 'TEXT',
  },
  {
    businessName: 'Country',
    attributeName: 'country',
    description: 'Refers to Sponsor Location\'s Country',
    sampleValue: 'Dubai',
    dataType: 'LOV',
    lovType: 'COUNTRY_LIST',
  },
  {
    businessName: 'Destination',
    attributeName: 'destination',
    description: 'Refers to the Location\'s Destination',
    sampleValue: 'burj Al Arab',
    dataType: 'LOOKUP',
    lookupType: 'DESTINATION',
  },
  {
    businessName: 'Division',
    attributeName: 'division',
    description: 'Refers to Location\'s division. This division is done based on the geographical location',
    sampleValue: 'EAST',
    dataType: 'LOOKUP',
    lookupType: 'DIVISION',
  },
  {
    businessName: 'Domain URL',
    attributeName: 'online_url',
    description: 'Refers to the website URL, needed only when location is an online location',
    sampleValue: 'https://www.jumeirah.com/en',
    dataType: 'TEXT',
  },
  {
    businessName: 'Email',
    attributeName: 'contact_email',
    description: 'Location Representative\'s Email, with this email id, a user would be created in GRAVTY as sponsor location representative',
    sampleValue: 'john@gmail.com',
    dataType: 'TEXT',
  },
  {
    businessName: 'Latitude',
    attributeName: 'latitude',
    description: 'Offline Location\'s Latitude value, used to pin the location on maps',
    sampleValue: '25.1415447',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Location Category',
    attributeName: 'location_category',
    description: 'Determines Location\'s category,\nIf location is online, online_URL is mandatory and if location is offline, latitude and longitude are mandatory',
    sampleValue: 'Online, Offline',
    dataType: 'TEXT',
  },
  {
    businessName: 'Location Code',
    attributeName: 'location_code',
    description: 'Each location in GRAVTY has unique alphanumeric location code, used when sending transactions to GRAVTY',
    sampleValue: 'BAA266',
    dataType: 'TEXT',
  },
  {
    businessName: 'Location Name',
    attributeName: 'location_name',
    description: 'Location\'s Name visible in GRAVTY and other member facing applications',
    sampleValue: 'Al Muntaha',
    dataType: 'TEXT',
  },
  {
    businessName: 'Location Type',
    attributeName: 'location_type',
    description: 'Location\'s Type, used to tag location under particular segment',
    sampleValue: 'Outlet',
    dataType: 'LOOKUP',
    lookupType: 'LOCATION_TYPE',
  },
  {
    businessName: 'Longitude',
    attributeName: 'longitude',
    description: 'Location\'s Longitude values, used to pin the location on maps',
    sampleValue: '55.1832383',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Phone Number',
    attributeName: 'phone_number',
    description: 'Location\'s phone number which would be visible to the member on the website',
    sampleValue: '91234567890',
    dataType: 'TEXT',
  },
  {
    businessName: 'Pin Code',
    attributeName: 'pin_code',
    description: 'Refers to location\'s Pin code on the map address',
    sampleValue: '12345',
    dataType: 'TEXT',
  },
  {
    businessName: 'Sponsor',
    attributeName: 'sponsor',
    description: 'Refers to which the Location the Sponsor is mapped to',
    sampleValue: 'Jumeirah Hotels',
    dataType: 'LOV',
    lovType: 'SPONSOR_LIST',
  },
  {
    businessName: 'Sponsor Location Enrollment Form URL',
    attributeName: 'acquisition_url',
    description: 'Refers to the member enrollment form URL. Also, used to keep a track of number of members getting enrolled',
    sampleValue: 'https://www.jumeirah.com/en/join-now',
    dataType: 'TEXT',
  },
  {
    businessName: 'State',
    attributeName: 'state',
    description: 'Location\'s State',
    sampleValue: 'Jumeirah St',
    dataType: 'LOV',
    lovType: 'REGION_LIST',
  },
  {
    businessName: 'Tags',
    attributeName: 'tags',
    description: 'Used for optimizing location search and recommendations, also called facets',
    sampleValue: 'Coffee',
    dataType: 'LOOKUP',
    lookupType: 'LOCATION_TAGS',
  },
  {
    businessName: 'Upload an Image for this Area',
    attributeName: 'image',
    description: 'Location\'s Image for that sponsor location',
    sampleValue: 'https://GRAVTY-media.qav2.gravtee.com/cf-data/173/sponsor/1/locations/images/21e0f845-8c36-4020-bdcc-7697b2f68d1e-download.png',
    dataType: 'TEXT',
  },
  {
    businessName: 'Location PIN',
    attributeName: 'PIN',
    description: 'This PIN is used to validate whether a transaction is approved by the location owner/operator, the PIN can be 4 digit numeric value',
    sampleValue: '6734',
    dataType: 'TEXT',
  },
];
