import type { DataModelAttribute } from '../types';

export const memberAttributes: DataModelAttribute[] = [
  {
    businessName: 'Address Line 1',
    attributeName: 'address_line1',
    description: 'Member\'s address line 1.',
    sampleValue: '831 Spring Haven Trail',
    dataType: 'TEXT',
  },
  {
    businessName: 'Address Line 2',
    attributeName: 'address_line2',
    description: 'Member\'s address line 2.',
    sampleValue: 'Netcong',
    dataType: 'TEXT',
  },
  {
    businessName: 'Age',
    attributeName: 'age',
    description: 'Member\'s age, calculated from Members Date of Birth, used to create targeted offers, determine member\'s eligibility to enroll into program.',
    sampleValue: '32',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Alias',
    attributeName: 'alias',
    description: 'Member\'s alias name, an alternate name for the member.',
    sampleValue: 'Johny',
    dataType: 'TEXT',
  },
  {
    businessName: 'Annual Income',
    attributeName: 'annual_income',
    description: 'Member\'s Annual Income.',
    sampleValue: '50,001 - 75,000',
    dataType: 'LOOKUP',
    lookupType: 'INCOME_RANGE',
  },
  {
    businessName: 'Apple UID',
    attributeName: 'apple_uid',
    description: 'Member\'s Apple user ID. Used when social login is enabled.',
    sampleValue: 'michael_cavanna@icloud.com',
    dataType: 'TEXT',
  },
  {
    businessName: 'Area',
    attributeName: 'area',
    description: 'Member\'s residing area.',
    sampleValue: 'New Jersey',
    dataType: 'LOV',
    lovType: 'AREA_LIST',
  },
  {
    businessName: 'Associate ID',
    attributeName: 'associate_id',
    description: 'ID of Associate of the company who have enrolled the Member, used to track and incentivize.',
    sampleValue: 'Bevan',
    dataType: 'TEXT',
  },
  {
    businessName: 'Behavior Value',
    attributeName: 'behaviour_value',
    description: 'This value measures the member\'s behaviour in the program assigned by the host sponsor, the value can be configured in the offer. Based on certain behaviour of the member, host sponsor would assign certain value. Used to gauge the value that member brings into the program.',
    sampleValue: '454',
    dataType: 'NUMBER',
  },
  {
    businessName: 'BIT Class',
    attributeName: 'bit_class',
    description: 'Member\'s BIT Class.',
    sampleValue: 'Gold',
    dataType: 'TEXT',
  },
  {
    businessName: 'BIT Rank',
    attributeName: 'bit_rank',
    description: 'Member\'s BIT Rank.',
    sampleValue: '34',
    dataType: 'NUMBER',
  },
  {
    businessName: 'BIT Score',
    attributeName: 'bit_score',
    description: 'This represents the value that member brings to the program (BIT Value) against the cost incurred by the program on the member. we get the value as BIT Value/Relationship Cost. Used to gauge the value that member brings into the program with respect to the cost incurred by the host sponsor.',
    sampleValue: '32',
    dataType: 'NUMBER',
  },
  {
    businessName: 'BIT Value',
    attributeName: 'bit_value',
    description: 'This represents an instance of a customer’s engagement with the brand, which comprises a specific Behavior or an Influence or a transaction or a combination of all these. Used to gauge the value that member brings into the program..',
    sampleValue: '34',
    dataType: 'NUMBER',
  },
  {
    businessName: 'City',
    attributeName: 'city',
    description: 'Member\'s Residing City.',
    sampleValue: 'New Jersey',
    dataType: 'LOV',
    lovType: 'CITY_LIST',
  },
  {
    businessName: 'Companion Designation',
    attributeName: 'companion_designation',
    description: 'Stores companion\'s designation,Using this feature, both the member and companion member can extra benefits from the loyalty program.',
    sampleValue: 'Primary',
    dataType: 'TEXT',
  },
  {
    businessName: 'Companion Member',
    attributeName: 'companion_member',
    description: 'Stores companion member\'s ID. Using this feature, both the member and companion member can extra benefits from the loyalty program.',
    sampleValue: 'candy',
    dataType: 'TEXT',
  },
  {
    businessName: 'Company',
    attributeName: 'company',
    description: 'Company where the Member is currently working in.',
    sampleValue: 'Google',
    dataType: 'TEXT',
  },
  {
    businessName: 'Corporate',
    attributeName: 'corporate',
    description: 'An entity to which is member is associated with and user can configure offers like corporate discounts,corporate incentives, Privileges etc.',
    sampleValue: 'LJI',
    dataType: 'LOV',
    lovType: 'CORPORATE_MEMBER_LIST',
  },
  {
    businessName: 'Country',
    attributeName: 'country',
    description: 'Member\'s country of residence. Used to created targeted offers.',
    sampleValue: 'United States',
    dataType: 'LOV',
    lovType: 'COUNTRY_LIST',
  },
  {
    businessName: 'Date of Birth',
    attributeName: 'date_of_birth',
    description: 'Member\'s Date of Birth. Used to create targeted offers and determine enrolment eligibility by calculating age.',
    sampleValue: '34705',
    dataType: 'DATE',
  },
  {
    businessName: 'Date of Joining',
    attributeName: 'date_of_joining',
    description: 'Refers to the Joining date or date of enrolment of guest member into the loyalty program. Used to derive other attributes like membership end date, or to create targeted offers etc.',
    sampleValue: '43836',
    dataType: 'DATE',
  },
  {
    businessName: 'Days since last BIT',
    attributeName: 'days_since_bit',
    description: 'Number of days since the last BIT (transaction), can be used to target offers.',
    sampleValue: '3',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Email',
    attributeName: 'email',
    description: 'Member\'s Email ID. Used as a log in attribute, or to communicate with member.',
    sampleValue: 'john345@gmail.com',
    dataType: 'TEXT',
  },
  {
    businessName: 'Acquiring Location',
    attributeName: 'enrolling_location',
    description: 'Location at which the member was enrolled into the program. Used to target offers.',
    sampleValue: 'Jumeirah',
    dataType: 'LOV',
    lovType: 'SPONSOR_LOCATION_LIST',
  },
  {
    businessName: 'Acquiring Sponsor',
    attributeName: 'enrolling_sponsor',
    description: 'Sponsor under whom the member is enrolled. Used to target offers.',
    sampleValue: 'jumeirah',
    dataType: 'LOV',
    lovType: 'SPONSOR_LIST',
  },
  {
    businessName: 'Enrollment Channel',
    attributeName: 'enrollment_channel',
    description: 'Refers to the Enrollment channel through which the Member gets enrolled. To keep track of what channels are being utilized actively.',
    sampleValue: 'Mobile, WEB, POS',
    dataType: 'LOOKUP',
    lookupType: 'ENROLLMENT_CHANNEL',
  },
  {
    businessName: 'Referrer - Membership',
    attributeName: 'enrollment_referrer',
    description: 'Member who referred the new member to enroll into the Program. Used to track and incentivize the referrers.',
    sampleValue: 'James Clear',
    dataType: 'TEXT',
  },
  {
    businessName: 'Enrollment Touch Point',
    attributeName: 'enrollment_touchpoint',
    description: 'Refers to the different touchpoints i.e points of contacts for a member to get enrolled, this would be subset of enrolment channels.',
    sampleValue: 'POS',
    dataType: 'LOV',
    lovType: 'ENROLLMENT_TOUCHPOINT_LIST',
  },
  {
    businessName: 'Enrollment User',
    attributeName: 'enrollment_user',
    description: 'Email ID of the user who enrolled the member.',
    sampleValue: 'john@gmail.com',
    dataType: 'TEXT',
  },
  {
    businessName: 'Ethnicity',
    attributeName: 'ethnicity',
    description: 'Member\'s ethnicity.',
    sampleValue: 'Indian Americans',
    dataType: 'LOOKUP',
    lookupType: 'ETHNICITY',
  },
  {
    businessName: 'External ID',
    attributeName: 'external_id',
    description: 'Member\'s ID as registered in the external system.',
    sampleValue: '674',
    dataType: 'TEXT',
  },
  {
    businessName: 'FaceBook ID',
    attributeName: 'facebook_id',
    description: 'Facebook ID of the Member. Used to track member actions on Facebook related to the sponsor. e.g., likes on post. Used when social login is enabled.',
    sampleValue: '635634665444',
    dataType: 'TEXT',
  },
  {
    businessName: 'Family Designation',
    attributeName: 'family_designation',
    description: 'Refers to the Member\'s designation in the Family.',
    sampleValue: 'FAMILY_HEAD/FAMILY_MEMBER',
    dataType: 'LOV',
    lovType: 'FAMILY_DESIGNATION',
  },
  {
    businessName: 'Family Head',
    attributeName: 'family_head',
    description: 'This attribute contains the details of member\'s head login attribute(login attribute might be mobile number, email id, etc.,',
    sampleValue: '236723484/john34@gmail.com',
    dataType: 'LOV',
    lovType: 'MEMBER_LIST',
  },
  {
    businessName: 'Family Head Point Share',
    attributeName: 'family_head_points_share',
    description: 'Percentage of points to share with the family head.',
    sampleValue: '20',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Family Head Relationship',
    attributeName: 'family_head_relationship',
    description: 'Relationship of the Member to the Family Head.',
    sampleValue: 'Brother',
    dataType: 'LOOKUP',
    lookupType: 'FAMILY_HEAD_RELATIONSHIP',
  },
  {
    businessName: 'Favorite Categories',
    attributeName: 'favorite_categories',
    description: 'Member\'s favorite Sponsor categories.',
    sampleValue: 'Food & Beverages, Clothing e.t.c',
    dataType: 'TEXT',
  },
  {
    businessName: 'Favorite Drink',
    attributeName: 'favorite_drink',
    description: 'Member\'s favorite drink. Used to create targeted offers.',
    sampleValue: 'KINGFISHER',
    dataType: 'LOOKUP',
    lookupType: 'FAVORITE_DRINK',
  },
  {
    businessName: 'Favorite Food',
    attributeName: 'favorite_food',
    description: 'Member\'s favourite food. Used to create targeted offers.',
    sampleValue: 'MEXICAN',
    dataType: 'LOOKUP',
    lookupType: 'FAVORITE_FOOD',
  },
  {
    businessName: 'Favorite Restaurant',
    attributeName: 'favorite_restaurant',
    description: 'Member \'s favourite restaurant. Used to create targeted offers.',
    sampleValue: 'Pappadeux Seafood Kitchen',
    dataType: 'LOOKUP',
    lookupType: 'FAVORITE_RESTAURANT',
  },
  {
    businessName: 'Favorite Sport',
    attributeName: 'favorite_sport',
    description: 'Member\'s favourite sport. Used to create targeted offers.',
    sampleValue: 'BADMINTON',
    dataType: 'LOOKUP',
    lookupType: 'FAVORITE_SPORT',
  },
  {
    businessName: 'FB Friends',
    attributeName: 'fb_friends',
    description: 'Refers to the number of friends of the member who are present on Facebook.',
    sampleValue: '34',
    dataType: 'NUMBER',
  },
  {
    businessName: 'First Name',
    attributeName: 'first_name',
    description: 'Member\'s first name, visible on the member facing portal.',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Food Preference',
    attributeName: 'food_preference',
    description: 'Member\'s food preference. Used to create targeted offers.',
    sampleValue: 'VEG',
    dataType: 'LOOKUP',
    lookupType: 'FOOD_PREFERENCE',
  },
  {
    businessName: 'Gender',
    attributeName: 'gender',
    description: 'Member\'s gender. Used to create targeted offers.',
    sampleValue: 'Male',
    dataType: 'LOOKUP',
    lookupType: 'GENDER',
  },
  {
    businessName: 'GooglePlus ID',
    attributeName: 'googleplus_id',
    description: 'Member\'s Google Plus ID. Used to track member actions on Google+ related to the sponsor. e.g., likes or shares.',
    sampleValue: 'https://www.googleplus.com/in/john',
    dataType: 'TEXT',
  },
  {
    businessName: 'Highest Education Level',
    attributeName: 'highest_education',
    description: 'Member\'s highest education.',
    sampleValue: 'GRADUATE',
    dataType: 'LOOKUP',
    lookupType: 'EDUCATION_LEVEL',
  },
  {
    businessName: 'Hobbies',
    attributeName: 'hobbies',
    description: 'Member\'s hobbies. Used to create targeted offers.',
    sampleValue: 'MUSIC,TENNIS',
    dataType: 'LOOKUP',
    lookupType: 'HOBBIES',
  },
  {
    businessName: 'Influence Value',
    attributeName: 'influence_value',
    description: 'This value measures the member\'s Influential value in the program, this can be configured in the offer. Based on the influence the member creates on other non members, we will assign certain value.',
    sampleValue: 'Refers new members into the program',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Institution',
    attributeName: 'institution',
    description: 'Refers to the Institution with which Member is associated (Institution is enrolled as Member in GRAVTY).',
    sampleValue: 'Municipality',
    dataType: 'TEXT',
  },
  {
    businessName: 'Job Title',
    attributeName: 'job_title',
    description: 'Member\'s job title in the current company.',
    sampleValue: 'Associate',
    dataType: 'LOOKUP',
    lookupType: 'JOB_TITLE',
  },
  {
    businessName: 'Last Accrual Date',
    attributeName: 'last_accrual_date',
    description: 'Refers to the Last Accrual date, the latest date on which the member earned points.',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Last BIT Date',
    attributeName: 'last_activity_date',
    description: 'Refers to the latest date on which offer action has been applied on the BIT.',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Last Name',
    attributeName: 'last_name',
    description: 'Last name of the Member.',
    sampleValue: 'Bevan',
    dataType: 'TEXT',
  },
  {
    businessName: 'Last Redemption Date',
    attributeName: 'last_redemption_date',
    description: 'Refers to the last date on which the awarded points are redeemed by the Member.',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Latitude',
    attributeName: 'latitude',
    description: 'Latitude of the Member\'s Residential location.',
    sampleValue: '25.2016° N',
    dataType: 'NUMBER',
  },
  {
    businessName: 'LinkedIn ID',
    attributeName: 'linkedin_id',
    description: 'Member\'s Linkedln ID. Used to track member actions on LinkedIn related to the sponsor. e.g., likes or shares.',
    sampleValue: 'https://www.linkedin.com/in/john',
    dataType: 'TEXT',
  },
  {
    businessName: 'Longitude',
    attributeName: 'longitude',
    description: 'Longitude of the Member\'s Residential location.',
    sampleValue: '55.2453° E',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Marital Status',
    attributeName: 'marital_status',
    description: 'Member\'s marital status. Used to create targeted offers.',
    sampleValue: 'Married',
    dataType: 'LOOKUP',
    lookupType: 'MARITAL_STATUS',
  },
  {
    businessName: 'Member ID',
    attributeName: 'member_id',
    description: 'Refers to the Unique Member ID of the Member.',
    sampleValue: '2000367991',
    dataType: 'TEXT',
  },
  {
    businessName: 'Member Name',
    attributeName: 'member_name',
    description: 'Refers to member\'s name given by the member,  member_name would be concatenated value of First Name, Middle name and Last Name incase member has not given his name..',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Member Type',
    attributeName: 'member_type',
    description: 'Refers to the type of Member(Employee of company, staff member.. etc), these are used to differentiate between the members and configure offer based on them.',
    sampleValue: 'Corporate/Staff/Institution',
    dataType: 'LOOKUP',
    lookupType: 'MEMBER_TYPE',
  },
  {
    businessName: 'Membership Stage',
    attributeName: 'membership_stage',
    description: 'Member\'s Membership Stage, these can be used to limit member access to rewards, awards or offers.',
    sampleValue: 'Active',
    dataType: 'LOV',
    lovType: 'MEMBERSHIP_STAGE_LIST',
  },
  {
    businessName: 'Membership Tenure',
    attributeName: 'membership_tenure',
    description: 'Number of total days since Enrolment. Derived from member\'s date of joining.',
    sampleValue: '10',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Middle Name',
    attributeName: 'middle_name',
    description: 'Member\'s middle name.',
    sampleValue: 'Wick',
    dataType: 'TEXT',
  },
  {
    businessName: 'Mobile Number',
    attributeName: 'mobile',
    description: 'Member\'s mobile number, can be used for as login attribute in Member facing portals.',
    sampleValue: '9876543210',
    dataType: 'TEXT',
  },
  {
    businessName: 'Preferred Mode of Communication',
    attributeName: 'mode_of_communication',
    description: 'Member\'s preferred mode of communication, we use this preference to communicate with the Member.',
    sampleValue: 'PHONE',
    dataType: 'LOOKUP',
    lookupType: 'COMMUNICATION_MODE',
  },
  {
    businessName: 'Mother Tongue',
    attributeName: 'mother_tongue',
    description: 'Member\'s mother tongue. Used to create targeted offers.',
    sampleValue: 'English',
    dataType: 'LOOKUP',
    lookupType: 'MOTHER_TONGUE',
  },
  {
    businessName: 'Nationality',
    attributeName: 'nationality',
    description: 'Member\'s nationality. Used to create targeted offers.',
    sampleValue: 'American',
    dataType: 'LOOKUP',
    lookupType: 'NATIONALITY_LIST',
  },
  {
    businessName: 'Number of Children',
    attributeName: 'number_of_children',
    description: 'Member\'s children count. Used to create targeted offers.',
    sampleValue: '2',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Passport Number',
    attributeName: 'passport_number',
    description: 'Member\'s passport number.',
    sampleValue: 'JH234587SHYNY',
    dataType: 'TEXT',
  },
  {
    businessName: 'PIN',
    attributeName: 'pin',
    description: 'Member\'s PIN number of the supplied address.',
    sampleValue: '7857',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Pinterest ID',
    attributeName: 'pinterest_id',
    description: 'Member\'s Pinterest ID. Used to track member actions on Pinterest related to the sponsor. e.g., likes or shares.',
    sampleValue: 'https://www.pinterest.com/in/john',
    dataType: 'TEXT',
  },
  {
    businessName: 'Preferred Location',
    attributeName: 'preferred_location',
    description: 'Member\'s Preferred Sponsor Location where they would like to transact. Used to create targeted offers.',
    sampleValue: 'RS Minibar',
    dataType: 'LOV',
    lovType: 'SPONSOR_LOCATION_LIST',
  },
  {
    businessName: 'Primary Member',
    attributeName: 'primary_member',
    description: 'Member\'s Primary Member ID (Companion concept).',
    sampleValue: '234343455',
    dataType: 'TEXT',
  },
  {
    businessName: 'Program Opt In',
    attributeName: 'program_opt_in',
    description: 'Member\'s choice/response to Opt in to the Loyalty Program. Used to capture members explicit consent.',
    sampleValue: 'Yes',
    dataType: 'LOOKUP',
    lookupType: 'PROGRAM_OPT_IN',
  },
  {
    businessName: 'Receive Offer Communication',
    attributeName: 'receive_offers',
    description: 'Whether a member is willing to receive communication related to the offers applicable for him.',
    sampleValue: 'Yes/No',
    dataType: 'TEXT',
  },
  {
    businessName: 'Region',
    attributeName: 'region',
    description: 'Member\'s Residing Region. Used to create targeted offers.',
    sampleValue: 'Goa',
    dataType: 'LOV',
    lovType: 'REGION_LIST',
  },
  {
    businessName: 'Relationship Cost',
    attributeName: 'relationship_cost',
    description: 'Amount spent by loyalty program to acquire and maintain the member, i.e., cost of member to loyalty program and to calculate BIT/Quantum score.',
    sampleValue: '456',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Salutation',
    attributeName: 'salutation',
    description: 'Member\'s Salutation.',
    sampleValue: 'MR/MS/GENERAL',
    dataType: 'LOOKUP',
    lookupType: 'SALUTATION_LIST',
  },
  {
    businessName: 'Tier Class',
    attributeName: 'tier_class',
    description: 'Tier Class to which the Member belongs to, defines the Member\'s class based on BIT value.',
    sampleValue: 'Silver',
    dataType: 'LOOKUP',
    lookupType: 'TIER_CLASS',
  },
  {
    businessName: 'Tier End Date',
    attributeName: 'tier_end_date',
    description: 'The date at which the Tier class assigned to the member expires.',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Tier Start Date',
    attributeName: 'tier_start_date',
    description: 'The date at which the Tier class is assigned to the member.',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Transaction Value',
    attributeName: 'transaction_value',
    description: 'Refers to the total amount spent by the member on all the transactions for a certain period of time in the program.',
    sampleValue: '45674',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Twitter ID',
    attributeName: 'twitter_id',
    description: 'Member\'s Twitter ID. Used to track member actions on Twitter related to the sponsor. e.g., tweets or shares.',
    sampleValue: 'https://www.twitter.com/in/john',
    dataType: 'TEXT',
  },
  {
    businessName: 'Wedding Anniversary',
    attributeName: 'wedding_anniversary',
    description: 'Member\'s Wedding Anniversary Date, used to create targeted offers.',
    sampleValue: '40184',
    dataType: 'DATE',
  },
  {
    businessName: 'Zip Code',
    attributeName: 'zipcode',
    description: 'Member\'s Zip Code/ Pin Code of the Region which they supplied.',
    sampleValue: '5467',
    dataType: 'NUMBER',
  },
];
