import type { DataModelAttribute } from '../types';

export const offerAttributes: DataModelAttribute[] = [
  {
    businessName: 'Allow Sponsor Followers',
    attributeName: 'allow_sponsorfollowers',
    description: 'Member would be able to follow these sponsors through member facing portals and offer would be targetted to these followers',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'True/False',
    lovType: '8',
  },
  {
    businessName: 'Availed Total',
    attributeName: 'availed_total',
    description: 'Number of times an offer has been applied for the transactions done by the members',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '140',
    lovType: '10',
  },
  {
    businessName: 'Availed Unique',
    attributeName: 'availed_unique',
    description: 'Number of unique transactions of a particular offer',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '89',
    lovType: '10',
  },
  {
    businessName: 'Average Rating',
    attributeName: 'average_rating',
    description: 'Offer\'s average rating, This attribute helps in capturing the ratings given by the member for an offer in Member facing portals.',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '4',
    lovType: '3',
  },
  {
    businessName: 'Batch Id',
    attributeName: 'batch_id',
    description: 'Batch ID is generated when a scheduled or Privilege Offer is launched',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '345',
    lovType: '10',
  },
  {
    businessName: 'Budget',
    attributeName: 'budget',
    description: 'Total amount of money the Program Manager has invested in an offer',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '17000',
    lovType: '10',
  },
  {
    businessName: 'Cost',
    attributeName: 'cost',
    description: 'Cost incurred for this offer by the sponsor',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '15000',
    lovType: '15',
  },
  {
    businessName: 'Count',
    attributeName: 'count',
    description: 'Total number of members in the program',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '37 million',
    lovType: '10',
  },
  {
    businessName: 'Deal Code',
    attributeName: 'deal_code',
    description: 'Common deal code which can be used accross by the member to avail a voucher/offer',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'DINE45',
    lovType: '50',
  },
  {
    businessName: 'End Date',
    attributeName: 'end_date',
    description: 'Refers to Offer\'s end date ',
    sampleValue: 'DATETIME',
    dataType: '',
    lookupType: '46307',
    lovType: '64',
  },
  {
    businessName: 'Fb Share',
    attributeName: 'fb_share',
    description: 'for an offer with limited availments, \'Num of Clients\' decreases each time a member avails the offer',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'True/False',
    lovType: '8',
  },
  {
    businessName: 'Interval',
    attributeName: 'interval',
    description: 'Refers to the duration type for scheduled offers',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Daily/Weekly/Monthly/Yearly',
    lovType: '50',
  },
  {
    businessName: 'Interval Period',
    attributeName: 'interval_period',
    description: 'Refers to frequency of the schedule i.e number of times the offer would run in an interval',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '4',
    lovType: '10',
  },
  {
    businessName: 'Is Base Offer',
    attributeName: 'is_base_offer',
    description: 'When enabled, the offer would be applicable accross all Sponsors, else only for a particular sponsor for which Offer is created',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'True/False',
    lovType: '8',
  },
  {
    businessName: 'Is Template Based',
    attributeName: 'is_template_based',
    description: 'Enabled when the Offer is Template based, i.e the offer is imported via Batch',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'True/False',
    lovType: '8',
  },
  {
    businessName: 'Landing Page Url',
    attributeName: 'landing_page_url',
    description: 'Where the member would be redirected to avail the offer',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'www.https://jumeirah/burjalarab/offers/HJ3674.com',
    lovType: '300',
  },
  {
    businessName: 'Launch Date',
    attributeName: 'launch_date',
    description: 'Refers to the date on which the offer is/will be launched',
    sampleValue: 'DATE',
    dataType: '',
    lookupType: '46307',
    lovType: '10',
  },
  {
    businessName: 'Location Category',
    attributeName: 'location_category',
    description: 'Category of the location',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Online/Offline',
    lovType: '50',
  },
  {
    businessName: 'Location Urls',
    attributeName: 'location_urls',
    description: 'Refers to the online location URL where members can avail the offer',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'www.https://jumeirah/burjalarab.com',
  },
  {
    businessName: 'Max Period',
    attributeName: 'max_period',
    description: 'Maximum times the Offer can be applied in a transaction ',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '3',
    lovType: '10',
  },
  {
    businessName: 'Max usage Per User',
    attributeName: 'max_usage_per_user',
    description: 'Offer usage limit per member',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '3',
    lovType: '10',
  },
  {
    businessName: 'Member Target Json',
    attributeName: 'member_target_json',
    description: 'Stores the JSON for targetting members, not visible on the UI',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: '.json file',
  },
  {
    businessName: 'Member Target Type',
    attributeName: 'member_target_type',
    description: 'Member segments type to be targetted for an offer',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'My members, All members e,t,c',
    lovType: '10',
  },
  {
    businessName: 'Member Target Xml',
    attributeName: 'member_target_xml',
    description: 'This represents the blockly rules configured in XML format, we can upload these into the rules for predefined rules',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: '.xml file',
    lovType: '500',
  },
  {
    businessName: 'Member Visible',
    attributeName: 'member_visible',
    description: 'Determines whether the offer should be visible to the members in member facing portals',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'True/False',
    lovType: '8',
  },
  {
    businessName: 'Non Cumulative',
    attributeName: 'non_cumulative',
    description: 'whether an Offer is cumulative/Non-cumulative. If enabled for few offers, only one of few would be applied.(Based on Priority if provided, else random)',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'True/False',
    lovType: '8',
  },
  {
    businessName: 'Non Cumulative Level',
    attributeName: 'non_cumulative_level',
    description: 'Determines if the offer is header non cumulative or line non cumulative. \nOnly one offer is applied on a transaction from header non cumulative offers or,\nonly one Offer is applied on each line from Line non-cumulative offers.',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'header_level/line_level',
    lovType: '50',
  },
  {
    businessName: 'Num Of Clients',
    attributeName: 'num_of_clients',
    description: 'For an offer with limited availments, \'Num of Clients\' decreases each time a member avails the offer',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '45',
    lovType: '10',
  },
  {
    businessName: 'Offer Acceptance Required',
    attributeName: 'offer_acceptance_required',
    description: 'Offer for which Member acceptance is needed to perform the transaction on which this offer gets applied',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'yes/No',
    lovType: '8',
  },
  {
    businessName: 'Offer Description',
    attributeName: 'offer_description',
    description: 'Offer\'s description ',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Exchange your Jumeirah One Points for an USD 100 lifestyle voucher that you can enjoy in an array of exciting ways.',
    lovType: '500',
  },
  {
    businessName: 'Offer Name',
    attributeName: 'offer_name',
    description: 'Offer\'s Title',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Three Course Meal - Signature Dining',
    lovType: '50',
  },
  {
    businessName: 'Offer Type',
    attributeName: 'offer_type',
    description: 'Offer Type i.e Award, Reward, Privilege or Deal',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Award',
    lovType: '50',
  },
  {
    businessName: 'Price',
    attributeName: 'price',
    description: 'Award Product Price - Applicable only for Award Offers',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '350 AED',
    lovType: '10',
  },
  {
    businessName: 'Priority',
    attributeName: 'priority',
    description: 'Refers to Sequence of execution, Highest value refers greater priority',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '5',
    lovType: '10',
  },
  {
    businessName: 'Rank',
    attributeName: 'rank',
    description: 'If specified, it will determine the display order of the offer in the offers list on member facing applications(Please do not use this attribute, this would be deprecated soon)',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '3',
    lovType: '10',
  },
  {
    businessName: 'Rating Count',
    attributeName: 'rating_count',
    description: 'Count of Members who rated this offer',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '90',
    lovType: '10',
  },
  {
    businessName: 'Send Notification',
    attributeName: 'send_notification',
    description: 'Whether you want to send the notification of offer launch/Start date or not',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'Yes',
    lovType: '8',
  },
  {
    businessName: 'Start date',
    attributeName: 'start_date',
    description: 'Validity - Offer\'s start date ',
    sampleValue: 'DATETIME',
    dataType: '',
    lookupType: '2019-09-17 11:59:59.573+00',
    lovType: '64',
  },
  {
    businessName: 'Status',
    attributeName: 'status',
    description: 'Offer\'s Status',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Active',
    lovType: '50',
  },
  {
    businessName: 'Subtitle',
    attributeName: 'subtitle',
    description: 'Offer\'s Sub Title',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Three Course Meal - Signature Dining',
    lovType: '2000',
  },
  {
    businessName: 'Template Name',
    attributeName: 'template_name',
    description: 'Name of the template used for DRL whenever offers are created via batch.',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'BOGO_Offer.csv',
    lovType: '100',
  },
  {
    businessName: 'Template Params',
    attributeName: 'template_params',
    description: 'Different parameters passed in template that are used in making DRL for the offers created via batches.',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'Offer Title,validity etc',
  },
  {
    businessName: 'Total Count',
    attributeName: 'total_count',
    description: 'Total number of the members targetted for the offer',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '240',
    lovType: '8',
  },
  {
    businessName: 'Twitter Share',
    attributeName: 'twitter_share',
    description: 'Refers to if the Offer\'s Twitter share is enabled or disabled',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'True/False',
    lovType: '8',
  },
  {
    businessName: 'Valid For',
    attributeName: 'valid_for',
    description: 'Award or Privilege Validity, Applicable only for Award and Privilege offers',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '6',
    lovType: '10',
  },
  {
    businessName: 'Valid Period',
    attributeName: 'valid_period',
    description: 'Award\'s validity duration type i.e Days, Months, Years',
    sampleValue: 'TEXT',
    dataType: '',
    lookupType: 'DAYS/MONTHS/YEARS/DATE',
    lovType: '100',
  },
  {
    businessName: 'Valid Until',
    attributeName: 'valid_until',
    description: 'Privilege or Award End Date, Applicable only for Award and Privilege offers',
    sampleValue: 'DATETIME',
    dataType: '',
    lookupType: '2019-09-17 11:59:59.573+00',
    lovType: '64',
  },
  {
    businessName: 'Validity',
    attributeName: 'validity',
    description: 'Total validity duration of the Offer',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '6 months',
    lovType: '8',
  },
  {
    businessName: 'Version',
    attributeName: 'version',
    description: 'Refers to Offer\'s Version, number of times an offer has been launched(after updating)',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '2',
    lovType: '8',
  },
  {
    businessName: 'Featured Rank',
    attributeName: 'featured_rank',
    description: 'Is this is a featured Offer, this rank represents the display order on the member facing applications',
    sampleValue: 'NUMBER',
    dataType: '',
    lookupType: '3',
    lovType: '8',
  },
  {
    businessName: 'Featured',
    attributeName: 'featured',
    description: 'Determines whether the offer belongs to featured offer category, and the order of display of these can be configured',
    sampleValue: 'BOOLEAN',
    dataType: '',
    lookupType: 'YES/NO',
    lovType: '8',
  },
  {
    businessName: 'Offer Tags',
    attributeName: 'tags',
    description: 'Used for optimizing Offer\'s search and recommendations, also called facets',
    sampleValue: 'LOOKUP',
    dataType: 'OFFER_TAGS',
    lookupType: 'Coffee',
    lovType: '50',
  },
];
