import type { DataModelAttribute } from '../types';

export const paymentAttributes: DataModelAttribute[] = [
  {
    businessName: 'Active',
    attributeName: 'active',
    description: 'Status of the Card.',
    sampleValue: 'YES',
    dataType: 'BOOLEAN',
    lovType: '100',
  },
  {
    businessName: 'Bank Code',
    attributeName: 'bank_code',
    description: 'Code of the bank used for transaction.',
    sampleValue: 'BARB0JASAMR',
    dataType: 'LOOKUP',
    lookupType: 'BANK_CODE',
    lovType: '100',
  },
  {
    businessName: 'Card Type',
    attributeName: 'card_type',
    description: 'Type of the Card used for transaction.',
    sampleValue: 'Platinum',
    dataType: 'LOOKUP',
    lookupType: 'PAYMENT_CARD_TYPE',
    lovType: '100',
  },
  {
    businessName: 'Code',
    attributeName: 'code',
    description: 'Payment Code',
    sampleValue: 'AB00123',
    dataType: 'TEXT',
    lovType: '50',
  },
  {
    businessName: 'Payment Name',
    attributeName: 'name',
    description: 'Name of the payment instrument.',
    sampleValue: 'American Express Platinum Card',
    dataType: 'TEXT',
    lovType: '255',
  },
  {
    businessName: 'Payment Type',
    attributeName: 'type',
    description: 'Type of payment',
    sampleValue: 'Credit Card',
    dataType: 'LOOKUP',
    lookupType: 'PAYMENT_TYPE',
    lovType: '100',
  },
  {
    businessName: 'Valid for Reward',
    attributeName: 'valid_for_accrual',
    description: 'If the method is valid for points accrual or not.',
    sampleValue: 'Yes',
    dataType: 'LOOKUP',
    lookupType: 'BOOLEAN_TYPE',
    lovType: '100',
  },
];
