import type { DataModelAttribute } from '../types';

export const productAttributes: DataModelAttribute[] = [
  {
    businessName: 'Sponsor',
    attributeName: 'sponsor',
    description: 'Sponsor to which the Product belongs to',
    sampleValue: 'Jumeirah Hotel',
    dataType: 'LOV',
    lovType: 'SPONSOR_LIST',
  },
  {
    businessName: 'Product Name',
    attributeName: 'name',
    description: 'Product\'s Name, visible in GRAVTY and also on the member facing portals',
    sampleValue: 'Casual Dining',
    dataType: 'TEXT',
  },
  {
    businessName: 'Product Description',
    attributeName: 'description',
    description: 'Brief description about the product,visible on the member facing portals',
    sampleValue: 'Offer for Casual Dining',
    dataType: 'TEXT',
  },
  {
    businessName: 'Type',
    attributeName: 'type',
    description: 'Determines the Product type like Award/Privilege/Award + Reward',
    sampleValue: 'Award',
    dataType: 'TEXT',
  },
  {
    businessName: 'Product Category',
    attributeName: 'category',
    description: 'Product\'s category',
    sampleValue: 'Dining',
    dataType: 'LOOKUP',
    lookupType: 'PRODUCT_CATEGORY',
  },
  {
    businessName: 'Product Line',
    attributeName: 'line',
    description: 'Line of the Product',
    sampleValue: 'Restaurant',
    dataType: 'LOOKUP',
    lookupType: 'PRODUCT_LINE',
  },
  {
    businessName: 'Cost',
    attributeName: 'cost',
    description: 'Product\'s cost incurred to the Sponsor',
    sampleValue: '224',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Award Currency',
    attributeName: 'award_currency',
    description: 'when a product is awarded to the member, the points would be deducted from this loyalty account',
    sampleValue: 'points',
    dataType: 'LOV',
    lovType: 'LOYALTY_ACCOUNT_LIST',
  },
  {
    businessName: 'Award Price',
    attributeName: 'award_price',
    description: 'This represents the number of points to be deducted from loyalty account mentioned in award_currency',
    sampleValue: '3300',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Valid for',
    attributeName: 'valid_for',
    description: 'Validity - Duration number in days, months or years for which the product is valid for',
    sampleValue: '45',
    dataType: 'NUMBER',
  },
  {
    businessName: 'Valid Period',
    attributeName: 'valid_period',
    description: 'Product\'s Validity duration type',
    sampleValue: 'DAYS/MONTHS/YEARS/DATE',
    dataType: 'TEXT',
  },
  {
    businessName: 'Privilege Validity Start',
    attributeName: 'valid_start',
    description: 'Start Date of the Privilege when \'valid_period\' = DATE',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Privilege Validity End',
    attributeName: 'valid_end',
    description: 'End Date of the Privilege when \'valid_period\' = DATE',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Dynamic',
    attributeName: 'dynamic',
    description: 'Refers to if the Product price is Dynamic or not when given as privilege',
    sampleValue: 'Yes/No',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'Product Validity Start',
    attributeName: 'active_start',
    description: 'Validity - Start Date of the Product',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'Product Validity End',
    attributeName: 'active_end',
    description: 'Validity - End Date of the Product',
    sampleValue: '2019-09-17 11:59:59.573+00',
    dataType: 'DATETIME',
  },
  {
    businessName: 'As Privilege',
    attributeName: 'as_privilege',
    description: 'Determines if the product can be used as privilege',
    sampleValue: 'Yes/No',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'Common Deal Code',
    attributeName: 'cdc',
    description: 'Refers to Privilege Product\'s common Deal Code, privilege is issued to the members when valid code is present in transaction. Cannot be used directly in GRAVTY, need GIS implementation',
    sampleValue: 'JSPROCADIN1',
    dataType: 'TEXT',
  },
  {
    businessName: 'Stock Keeping Unit',
    attributeName: 'sku',
    description: 'Stock-keeping unit (SKU) is a unique ID of the product, the source system can pass their own tracking ID',
    sampleValue: '2324',
    dataType: 'TEXT',
  },
  {
    businessName: 'Transfer On Merge',
    attributeName: 'transfer_on_merge',
    description: 'Determines if we want to transfer the privileges when members are merged',
    sampleValue: 'Yes/No',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'External Privilege',
    attributeName: 'has_external_privilege',
    description: 'Refers to if there is or isn’t any external Privilege linked to the Product, when has_external_privilege_ is enabled, either external codes or external services can to be enabled',
    sampleValue: 'Yes/No',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'External Privilege Codes',
    attributeName: 'has_external_privilege_codes',
    description: 'Determines if there are external privilege codes associated with the product, enabled when has_external_privilege is enabled',
    sampleValue: 'Yes/No',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'External Privilege Service',
    attributeName: 'external_privilege_service',
    description: 'Determines if there is external privilege service to be used for giving privileges outside of GRAVTY, enabled only when has_external_privilege is enabled',
    sampleValue: 'Mobile API',
    dataType: 'LOV',
    lovType: 'EXTERNAL_PRIVILEGE_SERVICE',
  },
  {
    businessName: 'Privilege Type',
    attributeName: 'privilege_type',
    description: 'Privilege\'s type',
    sampleValue: 'Fixed-Discount',
    dataType: 'LOOKUP',
    lookupType: 'PRIVILEGE_TYPE',
  },
  {
    businessName: 'Tags',
    attributeName: 'tags',
    description: 'Used for optimizing product search and recommendations, also called facets',
    sampleValue: 'Coffee',
    dataType: 'LOOKUP',
    lookupType: 'PRODUCT_TAGS',
  },
  {
    businessName: 'Logo',
    attributeName: 'logo',
    description: 'Refers to the url of the logo uploaded',
    sampleValue: 'https//docs.gravtee.com/test_logo',
    dataType: 'TEXT',
  },
];
