import type { DataModelAttribute } from '../types';

export const sponsorAttributes: DataModelAttribute[] = [
  {
    businessName: 'Additional Emails',
    attributeName: 'additional_emails',
    description: 'Refers to Sponsor\'s additional email address. This would be cc\'ed in all of the communication emails to the primary email. This is not visible on the UI and is usually added through merchant portals',
    sampleValue: 'John123@gmail.com',
    dataType: 'LIST',
  },
  {
    businessName: 'Address',
    attributeName: 'address',
    description: 'Sponsor\'s mailing address',
    sampleValue: 'Jumeirah - Dubai - United Arab Emirates',
    dataType: 'TEXT',
  },
  {
    businessName: 'Annual Revenue',
    attributeName: 'annual_revenue',
    description: 'Sponsor\'s Annual Revenue',
    sampleValue: '$ 100M - 1B',
    dataType: 'LOOKUP',
    lookupType: 'ANNUAL_REVENUE',
  },
  {
    businessName: 'Assign a symbol for this Sponsor',
    attributeName: 'logo',
    description: 'Sponsor\'s Logo Image, the link is captured and stored, and can be called through an API',
    sampleValue: 'image.png',
    dataType: 'TEXT',
  },
  {
    businessName: 'Business Division',
    attributeName: 'business_division',
    description: 'Business Division describes the part into which a business, organization or company is divided.',
    sampleValue: 'Hotels',
    dataType: 'LOOKUP',
    lookupType: 'BUSINESS_DIVISION',
  },
  {
    businessName: 'Business Unit',
    attributeName: 'business_unit',
    description: 'A business unit is a department or team within an organization/Company',
    sampleValue: 'Hospitality',
    dataType: 'LOOKUP',
    lookupType: 'BUSINESS_UNIT',
  },
  {
    businessName: 'City',
    attributeName: 'city',
    description: 'Sponsor\'s City to which they belong to',
    sampleValue: 'Dubai',
    dataType: 'LOV',
    lovType: 'CITY_LIST',
  },
  {
    businessName: 'Contact Number',
    attributeName: 'phone_number',
    description: 'Sponsor representative\'s contact number',
    sampleValue: '1234567890',
    dataType: 'TEXT',
  },
  {
    businessName: 'Contact Person',
    attributeName: 'contact_person_name',
    description: 'Sponsor\'s contact person\'s name',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Country',
    attributeName: 'country',
    description: 'Sponsor\'s country',
    sampleValue: 'Dubai',
    dataType: 'LOV',
    lovType: 'COUNTRY_LIST',
  },
  {
    businessName: 'Email',
    attributeName: 'email',
    description: 'Sponsor representative\'s email ID',
    sampleValue: 'john@gmail.com',
    dataType: 'TEXT',
  },
  {
    businessName: 'Email Verified',
    attributeName: 'email_verified',
    description: 'Determines if the Email has been verified or Not, TRUE/FALSE, when sponsor is activated, then this becomes TRUE',
    sampleValue: 'true',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'Employee Count',
    attributeName: 'employee_count',
    description: 'Number of Employees in the Company/Organization i.e Sponsor',
    sampleValue: '10,001 - 20,000',
    dataType: 'LOOKUP',
    lookupType: 'EMPLOYMENT_COUNT',
  },
  {
    businessName: 'End Date',
    attributeName: 'end_date',
    description: 'End date of the Sponsor\'s validity',
    sampleValue: '46032',
    dataType: 'DATE',
  },
  {
    businessName: 'First Name',
    attributeName: 'contact_person_first_name',
    description: 'First Name of the Sponsor\'s Contact Person, and it will be a captured from the attribute Contact Name',
    sampleValue: 'John',
    dataType: 'TEXT',
  },
  {
    businessName: 'Group Cluster Name',
    attributeName: 'entity_name',
    description: 'Refers to the Holding/Parent Company',
    sampleValue: 'Jumeirah',
    dataType: 'TEXT',
  },
  {
    businessName: 'Header',
    attributeName: 'header',
    description: 'Header Image/Banner\'s image URL',
    sampleValue: 'www.https://jumeirah.com/image234.jpg',
    dataType: 'TEXT',
  },
  {
    businessName: 'Industry',
    attributeName: 'industry',
    description: 'Sponsor\'s Industry to which they belong to',
    sampleValue: 'Hotels',
    dataType: 'LOOKUP',
    lookupType: 'INDUSTRY_TYPE',
  },
  {
    businessName: 'Last Name',
    attributeName: 'contact_person_last_name',
    description: 'Last Name of Sponsor\'s Contact Person, and it will be a captured from the attribute Contact Name',
    sampleValue: 'Wick',
    dataType: 'TEXT',
  },
  {
    businessName: 'Payment Status',
    attributeName: 'payment_status',
    description: 'Refers to Sponsor\'s Payment Status (Applicable only for postpaid sponsors)',
    sampleValue: 'OK/Overdue',
    dataType: 'TEXT',
  },
  {
    businessName: 'PIN Code',
    attributeName: 'pin_code',
    description: 'ZIP code of the Sponsor\'s mentioned address',
    sampleValue: '34895',
    dataType: 'TEXT',
  },
  {
    businessName: 'Region',
    attributeName: 'region',
    description: 'Sponsor\'s region to which they belong to',
    sampleValue: 'Burj Al',
    dataType: 'LOV',
    lovType: 'REGION_LIST',
  },
  {
    businessName: 'Registered ID',
    attributeName: 'trade_license_number',
    description: 'Sponsor\'s legal ID or identification',
    sampleValue: 'BH344JUR',
    dataType: 'TEXT',
  },
  {
    businessName: 'Specially abled',
    attributeName: 'specially_abled',
    description: 'Determines if the Sponsor representative is specially abled',
    sampleValue: 'No',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'Sponsor Description',
    attributeName: 'description',
    description: 'Sponsor\'s Description',
    sampleValue: 'Jumeirah Hotels and Resorts is a luxury hotel company',
    dataType: 'TEXT',
  },
  {
    businessName: 'Sponsor Enrollment Form URL',
    attributeName: 'acquisition_url',
    description: 'Sponsor\'s enrollment form URL',
    sampleValue: 'https://www.jumeirah.com/en/join-now',
    dataType: 'TEXT',
  },
  {
    businessName: 'Sponsor Name',
    attributeName: 'name',
    description: 'Sponsor\'s Name, visible on member facing platforms and GRAVTY',
    sampleValue: 'Jumeirah Hotels',
    dataType: 'TEXT',
  },
  {
    businessName: 'Sponsor PIN',
    attributeName: 'pin',
    description: 'This PIN is used to validate whether a transaction is approved by the Sponsor owner/operator, the PIN can be 4 digit numeric value',
    sampleValue: '3456',
    dataType: 'TEXT',
  },
  {
    businessName: 'Sponsor Short Name',
    attributeName: 'short_name',
    description: 'Sponsor\'s Short Name, Unique in the program and can be used as alternative to sponsor\'s name',
    sampleValue: 'Jumeirah',
    dataType: 'TEXT',
  },
  {
    businessName: 'Sponsor Status',
    attributeName: 'status',
    description: 'Sponsor\'s present status',
    sampleValue: 'Active',
    dataType: 'TEXT',
  },
  {
    businessName: 'Start date',
    attributeName: 'start_date',
    description: 'Sponsor\'s Validity Start Date',
    sampleValue: '44197',
    dataType: 'DATE',
  },
  {
    businessName: 'Tags',
    attributeName: 'tags',
    description: 'Used for optimizing Sponsor\'s search and recommendations, also called facets',
    sampleValue: 'Coffee',
    dataType: 'LOOKUP',
    lookupType: 'SPONSOR_TAGS',
  },
  {
    businessName: 'Title',
    attributeName: 'contact_person_title',
    description: 'Contact Person\'s Title',
    sampleValue: 'Mr/Mrs/Sir',
    dataType: 'TEXT',
  },
  {
    businessName: 'Url',
    attributeName: 'url',
    description: 'Sponsor\'s website URL',
    sampleValue: 'https://www.jumeirah.com/en/stay/dubai/burj-al-arab-jumeirah',
    dataType: 'TEXT',
  },
  {
    businessName: 'Visible Name',
    attributeName: 'brand_name',
    description: 'Name of the Brand represented by the sponsor, can be used on the member facing applications',
    sampleValue: 'Jumeirah Hotels',
    dataType: 'TEXT',
  },
  {
    businessName: 'Woman entrepreneur',
    attributeName: 'woman_entrepreneur',
    description: 'Determines if the Sponsor is headed by Woman Entrepreneur',
    sampleValue: 'Yes/No',
    dataType: 'BOOLEAN',
  },
  {
    businessName: 'Sponsor PIN Threshold',
    attributeName: 'sponsor_pin_threshold',
    description: 'This attribute defines the maximum BIT amount that can be passed for a particular sponsor transaction when it has to be validated via Sponsor/Location PIN.',
    sampleValue: 'Number',
    dataType: 'Number',
  },
];
